### ISSUE TITLE
Providing typescript definition file

### ISSUE THREAD

**Issue by maku** [arangodb/arangojs#108]
It would be useful when a typescript definition file for using arangojs is available

**Comment by jamesmoey** [comment]
+1

**Comment by pluma** [comment]
@jamesmoey Please use the reaction (smiley face with a plus in the top right corner of the issue description or comment) feature GitHub introduced for +1/-1 style comments unless you wish to elaborate. If you just want to subscribe to updates to an issue, you can subscribe to notifications using the Subscribe button in the sidebar on the right.

**Comment by ciscoheat** [comment]
If someone wants a good start for creating one, here are strongly typed definitions for Haxe, which should be quite easy to convert to typescript: https://github.com/ciscoheat/haxe-js-kit/tree/arangojs/js/npm/arangojs

**Comment by dothebart** [comment]
Thanks to @brabes for providing the implementation required for this.

**Comment by andregs** [comment]
Hi @brabes and others. Is this file available via arangojs npm package? Can you please provide an example of how to use it?

**Comment by daffunn** [comment]
@dothebart @brabes Why do we have dependencies of express in there?
E.g. I´d like to use it with hapi.js.

**Comment by pluma** [comment]
@daffunn yeah, that doesn't look quite right. It's using the Request and Response definitions from express's typescript definitions I guess?

**Comment by daffunn** [comment]
Yes, that's right. But this project does originally have no dependencies on express right? This should be changed accordingly.
Furthermore I hope that there will be a new release of this project soon. Really looking forward to use this db, but I rely on Typescript as well.

**Comment by daffunn** [comment]
@pluma I created a PR. https://github.com/arangodb/arangojs/pull/314
