### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by mknittig** [arangodb/arangojs#11]
The documentation shown on the GitHub page (README.md) for this driver is wrong. This is quite frustrating for first time user. At least the source code is pretty well documented (although it would be good to have some kind of cookbook).

**Comment by pluma** [comment]
The documentation on the NPM page is for the 2.x version of the driver. The documentation on this repo is for the upcoming 3.x rewrite you can currently get by installing `arangojs@rc` (or `arangojs@^3.0.0-rc`). The proper 3.0.0 release is scheduled for later this week.

Which version are you referring to?

**Comment by mknittig** [comment]
Ah OK, not sure if I want the new driver then. What's the advantage over the old one (who seems to have more functionality)?

**Comment by pluma** [comment]
It's more lightweight and more low-level. The intent is to provide just enough abstractions to make the driver useful on its own but also keep it lean enough to provide a basis for custom abstraction layers on top of it (analogous to how guacamole builds on ashikawa-core for the Ruby drivers, or how many other DB drivers are written in the node ecosystem).

It's written with modularity in mind. For example it doesn't provide a query builder of its own, instead you should use the `aqb` module, which is also shipped with ArangoDB 2.3+ and can be used separately. It also no longer provides a promise-based API out of the box and instead embraces node-style callbacks. Most promise libraries (e.g. bluebird or Q) make it trivial to consume node-style callbacks and cutting promise support out of the core significantly reduces redundancy, complexity and file size (which matters for front-end use).

If you prefer the old driver, kaerus' original fork of it is still available as `arango` on NPM and will be around as long as he maintains it.

**Comment by mknittig** [comment]
Well, I already have written a good chunk of code with the old driver. But I will definitely have a look at the new driver. And I still feel the documentation could be improved..
