### ISSUE TITLE
inEdges and outEdges are not defined on GraphEdgeCollection

### ISSUE THREAD

**Issue by arigrant** [arangodb/arangojs#116]
EdgeCollection defines inEdges and outEdges but GraphEdgeCollection inherits BaseCollection and not EdgeCollection.

**Comment by pluma** [comment]
That is correct. The API of GraphEdgeCollection merely provides the functionality the HTTP API provides.

It would probably be easy to support the additional methods provided by EdgeCollection for convenience. I'll see what I can do.

**Comment by pluma** [comment]
Fixed via 24ef208c551bf98a490a6d4fed42a9cea788bfeb and published as 4.1.0

**Comment by arigrant** [comment]
Awesome. Thanks!
