### ISSUE TITLE
Migrate API docs to GitBook/alternative?

### ISSUE THREAD

**Issue by pluma** [arangodb/arangojs#123]
The API docs are becoming a bit unwieldy, nearing 100 kB. NPM has started cutting the README.md off mid-sentence. Bumping the version for documentation updates is also a bit silly. We need something smarter than just dumping it all in README.md and praying for the best.

It's probably a good idea to switch to GitBook which is used by ArangoDB and other JS projects (e.g. Redux).

**Comment by dothebart** [comment]
the 10 minutes could become a part of that.

**Comment by pekeler** [comment]
Yes, better docs navigation would be great.

**Comment by pluma** [comment]
Docs live at https://github.com/arangodb/arangojs/blob/master/docs/Drivers/JS/README.md for now. Still require some more detailed splitting but this is a start.
