### ISSUE TITLE
first*() returning null

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangojs#131]
I understand if you don't want to change this now, but...

I would have preferred if the first*() methods returned null in the 404 case. With the current behaviour, I need to implement my getOrCreate() like

```JavaScript
function getOrCreate(params) {
  return new Promise((resolve, reject) => {
    myCollection.firstExample({what, ever})
    .then(resolve)
    .catch((error) => {
      if (error.code === 404) {
        let newDoc = {...};
        myCollection.save(newDoc)
        .then(() => resolve(newDoc))
        .catch(reject);
      } else {
        reject(error);
      }
    });
  });
}
```
which has my happy path implemented in a catch. Whereas if it'd return null, it would look like

```JavaScript
function getOrCreate(params) {
  return new Promise((resolve, reject) => {
    myCollection.firstExample({what, ever})
    .then((existingDoc) => {
      if (existingDoc) {
        resolve(existingDoc);
      } else {
        let newDoc = {...};
        myCollection.save(newDoc)
        .then(() => resolve(newDoc))
        .catch(reject);
      }
    }).catch(reject);
  });
}
```
which I find nicer to read and is even a line shorter.

**Comment by pluma** [comment]
I think the following would be even simpler:

```js
function getOrCreate(params) {
  return myCollection.firstExample({what, ever})
  .catch((error) => {
    if (error.code === 404) {
      let newDoc = {...};
      return myCollection.save(newDoc)
      .then(meta => Object.assign(newDoc, meta));
    }
    return Promise.reject(error);
  });
}
```

I agree that null would be nicer because it's more consistent with server-side `firstExample` but the driver aims to be consistent with the REST API more than the server-side JS API.

**Comment by pekeler** [comment]
Thank you for that coding tip!
I agree with your aim of being consistent. I guess my issue is with the REST API then. Closing this.
