### ISSUE TITLE
Problem with port when using a string as connection

### ISSUE THREAD

**Issue by ciscoheat** [arangodb/arangojs#174]
When I create a database using a string, the default port for the `Route` call is port 80 instead of the default. For example:

```js
var db = new arangojs.Database("mydb");
var route = db.route("_api/document");
route.get("articles/A11", function(err, res) {
    console.log(err); // Error: connect ECONNREFUSED 127.0.0.1:80
});
```

Using an object as initialization works however:

```js
var db = new arangojs.Database({databaseName: "mydb"});
var route = db.route("_api/document");
route.get("articles/A11", function(err, res) {
    console.log(res.body); // Works
});
```

As does specifying the database with the API, but not if you're instantiated with a string.

```js
var db = new arangojs.Database().useDatabase("mydb");
var route = db.route("_api/document");
route.get("articles/A11", function(err, res) {
    console.log(res.body); // Works
});

// Doesn't work:
var db = new arangojs.Database("mydb").useDatabase("mydb");
var route = db.route("_api/document");
route.get("articles/A11", function(err, res) {
    // Error
});
```

**Comment by pluma** [comment]
That is correct. The string argument is a connection string, not a database name. See: https://github.com/arangodb/arangojs#new-database

It would be confusing if the argument would be handled as a database name or connection string depending on its format.

**Comment by ciscoheat** [comment]
Yes, of course. I've been staring at the documentation too long. :) Which is a great documentation btw, thanks to it, I've just completed arangojs typedefs for [Haxe](http://haxe.org), available here: https://github.com/clemos/haxe-js-kit/tree/develop/js/npm/arangojs
