### ISSUE TITLE
Implement Simple queries?

### ISSUE THREAD

**Issue by pluma** [arangodb/arangojs#18]
See https://docs.arangodb.com/HttpSimpleQuery/README.html and https://docs.arangodb.com/HttpIndexes/Hash.html

**Comment by pluma** [comment]
@fceller with geo-spatial, fulltext and AQL queries already being supported by the driver, do we really need to support the other simple queries? A high-level driver could easily emulate them using simple AQL queries.

**Comment by fceller** [comment]
AQL is enough.
