### ISSUE TITLE
node.js + foxx session feature

### ISSUE THREAD

**Issue by phal0r** [arangodb/arangojs#20]
Hi Guys,

I am currently developing an authentication and session scheme for hapi.js with foxx. To identify the request in foxx I have to send the session cookies with every request (of course). My question is how to obtain the session id in first place using the arangojs driver, since node.js wont keep automatically track on the cookies like the browser does. I was looking at the source code and couldn't find any way to access the response headers. So my only solution would be to make an own request at first to store the session id and then use the arangojs driver, but i dont want to build the url on my own. How is it supposed to work?

Thanks in advance!

**Comment by pluma** [comment]
I've added the response object to all request callbacks. You should be able to call your Foxx routes as expected and receive the response object as the third argument (first being the error if any, second the (parsed, if JSON) response body and third the response object itself).

**Comment by phal0r** [comment]
Hey,

i tried the version from github and i can access them with response.headers. So, yes it solves my use case, thank you.
