### ISSUE TITLE
Retrieve nested structures

### ISSUE THREAD

**Issue by tthil** [arangodb/arangojs#209]
I need to receive a nested structure when I do a traversal on my edge collection. Right now I receive a flat structure. Is there any way to achieve this in arangojs? 
Example of the structure I want to achieve is like this. 
{
"proposalId": 12345,
"name": "ABCDE",
  "trips": [
    {"name": "trip1"},
    {"name": "trip2"},
    {"name": "trip3"}
]
}

//Thomas

**Comment by dothebart** [comment]
Hi, You can compose the return document in any way you need it.

I recently added a mored detailed description how to achieve this to https://github.com/arangodb/arangodb/blob/2.8/Documentation/Books/Users/Documents/README.mdpp

However, we didn't publish a nicely rendered version of it yet.

Hope this helps.

**Comment by tthil** [comment]
So the proper way to achieve this is by using AQL?

//Thomas

**Comment by dothebart** [comment]
Yes, exactly.

**Comment by tthil** [comment]
In your example. If you have your hobbies in a separate collection and connect them via a edge collection how would you retrieve the same nested result?

**Comment by tthil** [comment]
I have 2 collections. One proposals and one trips. They are connected via a edge collection named belongsTo. Would it be possible to retrieve this two collection as one nested result?

//Thomas

**Comment by dothebart** [comment]
have a look at https://docs.arangodb.com/Aql/GraphTraversals.html#combining-several-filters and play a little with the examples on arangosh, it should become clear whats to be done.
