### ISSUE TITLE
Bulk Import bug

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/arangojs#21]
Hi,

`type` of import function should be defaults to "auto". However, if I do not give opts argument, and then import an array of document, I will become such error:

```
[ArangoError: no JSON string array found in first line]
```

I believe it's still a bug of request parameter. Please fix.

Bg,
Kevin

**Comment by pluma** [comment]
Does it work if you specify `type: "auto"` explicitly? I think the default value was accidentally dropped when I added support for JSON-LD (JSON "streams").

**Comment by kevinprotoss** [comment]
Yes, it work, if specify `type: "auto"`explicitly.

**Comment by pluma** [comment]
Fixed in 3.3.1.
