### ISSUE TITLE
ORM

### ISSUE THREAD

**Issue by tthil** [arangodb/arangojs#215]
Is there any ORM layer to use with arangojs?

//Thomas

**Comment by pluma** [comment]
Not yet, no. But depending on what you're trying to do, it may be more efficient to write your JS apps directly in the database using [ArangoDB Foxx](https://foxx.arangodb.com). Foxx supports [joi](https://www.npmjs.com/package/joi) for schema validation in lieu of an ORM.

**Comment by tthil** [comment]
What is the best practice when it comes to combine 2 or more collection using traversals?
At the end we need to have the result as an JSON structure but all traversals return an array with objects.

//Thomas

**Comment by pluma** [comment]
Without knowing what you're specifically thinking of, I'd recommend using AQL queries where possible. You can manage complex queries easily by using the `aql`/`aqlQuery` template string handler provided by arangojs (and inside ArangoDB 2.8 and up). You can easily perform traversal in AQL, too: https://docs.arangodb.com/Aql/GraphTraversals.html

**Comment by lvarayut** [comment]
AQL is very low level, throwing AQL everywhere in source code might not be a good idea. When you build a very complex app, you will end up with a lot of complex queries, hard to read, and difficult to maintain.  It would be great if you had an ORM. For example, MongoDB has [Mongoose](http://mongoosejs.com/), MySQL has [Sequelize](https://github.com/sequelize/sequelize), to define all the schema relations. So, when you want to fetch a collection that is related to another collection, you could tell the ORM to automatically retrieve the related collection for you.

**Comment by pluma** [comment]
@lvarayut I can see where you're coming from but we do not plan to create an official ORM implementation. If someone from the community thinks there is value in having a dedicated ArangoDB ORM and creates one we'll gladly announce it and link to it on our website.

I think that most traditional use cases of having a server-side ORM can be solved equally well with a domain-specific API built using Foxx. One of our main goals with the rewrite of Foxx for ArangoDB 3.0 has been to reduce the barrier to entry for Node.js developers and the amount of boilerplate necessary to develop Foxx services.

The main advantages of Foxx over an ORM are that it reduces network overhead while allowing transactional guarantees (just do all the queries and updates in one place), that it avoids implementing your persistence layer in every service interfacing with the database (e.g. if you have services in different languages accessing with ArangoDB you'd need to maintain separate implementations of the same logic in each language, which also makes it harder to move the service to a new language later), and that it can help protect your data by only exposing the information your services (i.e. your authenticated users) should actually be able to access.

**Comment by lvarayut** [comment]
Thanks for your explanation. I think that Foxx and ORM are totally two different things, correct me if I'm wrong. The main propose of Foxx is to reduce network overhead by running the logic inside DB. However, the main propose of ORM is to help you define your collection relations, so, you could persist/retrieve the data easier. 

For example, let's say, we have User and Story collections. A user can create many stories, so, the relation between them is 1:M. The relation should be defined in ORM. When we want to retrieve the user object along with stories. We will tell the ORM; "hey, I need a user object whose userId equals to 1, and also give me his stories array too. The result would be roughly like this:

```js
"user": {
    "name": "John",
    "lastName": "Doe",
    "stories": [{
        ...
    }]
    ...
}
```

To persist the data, we just need to tell ORM; "here is the user object with stories array, persist the user object and stories array to the User and Story collections respectively" 

Without the ORM, you need to write AQL to retrieve and persist the data. This is just very simple example. In reality, you might have very complex AQL queries that will make you a lot of troubles. 

Foxx is not the replacement of ORM. On the other hands, they should work together, Foxx could use ORM to organize collection relations.

**Comment by ciscoheat** [comment]
But you will certainly hit speed issues with an ORM and complex queries, so eventually you must write a specialized query. It's fine for simple CRUD-like cases, but when things get complex and dynamic, as most real-life systems are, handling static relations in an ORM is wishful engineering thinking. :)

**Comment by pluma** [comment]
@lvarayut Aside from the speed difference there's also the problem that ORMs don't lend themselves to transactions: in your example you may run into conflicts (or worse: data loss) if the database changes between you telling the ORM "give me these things" and "now store these updated things". The idea of having a domain-specific (rather than persistence implementation-specific) API is that you can represent complex aggregate behaviour with a single endpoint.

ORMs merely map tables/collections to programming language level entities -- Foxx can abstract away those concepts entirely behind an API that makes sense to your application.

**Comment by uMaxmaxmaximus** [comment]
@tthil look at this https://www.npmjs.com/package/ormjs

**Comment by pluma** [comment]
We don't currently plan any official ORM. If the community wants to provide/champion any external ORM solution they may be added to the drivers page on the website (just hit us up on Slack or twitter).

**Comment by MisaZ10** [comment]
Now exists orango but is alpha
Inspired by Mongoose
https://github.com/roboncode/orango
