### ISSUE TITLE
`autoCreate` option for db.query function

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/arangojs#22]
Hi,

Maybe it's only a suggestion. Is it possible to implement some options like `autoCreate` in db.collection function for db.query function as well. If I use db.query to make some modification query, such as insert, arangoDB instance will always complain about collection not existing. 

Bg,
Kevin

**Comment by pluma** [comment]
Not at the driver level, no. You could parametrize the collection names (i.e. pass them in as parameters to the query using the `@@` syntax) and wrap `db.query` in a function that performs the necessary steps for each collection name in the parameters.
