### ISSUE TITLE
collection.firstExample throws ArangoError if no document matched the example instead of returning undefined

### ISSUE THREAD

**Issue by disharmonized** [arangodb/arangojs#225]
**Steps to reproduce:**
Call collection.firstExample(filter) with any "filter", that find nothing in your collection.

**Current Behaviour:**
It throw common ArangoError with 'no match' message

**Expected behaviour:**
Return undefined or null

**Comment by pluma** [comment]
This is because the driver mimics the behaviour of the HTTP API rather than ArangoDB's JavaScript API. The server returns a 404 with a "no match" error response.

We are considering taking steps to make the driver and "native" APIs more similar but right now it's "working as intended".

**Comment by arxpoetica** [comment]
So wait, am I understanding this correctly that you're actually throwing an error when `firstExample` doesn't find anything?

Can you recommend an alternative arangojs query technique that doesn't throw an error.

I can't imagine error handling every time I want to find *one* instance of something (a *very* common database operation) but having to handle it as an error every time it comes up empty handed (also a very common database result).
