### ISSUE TITLE
How can we establish a secure connection?

### ISSUE THREAD

**Issue by lalitlogical** [arangodb/arangojs#236]
I am working on NodeJs project. I have enabled the authentication for ArangoDB. I have added my own user to `_users` document named as 'admin'.

```
db._useDatabase("myDatabase");
require("org/arangodb/users").save("admin", "myPassword");
require("org/arangodb/users").reload();
```

I have not found proper doc for secure access of database. So I have write below to establish the secure connection but it is not working.

```
var arangojs = require('arangojs');
var server = arangojs({
  host: process.env.ARANGO_DB_SERVER_HOST,
  port: process.env.ARANGO_DB_SERVER_PORT
});

var db = server.useDatabase('GeoConnect', {
  username: process.env.ARANGO_DB_SERVER_USER_NAME,
  password: process.env.ARANGO_DB_SERVER_USER_PASSWORD
});
```

Please let me know, how can I achieve secure connection to my database?

**Comment by lalitlogical** [comment]
@pluma, @dothebart  can anyone help me on this?

**Comment by pluma** [comment]
What exactly are the errors you're seeing?

**Comment by pluma** [comment]
You should pass a connection string (including the username and password) and database name to arangojs directly. Check out the docs for `new Database` in the README.md.

**Comment by lalitlogical** [comment]
I am getting 'Unauthorised' error when I am changing the configuration file as below.

```
# disable authentication for the admin frontend
disable-authentication = no
```

```
var db = require('arangojs')({
  url: "http://some-ip-address:8529",
  // url: "http://localhost:8529",
  username: 'admin',
  password: 'myPassword'
});
db.useDatabase('myDatabase');

```

Without authorisation above work and connect with remote arangodb server. But not work when authorisation enables as above.

I have tried Connection property from [here](https://github.com/triAGENS/ArangoDB-JavaScript#quick-start)

```
var arango = require('arangojs');
var db = arango.Connection("http://my-ip-address:8529");
db.useDatabase('myDatabase');
```

```
var db = arango.Connection("http://myarangodb.server.com:8529");
                ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/standarduser/Documents/Lalit/CurrentProject/GeoConnect/app.js:36:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by pluma** [comment]
@lalitlogical the repo you're linking to is an older version of the driver that is no longer maintained (2.x, current version is 4.x). The `Connection` is not part of the API of arangojs 4.x.

Please see the README from this repo:

> # Database API
>
> ## new Database
>
> `new Database([config]): Database`
>
> Creates a new Database instance.
>
> If *config* is a string, it will be interpreted as *config.url*.
>
> **Arguments**
>
> * **config**: `Object` (optional)
>
>   An object with the following properties:
>
>   * **url**: `string` (Default: `http://localhost:8529`)
>
>     Base URL of the ArangoDB server.
>
>     If you want to use ArangoDB with HTTP Basic authentication, you can provide the credentials as part of the URL, e.g. `http://user:pass@localhost:8529`.

In other words, do this:

```js
var arango = require("arangojs");
var db = arango({
  url: "http://admin:myPassword@some-ip-address:8529",
  databaseName: "myDatabase"
});
```

If you get the address or credentials from environment variables you can build the connection string by concatenation or using ES6 string templates.

I'll extend the introductory usage examples to show how to do this.

**Comment by lalitlogical** [comment]
@pluma I have modified my code as your suggestions and it's working now.

```
var arango = require("arangojs");
var url = "http://"+process.env.ARANGO_DB_SERVER_USER_NAME+":"+process.env.ARANGO_DB_SERVER_USER_PASSWORD+"@"+process.env.ARANGO_DB_SERVER_HOST+":"+process.env.ARANGO_DB_SERVER_PORT;
var db = arango({
  url: url,
  databaseName: "GeoConnect"
});
```

Thanks for help 👍

**Comment by shivarajnaidu** [comment]
What can i do if i didn't set password for root user?
how i do the above in this case ? @pluma

**Comment by CoDEmanX** [comment]
Leave user and password out if it's `root` and a blank password. It should default to the root user. 

If you want to login as another user with an empty password, follow this scheme: `http://user:@host` (note the colon).
