### ISSUE TITLE
aql is not a function

### ISSUE THREAD

**Issue by bravedick** [arangodb/arangojs#242]
Should not it be `require('arangojs').aqlQuery;` in docs?

https://github.com/arangodb/arangojs#aql

**Comment by bravedick** [comment]
found. it was renamed in latest version.

**Comment by pluma** [comment]
Yes, the old name should still work though.

**Comment by rjravijain** [comment]
> found. it was renamed in latest version.

@bravecow can you please share what did you find.?
I am trying to do this operation:

aqlQuery = require('arangojs').aqlQuery;
db.query(aqlQuery`
FOR doc IN ${collection}
LET value = 100 + doc.value
INSERT {
_key: CONCAT("new", doc.value),
value
} INTO ${collection}
RETURN NEW
`).then(
cursor => cursor.map(doc => doc._key)
).then(
keys => console.log('Inserted documents:', keys.join(', ')),
err => console.error('Failed to insert:', err)
);

I am getting the following error:
>TypeError: aqlQuery is not a function

ref: https://www.arangodb.com/tutorials/tutorial-node-js/

**Comment by pluma** [comment]
@rjravijain the import was renamed from `aqlQuery` to `aql` in arangojs 6. If you're following the tutorial make sure to follow it closely as it was written for arangojs 5 and hasn't yet been updated. You can npm install `arangojs@5` (as indicated in the tutorial) to install that version of arangojs.
