### ISSUE TITLE
Is it possible to call neighbors from arangojs?

### ISSUE THREAD

**Issue by bravedick** [arangodb/arangojs#243]
I am about this method: https://docs.arangodb.com/GeneralGraphs/Functions.html#neighbors

And if AQL-only, is it possible to pass named params to NEIGHBORS?

**Comment by pluma** [comment]
The driver only wraps the HTTP API so it only offers the endpoints exposed by ArangoDB as part of that API. For questions regarding AQL you will have to open an issue on the ArangoDB repository or ask in the community slack (at https://slack.arangodb.com).
