### ISSUE TITLE
arangojs in the browser?

### ISSUE THREAD

**Issue by ciscoheat** [arangodb/arangojs#245]
I see this file `arangojs.min.js`, but how to use it in the browser? Nothing happens when it's loaded, and it doesn't seem to export or expose any variables.

**Comment by pluma** [comment]
Good catch. Upon closer inspection the webpack config doesn't seem to specify that the bundle should actually expose something.

**Comment by ciscoheat** [comment]
I got a PR for this soon.

**Comment by pluma** [comment]
I've published 5.0.2 containing the fixes.

**Comment by ciscoheat** [comment]
I'm afraid you gotta republish it because of a spelling mistake. I've made a line comment about it.

**Comment by pluma** [comment]
Thanks. I've force-pushed the release's tag so it covers the new bundle. Luckily the NPM release doesn't include the browser bundle.
