### ISSUE TITLE
Handling "undefined" in JSON

### ISSUE THREAD

**Issue by dsonet** [arangodb/arangojs#257]
When {exampleKey: undefined} passed, it will always return a document which should not return any document.

**Comment by jsteemann** [comment]
When using such example object it will be converted to JSON before being sent to ArangoDB (ArangoDB has a JSON API and stores JSON data after all). But in JSON there is no such thing as `undefined`.

In pure JavaScript the following code will only return an empty object (`{}`), and that is also what's being sent as an example to ArangoDB:
```js
> a = { exampleKey: undefined };
> JSON.stringify(a);
{}
```
In the end using `{ exampleKey : undefined }` will lead to querying an example document with an empty example `{ }` and that matches all documents.

**Comment by dsonet** [comment]
@jsteemann IC. That undefined is not from JSON, but was produced in JavaScript. It based on some other data operation. So means that I have to check it before pass to collection.firstExample.

**Comment by dothebart** [comment]
@dsonet the best way to get this fixed is to use AQL to query the data you need. You then need to handle that key to be gone and instert `FILTER ! HAS(x, 'examplekey')` in your query. ( see https://docs.arangodb.com/3.0/AQL/Functions/Document.html#has for more information)
