### ISSUE TITLE
Creating graphs with multiple edge definitions

### ISSUE THREAD

**Issue by ropeladder** [arangodb/arangojs#259]
I'm trying to create a "combined" graph that is a combination of my other graphs, but when I try to add edge definitions arangojs gives me back this error:
`error: ArangoError: [name of collection I already used] edge collection already used in edge def`

This is presumably because I already used the edge collection in another graph definition. But I cannot figure out how to re-use edge definitions that I have already defined elsewhere and can't figure out anything from the documentation.

My code looks like this (the second bit throws the error):

```
db.graph('myGraph1').create({edgeDefinitions: [{ collection: 'edge1',from:['doc1'],to:['doc2']}]}).then( ... )

db.graph('combinedGraph').create({edgeDefinitions: [
    { collection: 'edge1',from:['doc1'],to:['doc2']},
    { collection: 'edge2',from:['doc1'],to:['doc3']}
]}).then( ... )
```

**Comment by pluma** [comment]
Hm... this sounds like a problem with ArangoDB's graph API. Could you open an issue with ArangoDB itself? I'm not sure whether this is a problem with the API or how we have wrapped it in arangojs.

**Comment by pluma** [comment]
I'm closing this issue in favour of the arangodb issue referencing this one. Should this turn out to be an issue with arangojs itself, feel free to reopen it at any point.
