### ISSUE TITLE
Add optional promise support

### ISSUE THREAD

**Issue by pluma** [arangodb/arangojs#26]
We will not ship a promise implementation with arangojs. One of the major concerns the 3.0 rewrite addressed was making the library a lot more lightweight -- adding more dependencies (or rolling our own implementations) is not going to happen.

However there is a rightful demand for a promise based API. I think it's possible to support promises as return values without relying on a polyfill or promise library directly for those who don't want to use them.

The most obvious solution would be to check for the existence of a global `Promise` function when an async function is called. This could be achieved using a simple helper function like this (using ES6 destructuring for readability):

```js
function promisify (callback) {
  if (!callback) callback = noop;
  if (typeof Promise !== 'function') return {cb: callback};
  // ES6 Promise is supported
  var cb;
  var p = new Promise(function (resolve, reject) {
    cb = function (err, res) {
      if (err) reject(err);
      else resolve(res);
      callback(err, res);
    };
  });
  return {cb, p};
}
```

and used like this:

```js
Database.prototype.createCollection = function (properties, callback) {
  var {cb, p} = promisify(callback);
  // … same logic as before …
  return p;
};
```

This would be entirely transparent for environments that don't support ES6 promises and result in miminal overhead in those that do. Non-ES6 environments could use a polyfill like [es6-promise](https://npmjs.org/package/es6-promise) (`require('es6-promise').polyfill();`) or a custom ES6-compatible promise implementation like [bluebird](https://npmjs.org/package/bluebird) (`global.Promise = require('bluebird');`).

**Comment by pluma** [comment]
I've pushed an experimental branch using the above solution for all async methods.

The total added weight is roughly 0.5 kB after minifying and gzip.

**Comment by legikaloz** [comment]
I will try the branch in a few days. In the meantime I'd suggest to differentiate sync and async functions somehow (in their names or so). What do you think?

A word about promises: Almost all major browser has enabled support for promises (notably except: ie, android browser bellow 4.4), node from 0.12, io.js from the beginning.

**Comment by pluma** [comment]
@legikaloz I hear you, but arangojs being a relatively low-level library the backward compatibility with browsers like IE8 is a big concern. You shouldn't be forced to add a promise library just so you can use a database driver in an IE8 project.

The only non-async methods are those that never have to perform any network I/O, e.g. `cursor.hasNext()` or `cursor.rewind()`, and `database.route()`. Since they're never async (and especially the last one shouldn't reasonably be expected to be async), I'm not sure how the name could be changed to anything more meaningful. Having `cursor.hasNextSync()` implies there's an async `cursor.hasNext()` -- which isn't necessary because it doesn't actually touch anything that could block.

**Comment by legikaloz** [comment]
I'm testing the promise support now, and i think i found a bug: the doc says that route functions return a promise, but there are no promise support in these functions (post,get...). 
Thank you for adding promise support. I've seen the documentation improvements about promises and sync/async distinction too :)

**Comment by pluma** [comment]
Could you tell me what environment you are running arangojs in? The promise support is only available if `global.Promise` (or `window.Promise` in the browser) is defined. If you use `bluebird`, you need to define `global.Promise = require('bluebird')` if the environment (e.g. Node 0.10) doesn't have ES6 promises.

I've just given it a try with `require('es6-promise').polyfill()` and everything works as expected, even route methods.

**Comment by legikaloz** [comment]
Sorry, promises seems to work (with native and bluebird too). I just replaced the lib and wondered why my code doesn't work. The real problem in the results: the old callback gave back an object with a `result` property contained the actual query result. Now the given object has a body.result property with the data. Also that object has a couple of unnecessary properties. Is this change intentional, or accidental?

**Comment by pluma** [comment]
That is right, the route methods now resolve to the response object (or in the browser the xhr object) and the actual result JSON can be found in the `body` property of that.

The reason behind this change is that previously the callback received three arguments (error, response body and response object) and promises can only resolve to a single value. The only alternative would have been to drop the response object from the promise or to resolve to an array of the two values (which would have been suboptimal IMO).
