### ISSUE TITLE
Unify arangojs and arangosh/arangodb JS API

### ISSUE THREAD

**Issue by pluma** [arangodb/arangojs#264]
As far as possible, arangojs should adhere to names and APIs provided in ArangoDB, even if this causes some redundancies like `db.create`/`db.createDocumentCollection` vs `db.collection().create`.

Some limitations:
- arangojs shouldn't try to bend the HTTP responses to match the ArangoDB JS return values as this may incur performance penalties
- arangojs should drop the `_` prefixes in database methods as the `db.<collectionName>` magic can't be meaningfully supported
- `db.collection()` should still return the collection object synchronously (so `collection.get()` needs to stay)

**Comment by Simran-B** [comment]
> the `db.<collectionName>` magic can't be meaningfully supported

Wouldn't a [proxy object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) be possible? Or is the actual problem about fetching the available collections?

**Comment by pluma** [comment]
This has been put on hold as we currently aim to unify the driver APIs first. Unifying the async arangojs and sync arangosh/arangodb APIs seems more difficult and may require changes on the arangosh/arangodb end which won't be up for discussion until 4.0.
