### ISSUE TITLE
collection.import opts argument is not optional as informed in the documentation

### ISSUE THREAD

**Issue by b-s-d** [arangodb/arangojs#27]
When calling `collection.import(data, [opts,] callback)` the `opts` argument is not being treated as optional as informed in the documentation.

For example, if you call import like: 
```javascript
collection.import([{name: 'abc'}], function(err){});
```

The following error is received on the callback:

*[TypeError: Cannot read property 'type' of undefined]*

My understanding is that the attribute `opts.type` is being expected in the implementation even when the `opts` is not being passed (see collection.js:189) :

```javascript
ld: Boolean(opts.type !== 'array')
```

**Comment by pluma** [comment]
Thanks for bringing this to our attention. I've published a bugfix release.
