### ISSUE TITLE
nodejs like callbacks?

### ISSUE THREAD

**Issue by shivarajnaidu** [arangodb/arangojs#272]
The latest version of arangojs uses `.then` method (promises).. but my question is... can I use nodejs like call backs? is it possible ?

**Comment by pluma** [comment]
You can do both. If you pass a callback, the methods will not return a promise and instead use the callback.

**Comment by shivarajnaidu** [comment]
I have seen for creating database.. can you please give me an example to create collection using nodejs style callback functions..

**Comment by pluma** [comment]
Hi @shivarajnaidu,

every method that is marked as `async` in the documentation can optionally take a callback as the last argument. If passed a callback, it won't return a promise and will instead treat the callback as a node-style "errback" (i.e. first argument will be the error or `null`, second argument will be the result).

If you find a function doesn't behave this way, that's probably an error.

**Comment by shivarajnaidu** [comment]
Hi , would you please give me an example to create a collection with node style callbacks .. sorry if my questions  looks like silly .. @pluma

**Comment by Simran-B** [comment]
```
let db = require("arangojs")();
db.collection("myNewCollection").create( function(err, data) { if (err) ... } );
// or shorter:
db.collection("myNewCollection").create( (err, data) => { if (err) ... } );
```

**Comment by shivarajnaidu** [comment]
Thanks Guys :+1:  :blush:
