### ISSUE TITLE
Cursor.all too slow for large query resultset

### ISSUE THREAD

**Issue by Kurtas** [arangodb/arangojs#274]
Hi, 

I have few queries which have big result set (> 100k rows) and I figured out that query is processed quite fast, but ```cursor.all()``` method which returns array of objects from cursor is too slow. 

Here is example:
```javascript
const db = new Arango(arangoConfig);
const aql = `FOR x IN 1..200000 RETURN x`;

console.time('query');
db.query(aql)
.then(cursor => {
  console.timeEnd('query');
  console.time('cursor.all');
  return cursor.all();
})
.then(results => {
  console.timeEnd('cursor.all');
  console.log(`Array length ${results.length}`);
});
```
*Result*
```
query: 147.187ms
cursor.all: 19426.323ms
Array length 200000
```

Can you do something about it, or it's normal?
BTW: I use arangojs@5.0.2

**After modification (see pull request)**
```
query: 148.247ms
cursor.all: 171.964ms
Array length 200000
```

Thanks a lot

**Comment by Kurtas** [comment]
Hi, can you release new version with this fix? It's almost 2 months from the commit. Thanks

**Comment by Kurtas** [comment]
Hi, it's me again :) ... Please can you release new version?

**Comment by pluma** [comment]
The latest version is now on npm.

**Comment by Kurtas** [comment]
Thanks a lot!
