### ISSUE TITLE
Allow _key set to null?

### ISSUE THREAD

**Issue by ciscoheat** [arangodb/arangojs#279]
I've noticed that when you save a document and have `_key` set to `null`, you'll get an `ArangoError` "invalid document key". Would it be ok to allow this, having ArangoDB set the key as if it doesn't exist, when you save it?

It can be useful when creating objects like this for example:

``` js
class Person {
    constructor(id, name) {
        this._key = id;
        this.name = name;
    }
}
```

My case is that I'm using the transpiler language Haxe, where fields are set automatically when instantiated, so you'll always have `_key == null`, and the only way to save an object is to make some shady Reflection stuff, deleting the field.

**Comment by pluma** [comment]
`undefined` and `null` have different meanings in JavaScript. A field set to `undefined` will be omitted in the JSON representation, a field set to `null` indicates an intentionally empty value.

Can you solve this problem on your end by explicitly initialising the value to `undefined` instead or is this a limitation of Haxe?

**Comment by ciscoheat** [comment]
That's the intention I was thinking about in this case, since `_key` cannot be empty in the database, setting the field to `null` could mean "set this for me, please". But it's no big issue for me.

Yes, it's a Haxe "limitation" :) It doesn't have undefined, unless you use some special functions and inject raw javascript. It would be nice to stay away from that, or using reflection.

**Comment by pluma** [comment]
Now that I think about it, there's never a reason for `_key` to be anything false-y, so it makes sense to clear the attribute if it would otherwise be something false-y (null, zero, empty string, what have you).

**Comment by ciscoheat** [comment]
That's what I'm thinking too, the only thing I can think of would be if someone sets it by mistake. But `_key` is a well-known, special attribute, so I'd be surprised if someone doesn't know about it, in these circumstances.

**Comment by pluma** [comment]
Changing this would require modifying the data passed to arangojs before sending it to the server. Doing that to obscure a potential error by obscuring sloppy input seems like a bad idea. I'm closing this issue as this won't be implemented. If you want the API to support `null` values, I suggest opening an issue at [ArangoDB](/arangodb/arangodb) instead.
