### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by sleepycat** [arangodb/arangojs#280]
Running the Arangojs test suite with ArangoDB 2.8.9 produces  errors like the following:

```sh
  1) Manipulating databases database.truncate removes all documents from all non-system collections in the database:
     Uncaught TypeError: Cannot read property 'map' of undefined
      at database.js:138:15
      at database.js:105:43
      at connection.js:112:16
      at callback (request.js:67:9)
      at IncomingMessage.<anonymous> (request.js:75:11)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

The calls to truncate are blowing up on line [138 of database.js](https://github.com/arangodb/arangojs/blob/4899bfb88913b5accf8c307e0a143dc596808834/src/database.js#L138):

```javascript
: all(collections.map((data) => (cb) => this._api.put(
```

`collections` is undefined. The reason appears to be in the [`listCollections`](https://github.com/arangodb/arangojs/blob/4899bfb88913b5accf8c307e0a143dc596808834/src/database.js#L97-L101) function:

```javascript
    const resultField = (
      this._connection.arangoMajor < 3
      ? 'collections'
      : 'result'
    )
```

`_connection.arangoMajor` is set by looking at the `x-arango-version` header (set by the client rather than the server) and as it stands with `this._connection.arangoMajor < 3` and ArangoDB 2.8.9, I get back a response from the server with an array of collections accessible via `res.body['collections']` but `listCollections` returns `res.body['result']` (undefined) which `truncate` then calls map on.

I've fixed this locally with the following change to `src/database.js`:

```javascript
-      this._connection.arangoMajor < 3
+      this._connection.arangoMajor == 3
```

I'm not fully sure that makes sense (given the various server versions and all) but it seems to solve the issue. The tests pass and all seems well again in the land of 2.8.9.
I'm happy to send a pull request if that seems right (and won't break anything else).

**Comment by pluma** [comment]
The test suite explicitly sets the ArangoDB version to the version set in the travis environment and defaults to 3.0 otherwise.

Try running the tests with `ARANGO_VERSION=28090`.

**Comment by sleepycat** [comment]
Ahh, OK. Thanks!
