### ISSUE TITLE
API for Data export and import as JSON or CSV !

### ISSUE THREAD

**Issue by shivarajnaidu** [arangodb/arangojs#297]
I have noticed there is a feature in web interface of ArangoDB which allows users to Download or Upload data as JSON file..
Is there any API available in ArangoJS  to Download and Upload Data from/to JSON or CSV file ?

**IF None is available please make one which will be very useful to node-arango devs**

Thanks !

**Comment by jsteemann** [comment]
It looks like there is at least `collection.import(data, [opts])` for importing (JSON) data into a collection. The documentation for it can be found here: https://github.com/arangodb/arangojs#collectionimport

To download all data from a collection as (JSON) objects, the is `collection.all([opts])` (see https://github.com/arangodb/arangojs#collectionall).

Note that I have never these them myself, but was just checking the arangojs docs.

**Comment by shivarajnaidu** [comment]
First of all Thanks for your answer @jsteemann 
But what I am exactly looking for is API interface which take JSON or CSV file path and can do upload download(export-import) like operations..

**Comment by Simran-B** [comment]
If you're using Node.js, you can simply read the desired file and call import() with what you read from the file - given that it's already in a supported format. Standard CSV requires a little parsing, but it's rather simple. Every row needs to become an array of strings (one per field), and the first array has to contain the attribute names. Stringify the arrays and separate every row with `\n`.

With JavaScript in a browser, there's the problem that it is not allowed to read arbitrary files. You would need to provide an input element and let the user select the file with it in order to use the FileReader API to read its content.

It's probably simpler to use `arangoimp` though. You can call it with the filepath of a CSV or (line-separated) JSON file you want to import, and it will do all the heavy-lifting.

**Comment by shivarajnaidu** [comment]
Hmmm ... I agree @Simran-B  ...  But , How about adding an API atleast it will take JSON file path as input and can able to upload it to db(import) or can save as specified filename with requested data(export).... Please consider this feature.. This will make dev life more easy with ArangoDB on Node... Will be very helpful..

I want all members to make discussion on this feature request  at least  ...

**Comment by dothebart** [comment]
I'd say the components are here, https://www.npmjs.com/search?q=csv -  https://docs.arangodb.com/3.0/HTTP/BulkImports/index.html maybe @shivarajnaidu you join them and discuss your findings with us? ;-)

**Comment by dothebart** [comment]
you probably also saw `js/contrib/CSV_export/CSVexport.js` which is part of the arangodb distribution - you simply need to adapt it to your needs.

**Comment by shivarajnaidu** [comment]
Hi  @dothebart  ,
would you please explain bit more about what is this `js/contrib/CSV_export/CSVexport.js` ..
sorry I am new to both arangodb as well as to node.. So i am not able to figure out myself what it (`js/contrib/CSV_export/CSVexport.js`) is actually..

**Comment by Simran-B** [comment]
You can find the file in your ArangoDB installation directory, e.g.<br>
`C:\Program Files\ArangoDB 3.0.5\share\arangodb3\js\contrib\CSV_export\CSVexport.js`

**Comment by pluma** [comment]
@shivarajnaidu try this:

```js
// export to JSON file
var fs = require('fs');
db.collection('myCollection').all().then(function (docs) {
  return new Promise(function (resolve, reject) {
    fs.writeFile('dump.json', JSON.stringify(docs, null, 2), function (err) {
      if (err) reject(err);
      else resolve();
    });
})
.then(function () {
  console.log('All done!');
})
.catch(function (err) {
  console.error('Something wrong', err);
});
```

```js
// import from JSON file
var fs = require('fs');
new Promise(function (resolve, reject) {
  fs.readFile('dump.json', 'utf-8', function (err, data) {
    if (err) reject(err);
    else resolve(data);
  });
})
.then(function (data) {
  var docs = JSON.parse(data);
  return db.collection('myCollection').import(docs, {type: 'documents'});
});
```

I haven't tried this out but it should work using arangojs.

**Comment by shivarajnaidu** [comment]
I have already done this and even it is more easier than above.. No need to use promises.. etc .. But i thought feature I have requested will be useful and very helpful to others devs .. That's why i started conversation Here..  However , Thank You very Much... Great Response  From Community..

**Comment by shivarajnaidu** [comment]
And One more doubt .. Is Import method will withstand for large data.. 

For example if i Bulk Import 40000 records(documents) into a collection .. That's Okay or any side effects is there in using Bulk import and what is the safer limit of bulk import.. ?

**Comment by pluma** [comment]
I'm closing this issue as the original question seems to have been resolved. If you want CSV support in the API itself that would be an issue for ArangoDB, not arangojs.
