### ISSUE TITLE
How to create DB user from arangojs context (after the DB was created)?

### ISSUE THREAD

**Issue by oklemenz** [arangodb/arangojs#302]
For creating DB users I have found only the following in the documentation:

1.) https://docs.arangodb.com/3.0/Manual/Administration/ManagingUsers.html
2.) https://github.com/arangodb/arangojs#manipulating-databases
async database.createDatabase(databaseName, [users]): Object

I search for a way to automatically create users and grant database privilege from Node.js context after the database has already been created. Can this only be done via the arangoDB shell?

**Comment by pluma** [comment]
You're thinking of the HTTP API for creating users, not the ArangoDB API: https://docs.arangodb.com/3.0/HTTP/UserManagement/index.html

It's correct that arangojs currently doesn't wrap this API. You can however use the Route API to speak to arbitrary endpoints on the ArangoDB server, so you could use that as a workaround: https://github.com/arangodb/arangojs#route-api

**Comment by oklemenz** [comment]
Thx for pointing me to the right place...
