### ISSUE TITLE
How to create multi-collection graphs w/ arangojs?

### ISSUE THREAD

**Issue by arxpoetica** [arangodb/arangojs#304]
In version 2.2, the concept of multi-collection graphs was introduced: https://www.arangodb.com/2014/07/multi-collection-graphs/

How can I create a multi-collection graph in arangojs? Or is this not possible?

**Comment by pluma** [comment]
All graphs in ArangoDB are "multi-collection graphs". The General Graph API has replaced the old graph API, which was deprecated in 2.x a while ago and has been removed completely in 3.0.

Just pass multiple strings as collection names for the `from` and `to` values in the edge definitions when creating the graph if you want edges to connect sets of multiple collections:  https://github.com/arangodb/arangojs#graph-api

**Comment by arxpoetica** [comment]
Awesome. I'll check it out.
