### ISSUE TITLE
Expaired Links In ArangoJS Readme file (Documentation)

### ISSUE THREAD

**Issue by shivarajnaidu** [arangodb/arangojs#305]
Most of the Links Present in ArangoJS Documentation (README file) are expired Links..
Please Update With Latest Links..

For Example.. 
Go here ...  https://github.com/arangodb/arangojs/blob/master/README.md#accessing-collections
and click.. [ HTTP API for accessing collections](https://docs.arangodb.com/3.0/HttpCollection/Getting.html)

**Comment by pluma** [comment]
Closed via 13d91762999d51bf555a9a736950d43cee3c3f98
