### ISSUE TITLE
Can't insert documents immediately after creation of collections.

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangojs#309]
I have the next problem. I try to migrate my base from MongoDB to ArangoDB. But i found the issue.
Example:

```javascript
const dbCol = db.collection('androidclients');
yield dbCol.create();
yield dbCol.load(); // ERROR
```

This code is arounded by `wait.launch(function*() {})`, emulating async/await.
And the error is

> { ArangoError: unknown collection 'androidclients'
>     at new ArangoError (/Users/Dmitry/WebstormProjects/Chat/node_modules/arangojs/lib/error.js:30:15)
>     at /Users/Dmitry/WebstormProjects/Chat/node_modules/arangojs/lib/connection.js:163:19
>     at callback (/Users/Dmitry/WebstormProjects/Chat/node_modules/arangojs/lib/util/request.js:50:12)
>     at IncomingMessage.<anonymous> (/Users/Dmitry/WebstormProjects/Chat/node_modules/arangojs/lib/util/request.js:58:11)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>   errorNum: 1203,

I want to create the collection, wait the answer from API, then make some operations on collection, but i get the error. In fact the collection was created.

I don't know, where is an issue: in your driver or in ArangoDB... Or maybe I do something wrong.

**Comment by DeShadow** [comment]
Sorry, it's my mistake...

**Comment by Simran-B** [comment]
How did you solve it?

**Comment by DeShadow** [comment]
The problem was in my `wait.launch(function*() {})`.
The code was like:

```javascript
try {
	yield dbCol.truncate();
} catch (e) {
	yield dbCol.create();
	yield dbCol.import(docs);
}
```

I tried to truncate my collection. And if the collection was not exists, I wanted to create it. But my `wait.launch` worked wrong. After the line `yield dbCol.create();` my generator without waiting the resolving of promise goes to next line. That's why creating and importing execute in parallel, but not series. There is race condition in this point.
