### ISSUE TITLE
Bluebird promises log unhandled rejection errors

### ISSUE THREAD

**Issue by pluma** [arangodb/arangojs#31]
Bluebird is being "helpful" by logging rejected promises that don't have rejection handlers.

This leads to console noise when promises are silently discarded in favour of callbacks (e.g. when `db.collection` or `db.edgeCollection` with autoCreate=true determines that a collection doesn't exist).

This problem only occurs when bluebird is used as a promise polyfill via `global.Promise = require('bluebird')`.

**Comment by pluma** [comment]
@XescuGC Can you test with the current development version again? I've implemented a workaround that should make sure bluebird only complains if you didn't pass a callback and don't use a rejection handler.

**Comment by XescuGC** [comment]
Ok i've tested it including the `global.Promise` and removing the collections, and it worked :smile: , i'll migrate everithing to promises this night but i think the bug is solved.

**Comment by XescuGC** [comment]
Tested with full Promises and works :+1:

**Comment by pluma** [comment]
The fixes are in 3.6.0 on npm. Thanks.
