### ISSUE TITLE
Question: mongo $inc in arango?

### ISSUE THREAD

**Issue by ericfong** [arangodb/arangojs#311]
What is the best way to $inc a counter in arango?

Want to build a auto-inc counter. In mongo, we can do
```js
db.receipt.findAndModify({
    query: { name: "CompanyA" },
    update: { $inc: { receiptNum: 1 } },
    new: true,
})
```

Thanks

**Comment by Simran-B** [comment]
You can achieve this with an AQL query like the following:

```js
FOR doc IN receipt
  FILTER doc.name == "CompanyA"
  // LIMIT 1 // optionally limit to a single record
  UPDATE doc WITH { receiptNum: doc.receiptNum + 1 } IN receipt
  RETURN NEW // optionally return updated records
```

AQL queries can be run using https://github.com/arangodb/arangojs#databasequery

**Comment by ericfong** [comment]
Thanks for your quick reply.

Is it atomic?

2016年9月21日 上午1:22 於 "Simran" <notifications@github.com> 寫道：

**Comment by Simran-B** [comment]
AQL queries are fully ACID, except for multi-collection queries if the collections are sharded in a cluster.

**Comment by ericfong** [comment]
Wow, thanks

2016年9月21日 上午7:51 於 "Simran" <notifications@github.com> 寫道：
