### ISSUE TITLE
database.query() return symbol is undefined in IE

### ISSUE THREAD

**Issue by loredra** [arangodb/arangojs#313]
In IE, I encountered this error even though polyfill for promise has been imported like in this:
https://www.npmjs.com/package/es6-promise

Is there anything or config that I missed

**Comment by pluma** [comment]
This should be solved in the upcoming major release 6.0.0. Please feel free to reopen the issue if the problem persists after upgrading to the latest alpha (`npm install arangojs@6.0.0-alpha`) or the final 6.0 release.
