### ISSUE TITLE
Retrying request errors

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangojs#329]
One of my node apps uses arangojs all over the place. When ArangoDB is unreachable (arangod crashed, or got restarted by puppet, or is behind some networking trouble) my app dies and loses important state. I should catch arangojs errors and retry. But due to the complexity of my app, it actually makes more sense to catch and retry this type of error on the adapter level.

I've made the minimum required change for my use case by changing the Connection module in arangojs. It wraps the call to `this._request` using https://github.com/tim-kos/node-retry and, depending on the error, retries forever, just once, or not at all.

See https://github.com/pekeler/arangojs/blob/retry/src/connection.js#L82 from line 82 on.

The part I'm unsure about is https://github.com/pekeler/arangojs/blob/retry/src/connection.js#L123. Once in my testing I got an `ArangoError: canceled request` from arangojs while shutting down arangod, which is supposed to be handled by this line. I haven't been able to reproduce this error so I'm unsure that it actually has code `21`.

This might be of interest to others. And if you agree with the general approach, we could make this a bit more generic/configurable and turn it into a PR.

**Comment by pekeler** [comment]
I was able to reproduce the Canceled Request error. The `errorNum` is 21 (not the `code`).

**Comment by pluma** [comment]
This was addressed by the merged PRs.
