### ISSUE TITLE
transaction - using external JS functions

### ISSUE THREAD

**Issue by piotr-s-brainhub** [arangodb/arangojs#332]
I would like to know what is the best way to use external JS functions inside Arango transactions.

ex. I can do something like that:

``` js
function foo() {
  ...
}

function action () {
  foo();
  ...
}

arango.transaction({ write: 'users' }, `${action.toString().split(0, -1)}; ${foo.toString()}; }`;
```

However it looks a bit strange.

another approach:

```
function action () {
  function foo() {
    ...
  }

  foo();
  ...
}

arango.transaction({ write: 'users' }, action.toString());
```

However `foo` is a general function which I use not only in transactions so it would cause a duplication of code.

Moreover it's impossible to pass a stringified function as a parameter to the transaction because it doesn't allow to use `eval`.

**Comment by Simran-B** [comment]
Instead of `sum = eval("(function(a, b) { return a+b } )")` it is also possible to dynamically create functions from string like `sum = new Function("a", "b", "return a + b")` - maybe that helps?

Other options are to require JavaScript files inside the transaction or to register user-defined AQL functions and use an AQL query (UDFs must be side-effect free however).

**Comment by piotr-s-brainhub** [comment]
It works with `new Function`. However there is a problem when this function is defined in an external module and it uses other modules.

**Comment by pluma** [comment]
You can't invoke code outside the function you're passing to the transaction.

The code doesn't get executed in the browser (or node instance) where you define the function but inside ArangoDB. That means all the local variables and functions surrounding your function don't exist when the function gets executed.

If you have complex JavaScript logic that doesn't really fit inside a transaction function, consider using Foxx to move the entire code into ArangoDB: https://www.arangodb.com/why-arangodb/foxx/

**Comment by pluma** [comment]
@piotr-s-brainhub Does this answer your question?

**Comment by piotr-s-brainhub** [comment]
It's a good answer. I was looking for the best way. Therefore there shouldn't be a sophisticated logic in transactions
