### ISSUE TITLE
onDuplicate not working

### ISSUE THREAD

**Issue by devmetal** [arangodb/arangojs#336]
Hi, i use arabgodb 3.0 in my server, and i use the latest arangojs driver.

``` JavaScript
exports.batchInsert = (records) => inserts.import(records, {onDuplicate: "update"});
```

I created a collection, and i also create an index, name just simple id. So i want to bulk my inserts and updates.

If i try this:

``` JavaScript
{foo: 'bar', bar: 'foo', id: 2},
{foo: 'bar', bar: 'foo', id: 3},
{foo: 'bar', bar: 'foo', id: 4}
```

And if the databse hold a record with id 2, (id field is my unique index) i get a big error about unique constraint violation. I made an another call with internal _key field, and whatewer what is the onDuplicate value, the result is always error:

``` JavaScript
{ error: false,
  created: 3,
  errors: 1,
  empty: 0,
  updated: 0,
  ignored: 0 }
```

Not updated or ignored, just error.

Pls help, where i go wrong?

**Comment by pluma** [comment]
As far as I can tell this seems to be a problem with ArangoDB itself but I was unable to reproduce the problem.

Please feel free to reopen the issue if you think this is a bug in arangojs or can still reproduce the problem with the latest versions of arangojs and ArangoDB.
