### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by pluma** [arangodb/arangojs#34]

**Comment by thomasmodeneis** [comment]
Where test coverage increase is needed ?
Could you please elaborate this ?

**Comment by pluma** [comment]
Just run the tests and look for "`is missing tests`". There are a number of methods that don't currently have any test coverage, so adding tests for these would be a priority. These are currently stubbed out in the test directory to make it obvious which methods are known not to have tests yet.

**Comment by pluma** [comment]
Fixed via #519.
