### ISSUE TITLE
returnNew support

### ISSUE THREAD

**Issue by sylvainlap** [arangodb/arangojs#341]
In the doc, https://docs.arangodb.com/3.0/Manual/DataModeling/Documents/DocumentMethods.html#insert, we can see that document.insert can return the newly created document.

In arangojs, collection.insert does not exist, only collection.save. Is this method can support returnNew ?

Regards,
Sylvain

**Comment by pluma** [comment]
The methods `insert` and `save` are identical. I'm not sure why the save method is not in the official documentation as the examples use it almost exclusively.

We can add support for returnNew as the HTTP API also supports this option but for the time being you can simply `Object.assign` the document to the return value (which only contains the `_id`, `_key` and `_rev` attributes):

```js
const doc = {some: 'data'};
myCollection.save(doc).then((meta) => Object.assign(meta, doc)).then((savedDoc) => ...);
```
