### ISSUE TITLE
How i can SORT items???

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [arangodb/arangojs#344]
``` javascript
var res = collection.byExample({}, {sort: 'time'})
```

i want sort items by date, i storage date in Number type in field 'time'

**Comment by pluma** [comment]
The simple query `byExample` doesn't offer sorting.

I suggest you use an AQL query instead.

**Comment by Simran-B** [comment]
In case you wonder how to do that:

```
db.query(aql`
    FOR doc IN collection
    SORT doc.time
    RETURN doc
`)
```

**Comment by uMaxmaxmaximus** [comment]
Make that the method "by Example" supports sorting)?

**Comment by pluma** [comment]
As I said, the HTTP API doesn't offer this and we don't plan to extend the simple query APIs further.

You can either use an AQL query or sort the result on the client.
