### ISSUE TITLE
Persistent Indexes

### ISSUE THREAD

**Issue by iyobo** [arangodb/arangojs#345]
ArangoDB 3+ comes with persistent indexes through RocksDB.
Persistent indexes are stored on disk as opposed to in-memory, which makes ArangoDB a more attractive alternative in RAM-limited environments. Of-course nothing's faster than memory, but sometimes stability and recovery speed is just simply more important.

ArangoJS does not currently support persistent indexes in a non-arbitrary manner. It should.

**Comment by iyobo** [comment]
I created a Pull Request :)
https://github.com/arangodb/arangojs/pull/346

**Comment by Simran-B** [comment]
Thank you for your report and prompt PR to resolve it!

For legal reasons, we require contributors to sign a contributor license agreement (CLA). We are using a Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

Could you sign, scan and email the CLA to cla (at) arangodb.com?

Thanks!

**Comment by iyobo** [comment]
Signed

**Comment by pluma** [comment]
The PR was merged and published. I'm closing this.
