### ISSUE TITLE
Creating database after check if database exists

### ISSUE THREAD

**Issue by mirokk** [arangodb/arangojs#358]
I'm trying to do something very simple:

Check if database exist, if not create one..

If i just create one like in the following example it works:

	db.createDatabase(database_name).then(
		()=> console.log("Database created successfully: "+database_name),
		error=> console.error("Error creating database: "+error)
	);

If i first check if its available, the exact above code runs into the error function with the error "ArangoError: database not found"

Here the whole code:

	db.useDatabase(database_name);
	db.get().then(
		()=> console.log("Using database "+database_name),
		err=> {
			console.log(database_name+" doesn't exist, creating.. ");
			db.createDatabase(database_name).then(
				()=> console.log("Database created successfully: "+database_name),
				error=> console.error("Error creating database: "+error)
			);

		}
	);

it is also very unfortunate that things like db.useDatabase() and the initial connect to the db server doesn't have a .then() to check if I'm actually connected or not. Maybe there is a nicer way to do this which I'm not aware of?

**Comment by mirokk** [comment]
I found another - probably more elegant way to do it - by not using the error callback but by using listDatabases()

	db.listDatabases()
	.then((names) => {
		if (names.indexOf(database_name) > -1){
			db.useDatabase(database_name);
			db.get().then(
				()=> console.log("Using database "+database_name),
				error=> console.error("Error connecting to database: "+error)
			);
		} else {
			db.createDatabase(database_name).then(
				()=> console.log("Database created successfully: "+database_name),
				error=> console.error("Error creating database: "+error)
			);
		}
	});

**Comment by pluma** [comment]
`useDatabase` does nothing to ArangoDB, it just changes the client's connection. It should be reversible (just pass the original database name in, e.g. `_system`).

But you're correct that you need to create the database BEFORE using it. `useDatabase` changes which database's API the client will talk to so trying to switch to the database and then creating it means you'll talk to the API of a database that isn't there yet and tell it to create itself.

**Comment by SiamakShams** [comment]
### I know this thread is years old but I'm a new comer.

Mirokk that solution works well but partly, because you still need to use the database after the creation - so I slightly altered your solution and it works for me.

db.listDatabases().then((names) => {
    if (names.indexOf(database_name) > -1){
        db.useDatabase(database_name);
    } else {
        db.createDatabase(database_name).then(
            ()=> console.log("Database created successfully: "+ database_name),
            error=> console.error("Error creating database: " + error)
        );
    }
}).then (() => {
  db.get().then(
    ()=> console.log("Using database " + database_name),
    error=> console.error("Error connecting to database: " + error)
  );
});
