### ISSUE TITLE
hello world js failing

### ISSUE THREAD

**Issue by donpdonp** [arangodb/arangojs#364]
Hello, first time arango user (experienced admin/dev). Arango 3.1.1 starts fine. Trying to get a hello world js script going but a confusing error results. Can someone explain what the problem here is? There are no databases created, just trying to get an empty list or some sort of positive response from arango.

arango.js
```javascript
'use strict'
var arango = require('arango')

let db = arango.Connection()

console.log('db list')
db.database.list().done(function(res){
  console.log("collections: ");
})
```
```$ node arango.js 
db list

/home/donp/code/cointhink/superpoll/node_modules/arango/node_modules/micropromise/node_modules/microtask/index.js:60
                    throw e;
                    ^
```

**Comment by thomaskarlrichter** [comment]
Try 
var arango = require("arangojs");

**Comment by pluma** [comment]
Can you clarify where you found a tutorial that tells you to use `Connection`? I'm guessing it's extremely out of date. The API has changed between the major versions of arangojs in backwards-incompatible ways (hence the major version changing) and there are still examples out there for older versions that don't explicitly pin the version number of arangojs.

Also it looks like you're following a tutorial for `arango` not `arangojs`. The former was developed by a member of the community and doesn't seem to be maintained any longer: https://www.npmjs.com/package/arango

**Comment by donpdonp** [comment]
I was following https://www.npmjs.com/package/arango#quick-start 

Thanks for the help. I'm using arangojs now. Perhaps an arango dev could contact the maintainer of arango to add a big README warning about how that client has been abandoned.

**Comment by Simran-B** [comment]
It actually says:

![image](https://cloud.githubusercontent.com/assets/7819991/20796061/b30329e2-b7d4-11e6-9cc4-3f1202a9878c.png)

which in turn states:

![image](https://cloud.githubusercontent.com/assets/7819991/20796065/bf9152e2-b7d4-11e6-9a0c-26e5635cdec4.png)

**Comment by pluma** [comment]
Yeah, the message could be clearer and it would be nice if it used the deprecation feature of npm.

But @andelo doesn't seem to be active on GitHub anymore and I'm not sure whether he's still doing anything with ArangoDB.
