### ISSUE TITLE
Problem in insert a document with a self-define key

### ISSUE THREAD

**Issue by Rucchao** [arangodb/arangojs#370]
I use the code of documentCollection.save, 

var db = require('arangojs')();
var collection = db.collection('my-docs');
var doc = {some: 'data'};
collection.save(doc)
.then(doc1 => {
    doc1._key; // the document's key
    doc1._id === ('my-docs/' + doc1._key);
    collection.document(doc)
    .then(doc2 => {
        doc2._id === doc1._id;
        doc2._rev === doc1._rev;
        doc2.some === 'data';
    });
});

and get a error, as follow:

Error: Document handle must be a document or string
    at DocumentCollection._documentHandlel
    at DocumentCollection._documentPath 
    at DocumentCollection.document 
    at process._tickCallback (internal/process/next_tick.js:103:7)

Could anybody help me with this ?  I am fairly new to JS and arangodb, Thanks !

**Comment by jsteemann** [comment]
Instead of `collection.document(doc)` it should read `collection.document(doc1._key)`.
This does a primary key lookup with the inserted document's key. The code above calls `document(doc)`, and `document()` expects either a key string as its input parameter or an object with an `_id` value. But `doc` in the above code is an object which does not contain a `_key` attribute, so the call fails.

**Comment by pluma** [comment]
To address this you could change the code to this:

```js
collection.save(doc)
.then((meta1) => {
  Object.assign(doc, meta1); // copy `_id` and friends to the doc object
  collection.document(doc)
  // alternatively just use collection.document(meta1) directly
  .then((meta2) => {
    meta2._id === meta1._id;
    meta2._rev !== meta1._rev;
  });
});
```

Also note that `meta1` and `meta2` aren't the full documents but just an object with the `_id`, `_rev` and `_key` attributes. Arangojs does not modify the object you pass to `collection.save`.

**Comment by pluma** [comment]
I see why you made this mistake. It seems the documentation is lying -- the examples imply arangojs merges the metadata into the input document. We should fix that.

**Comment by Rucchao** [comment]
Thanks for your quick response! I actually found a easier way to do this job, just assign the attribute "._key" of the json object, and then save it , finally it meet my need. 

doc._key='000';
collection.save(doc);

**Comment by pluma** [comment]
Yes, if you want to define the key yourself, you can do that. If you want to use an autogenerated key, however, you still need to use the response data.

**Comment by Rucchao** [comment]
Here's another issue need help, sorry.

I'd like to build a "knows" graph in my customer collection, as follows:

var d1=collection.document('640f4f97-1d9b-4287-8b10-614688f9b1d0');
d1.then(function(result) {
    console.log(result._id) 
})

var d2=collection.document('c606d25b-e37e-42c5-b925-33d239214b27');
d2.then(function(result) {
    console.log(result._id) //will log results.
})

var collection1 = db.edgeCollection('knows');
collection1.save({
    _from: d1._id,
    _to: d2._id
});

The two document is exist, id format is UUID, I can do it use web interface, but I get a error when I use node.js api, any help will be appreciated:

ArangoError: invalid edge attribute
    at new ArangoError
    at callback
    at IncomingMessage
    at emitNone (events.js:91:20)

**Comment by pluma** [comment]
Hi @Rucchao, you've opened another issue for this question, so I've answered it there.

I'll keep this issue open as a documentation issue until the code examples have been corrected.
