### ISSUE TITLE
Problem in insert a edge between two documents

### ISSUE THREAD

**Issue by Rucchao** [arangodb/arangojs#371]
I'd like to build a "knows" graph for my customer collection, as follows:

var d1=collection.document('640f4f97-1d9b-4287-8b10-614688f9b1d0');
d1.then(function(result) {
console.log(result._id)
})

var d2=collection.document('c606d25b-e37e-42c5-b925-33d239214b27');
d2.then(function(result) {
console.log(result._id) //will log results.
})

var collection1 = db.edgeCollection('knows');
collection1.save({
_from: d1._id,
_to: d2._id
});

The two documents are exist, id format is UUID, I can do it using the web interface, but I get a error when I use node.js api, any help will be appreciated:

ArangoError: invalid edge attribute
at new ArangoError
at callback
at IncomingMessage
at emitNone (events.js:91:20)

**Comment by pluma** [comment]
All operations that return promises are asynchronous. That means the callback will only be invoked at a later time (in fact, promises guarantee that the callback will not be executed immediately even when the result is already known in advance). The result of one async operation will not be known by the time the second operation is invoked unless you explicitly await the first result (e.g. using nested `then` callbacks or the `async/await` syntax that will become available in upcoming versions of Node and browsers).

Here's a nice explanation by Google's Jake Archibald on how promises can be used: https://developers.google.com/web/fundamentals/getting-started/primers/promises

In your case `d1` and `d2` do not have a result by the time you try to create the edge. Also, they are promises, not the result objects that will be passed to the `then` callbacks.

In lieu of `async/await` (which should land in Node at some point next year) you can simply use `Promise.all` to make sure both vertices are fetched before you create the edge connecting them:

```js
Promise.all([
  collection.document('key1'),
  collection.document('key2')
])
.then(function (results) {
  var d1 = results[0];
  var d2 = results[1];
  var collection1 = db.edgeCollection('knows');
  return collection1.save({
    _from: d1._id,
    _to: d2._id
  });
})
.then(function (meta) {
  console.log(meta); // edge has been created!
});
```

Note that we're avoiding deep nesting of callbacks by returning the next promise from the first `then`. The second `then` will automatically pass the result of `collection1.save` to its callback although the "outer" code doesn't know anything about it.

It's also good practice to catch any asynchronous errors using the `catch` callback like so:

```js
// ... same code as above ...
.then(function (meta) {
  console.log(meta); // edge has been created!
})
.catch(function (err) {
  // This could be an error from any of the three promises above.
  console.error(err.stack);
});
```

In this case both the first and the second `then` callback will be skipped if either of the vertices can't be fetched and the second callback will be skipped if the edge creation failed.

**Comment by Rucchao** [comment]
Thanks for your time and help ! It works to me now, async programming in Node.js is pretty cool ! And also, ArangoDB is a very nice multi-model database !

**Comment by pluma** [comment]
You're welcome. Asynchronous programming can be hard to wrap your mind around so don't worry if you run into problems again. Glad to hear you're enjoying ArangoDB, too.
