### ISSUE TITLE
Improvements for the typescript definition files

### ISSUE THREAD

**Issue by janwo** [arangodb/arangojs#374]
Hey guys, 

I am using `arangojs` in my project. Since Typescript 2.1.x I need to assume the type of the returned object of methods like `Cursor.next()`, `Cursor.all()`, ... now. Most likely Typescript improved the error detection in some way.

To solve these errors, I am currently doing the following:
````ts
export function myfunction(queryString: string) : Promise<List[]> {
    ...
    return arango.query(aqlQuery, aqlParams).then((cursor: Cursor) => cursor.all()) as any as Promise<List[]>;
}
````
or 
````ts
export function myfunction(queryString: string) : Promise<List> {
    ...
    return new Promise<List>(resolve => {
        return arango.query(aqlQuery, aqlParams).then((cursor: Cursor) => cursor.next() as any as User).then(user => resolve(user));
    });
}
````
This looks a little bit weird and these assumptions seem to be a bad practice with good reason.
I suggest to replace the types of `Object` with `any` or to make the Cursor somehow generic. What do you guys think? Or is there a nicer approach?

**Comment by pluma** [comment]
Sounds sensible. `cursor.next` can literally be anything and `cursor.all` will always return an array of those.

The TypeScript definition file was contributed by a community member. Could you make the changes yourself in a PR? I'm not confident enough in my TypeScript knowledge (or rather the complete lack thereof) to make them myself.

**Comment by janwo** [comment]
@pluma  I created a PR ✌️

**Comment by pluma** [comment]
Merged :+1:

Thanks for the contribution!
