### ISSUE TITLE
jobs

### ISSUE THREAD

**Issue by AmmarMohamed** [arangodb/arangojs#376]
I read all the functions about jobs , but if i wont to run the job function daily What can i made ??
for example : i need to insert documents in specific collection every day ??

**Comment by pluma** [comment]
I'm not sure I understand your question.

If you're wondering how to schedule daily tasks that's outside the scope of this driver.

For a built-in solution you could look at Foxx queues: https://docs.arangodb.com/3/Manual/Foxx/Scripts.html

Alternatively you can either define your task as a Foxx script (see the same documentation page) or as a standalone script outside ArangoDB. You could then use a tool like `cron` to schedule the script to be invoked repeatedly.

**Comment by Simran-B** [comment]
For daily or even less frequent time intervals (weekly, monthly, ...), you should really use a task scheduler outside of this driver and also outside of ArangoDB (e.g. a cron job like pluma suggested). Think of daylight saving time, leap years and leap seconds: if you wanted to run a task daily at 3am, it is easily to setup with a task scheduler, but

**Comment by AmmarMohamed** [comment]
Ok thanks  @Simran-B  and @pluma  i will use foxx to solve this problem
