### ISSUE TITLE
connecting with unix file socket to arangodb3

### ISSUE THREAD

**Issue by kfirufk** [arangodb/arangojs#405]
Hi.

When I try to connect to arangodb3 using unix file socket with the following code:

```
let db = arangojs({
  url: `unix:///tmp/mysocket`,
    databaseName: false // don't automatically append database path to URL
    });

```

i receive:

> Error: connect ECONNREFUSED ::1:80
>     at Object.exports._errnoException (util.js:1023:11)
>     at exports._exceptionWithHostPort (util.js:1046:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

so it tries to connect to localhost with port 80 instead of the unix file socket location. 

does this client doesn't support unix file socket or am I missing something ?

**Comment by pluma** [comment]
You're right unix file sockets aren't currently supported but it seems Node supports this in `http` via the `socketPath` part of the URL object.

It should be possible to adjust the logic to support the `unix` protocol in URLs but right now this is a feature request.

**Comment by kfirufk** [comment]
When practicing the technique of specifying the unix-domain-socket path in the http.request:

1. Does this mean that the client re-initiates a new ad-hock connection to that unix-domain-socket - for the purpose of the request processing only - and drops that connection once it has been completed (and then does this whole connect/disconnect procedure again for each http.request? - OR - does it maintain the connection to the unix-domain-socket in the background and re-utilizes that connection over-and-over-again whenever it's required?

2. If the re-utilization technique is practiced, WHEN does the initial connection to unix-domain-socket establishment happen - once at ArangoDB-client object creation, OR at first issued http.request (which is then kept-on alive for other requests)

**Comment by pluma** [comment]
Node seems to have the same behavior for unix sockets as for TCP sockets, so it seems keep-alive works just the same.

**Comment by pluma** [comment]
Currently some of the Foxx tests are failing because of how the test fixtures reflect their externally visible URL. Hopefully that should be relatively straightforward to resolve.
