### ISSUE TITLE
db.collection error handling

### ISSUE THREAD

**Issue by legikaloz** [arangodb/arangojs#41]
I'm using ArangoDB 2.6-alpha3, over HTTPS & HTTP authentication turned on with arangojs 3.8.1 driver.
When I invoke the above function with wrong or no pw, the callback called with error = null. When i use promises the success handler will be invoked. However the response has statusCode = 401
```
db.collection('collectionname',function(err,resp){
console.log('error: ',e);
console.log('response: ',r)
});
```
I've not checked more API calls for this bug.

**Comment by pluma** [comment]
See #24. Currently the error handling only handles API errors (i.e. ArangoErrors). This may be what you want for custom endpoints but not for the built-ins, so this needs to fixed.

I'm closing this issue in favour of the more general #24 as auth and db.collection are just one specific example of this behaviour.
