### ISSUE TITLE
query parameter not working

### ISSUE THREAD

**Issue by chrislarsenqlik** [arangodb/arangojs#414]
Hi, 
I have a working aql query, as soon as i substitute a hardcoded value in a parameter to a variable, it's not working. It's working in another part of my code no problem!

Here's the query I'm running in arangosh that works just fine:

`FOR answer IN polls
FILTER answer.type == 'answer_option'
FILTER answer.question_id == 12345
COLLECT question_id = answer.question_id,
response = answer.response, response_position=answer.response_position
WITH COUNT INTO number
RETURN { 
	response: response, 
	question_id: question_id,
	response_position: response_position,
	votes: number 
}`

Here is an example elsewhere in my code that works fine with a curly parameter specified:

`FOR poll IN polls
FILTER poll.type == 'response'
FILTER poll.ip == ${remoteAddress}
COLLECT question_id = poll.question_id 
WITH COUNT INTO number
RETURN { 
	question_id: question_id, 
	votes: number 
}`

As soon as I change the "12345" to a variable referenced just the same way, that's when it fails. When consoling out the value it should be using, I'm getting the correct value, but i get null results when running it like this:

`FOR answer IN polls
FILTER answer.type == 'answer_option'
FILTER answer.question_id == ${my_next_question}
COLLECT question_id = answer.question_id,
response = answer.response, response_position=answer.response_position
WITH COUNT INTO number
RETURN { 
	response: response, 
	question_id: question_id,
	response_position: response_position,
	votes: number 
}`

**Comment by chrislarsenqlik** [comment]
Found the issue, it was seeing a variable as a number (which it looks like it actually is in Arangodb!) when it needed to be converted explicitly to a string for the parameter option.

**Comment by pluma** [comment]
Can you clarify what one of the documents in question actually looks like as JSON and how you're passing the query specifically?

There's a difference between

```js
`this ${query} string`
```

and

```js
aql`this ${query} string`
```

and if a number literal behaves different from a number parameter that sounds like a bug in AQL not the driver (in which case I'm sure the ArangoDB query team would love to hear about it).
