### ISSUE TITLE
COLLECT AGGREGATE for AQB

### ISSUE THREAD

**Issue by AlexeiAndreev** [arangodb/arangojs#441]
I don't see a way to use AQB to create a "COLLECT AGGREGATE" statement.

**Comment by pluma** [comment]
This is the repository for the arangojs driver. If you want to file an issue with AQB please use https://github.com/arangodb/aqbjs/issues instead.

However AQB is currently known to be lagging behind parity with ArangoDB in what AQL expressions it supports and not actively maintained.
