### ISSUE TITLE
Support real proxy connections

### ISSUE THREAD

**Issue by nervetattoo** [arangodb/arangojs#445]
I've been trying to figure out how to connect to a database with arangojs using a proxy. 
I guessed that passing a configuration like this should be sufficient, but when I've tried it using Quotaguard proxies on heroku I've failed:

```js
const db = arangojs({
  url: proxyUrl,
  databaseName: mydatabase,
  headers: {
    Host: databaseHost,
    Authorization: arangodbBasicAuth,
  }
})
```

I've attempted to break down `url` properties into `hostname` + `port` + `headers.Proxy-Authorization` as well. In all attempts the proxy refuses because it doesn't receive them as proxy requests, but real requests.

**Comment by pluma** [comment]
The solution in Node.js land seems to be to simply use a library like https://github.com/TooTallNate/node-proxy-agent. It's possible to pass your own `Agent` to arangojs, so that library should work as described.
