### ISSUE TITLE
Throw error in transation

### ISSUE THREAD

**Issue by xygahs0801** [arangodb/arangojs#449]
**please note this code:**
``` javascript
const action = String(function() {
    const db = require('org/arangodb').db;
    throw "error";
});
await db.transaction({ }, action, { });
```
**console will show** 
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ArangoError: internal server error
(node:1) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 **then the promise will pendding ! 
it's not reasonable.
it should rollback and reject with a error.**

**Comment by pluma** [comment]
This actually seems to result in an error in ArangoDB, not arangojs:
```
{ error: true, errorMessage: 'error', code: 500, errorNum: 1650 }
```
Throwing an actual Error object results in this instead:
```
{ error: true, errorMessage: 'Error: error', code: 500, errorNum: 4 }
```

If you think either of these two responses is unreasonable, you may want to open an issue in the ArangoDB repository.

The async/promise logic will change in the upcoming 6.0.0 release of arangojs by removing support for node-style callbacks, so it will no longer be possible for promises to get stuck on pending.
