### ISSUE TITLE
Did i use arangojs correctly?

### ISSUE THREAD

**Issue by lzszone** [arangodb/arangojs#457]
i'm using arangojs like this:
```
const arango = require('arangojs');
const db = arangojs({
  url: `http://${userName}:${passwd}@${host}:${port}`,
  databaseName: database,
  arangoVersion: 20800
});
const aql = arango.aql;
```
in several files in my projects, i mean **if the aql query is required in that module/file, a db instance of db is created.**,
and i found that the app could receive requests but do not response anything sometimes,
then i search for it , view the issues about pool  in arango
is there other posibility would cause this problem?

**Comment by pluma** [comment]
Arangojs uses connection pooling to limit how many connections are opened at a time. If you want to use arangojs in multiple modules in your server code, you probably want them to share an arangojs instance and its connection pool, so I would recommend extracting the `db` object into a separate module.

**Comment by lzszone** [comment]
got it , thanks
