### ISSUE TITLE
Bulk Import of List doesn't work

### ISSUE THREAD

**Issue by TimMensch** [arangodb/arangojs#461]
I was having issues with bulk import, and I finally gave up on my code and used the snippet from the docs:

```
    collection.import(
        [// array stream with header
            [ 'username', 'password' ], // keys
            [ 'admin', 'hunter2' ], // row 1
            [ 'jcd', 'bionicman' ], // row 2
            [ 'jreyes', 'amigo' ],
            [ 'ghermann', 'zeitgeist' ]
        ]
    )
```

I get:

```
ArangoError: expecting a valid JSON array in the request. got: Expecting EOF
```

I can do the equivalent query using `curl` without issue, and I've looked at the generated query and I don't see what's different compared to the raw query that `curl` generates, so I'm going to throw up my hands for now and just pass in an array of objects (which does work).

**Comment by dimahav** [comment]
Same problem for me.

**Comment by Kustopher** [comment]
same here

this syntax works fine:
[
  {key1: value1, key2: value2}, // document 1
  {key1: value1, key2: value2}, // document 2
  ...
]

this syntax doesn't work at all:
[
  ['key1', 'key2'], // key names
  [value1, value2], // document 1
  [value1, value2], // document 2
  ...
]
i get the error response: 
(node:11676) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ArangoError: expecting a valid JSON array in the request. got: Expecting EOF

**Comment by pluma** [comment]
I'm currently waiting for clarification of the correct behaviour of the ArangoDB import API. See #496 for details.
