### ISSUE TITLE
Export collection.types const

### ISSUE THREAD

**Issue by casdevs** [arangodb/arangojs#466]
Could the `types` const defined in collection.js be exported, so that it can be used by external code?

I would like to get all edgeCollections (by using database.listCollections) and have to filter them by type, and I don't want to redefine it or use magic numbers...

Thanks.

**Comment by pluma** [comment]
It's now an exported TypeScript enum which compiles to a plain JS object.

**Comment by casdevs** [comment]
I'm sorry, but I can't find out how to access the `types` object from outside the arangojs module...
Checking the module's source code, it doesn't seem that it gets exported. The only public exports are `database` and `aql`, but the `types` object is just exported on the `Collection` type which I can`t access from outside of the module?

Thanks for clarification!

**Comment by pluma** [comment]
You should be able to import from `arangojs/cjs/collection` but I guess we can make that part of the "official" exports as well.

**Comment by casdevs** [comment]
thanks for the hint!
A direct es6 import like `import {Types as CollectionTypes} from 'arangojs/lib/async/collection';` does work; however, it would be great indeed if one could access that in a more 'official' way that doesn't require the caller to decide whether to use the `async` or `cjs` code base.

**Comment by pluma** [comment]
Fixed via 6.4.0, the enum is now called `CollectionType` and part of the public exports.
