### ISSUE TITLE
Database doesn't rollback on failure using transactions.

### ISSUE THREAD

**Issue by nicolaselkhoury** [arangodb/arangojs#467]
I am trying to use the transactions function using arangoJS library. The function is just a dummy function that inserts two records, and then tries to get a document that doesn't exist. Getting the nonexistent document generates an error, and the transaction must rollback. Indeed, the error gets generated after trying to get the document that doesn't exist. However, the database does not rollback, and the two inserted documents remain inserted in the database. Does anyone know how to solve it?

UPDATE: I tried this transaction on a single instance ArangoDB and it worked. However, it did not work on a cluster. Is there no support for transactions on ArangoDB clusters?

**Comment by pluma** [comment]
Hi @nicolaselkhoury, this sounds like a problem with ArangoDB rather than the JS driver.

Can you please open an [issue on the ArangoDB repo itself](/arangodb/arangodb/issues)?
