### ISSUE TITLE
Improvement: documentCollection.update should return whole document

### ISSUE THREAD

**Issue by Kurtas** [arangodb/arangojs#468]
Hi, 

I suggesting that `update` method should return whole document instead of only metadata. 
There can be `returnNew` option for that, like in `save` method.

Thanks

**Comment by pluma** [comment]
The option is already supported by ArangoDB, it's just missing in the documentation.

**Comment by dsonet** [comment]
@pluma If set to `false`, return additionally the complete...., it should be 'If set to `true`'.
