### ISSUE TITLE
"unknown path" responses from server on every API call

### ISSUE THREAD

**Issue by jrsnyder** [arangodb/arangojs#47]
I'm just starting with arangodb and arangojs, so maybe I'm making a basic mistake, but arangojs is returning "unknown path" for every API call for me.  Manual http requests from iojs to the server work fine.

I made an attempt at debugging, and found that the use of [path.join in request.js](https://github.com/arangodb/arangojs/blob/v3.8.1/lib/util/request.js#L47) was changing the slashes in the path to backslashes.  Changing them back to slashes fixed the problem.

I'm running arangodb 2.6 with a fresh database and stock settings.  I'm running arangojs 3.8.1 on iojs 1.8.1, and using the default Database constructor.

**Comment by jrsnyder** [comment]
Ok, now I found [Ziink's pull request](https://github.com/arangodb/arangojs/pull/40), which solves the problem.

**Comment by pluma** [comment]
Closed via #40.
