### ISSUE TITLE
Access-Control-Allow-Credentials CORS issue

### ISSUE THREAD

**Issue by alexalexpod** [arangodb/arangojs#470]
Hello.

I am trying to get the data from my Foxx service by the following code:
**const route = db.route('hello-me', { 'Access-Control-Allow-Credentials': 'true' });
const response = await route.get('hello/LAX');**

and I get the following error in Google Chrome:
**Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is 'false' which must be 'true' when the request's credentials mode is 'include'. Origin 'http://localhost:3000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.**.

The problem is CORS configuration, but I thought that I treat it with 'Access-Control-Allow-Credentials': 'true' (as shown above).
How can I solve the CORS problem?

Thanks, Alex.

**Comment by pluma** [comment]
This sounds like a problem with ArangoDB, not the driver. If you need help with setting up ArangoDB for CORS, please check the [relevant documentation](https://docs.arangodb.com/3.2/HTTP/General/index.html#cross-origin-resource-sharing-cors-requests) or drop by the [Community Slack](https://slack.arangodb.com/).

I'm closing this as there doesn't seem to be anything arangojs can do to address this. Please feel free to reopen the issue if you think this is a mistake.
