### ISSUE TITLE
Multiple ArangoDB coordinators

### ISSUE THREAD

**Issue by nickcodefresh** [arangodb/arangojs#471]
We are using multiple ArangoDB coordinators, but the library only allows us to use use a single one as a connection URL. Ideally we should be able to set multiple URLs, which means if current coordinator fails over to another and the application continues to work.

**Comment by pluma** [comment]
This is something the driver team at ArangoDB is currently discussing. We support failover in the Java driver and plan to bring this feature to other drivers, however this will likely require changes to the driver API and a lot of the underlying implementation.

**Comment by pluma** [comment]
The upcoming major release, 6.0.0, will support specifying multiple URLs as well as updating the URL list using the `acquireHostList` method. It also implements failover and round robin load balancing.
