### ISSUE TITLE
TypeScript [ts] Module '"arangojs"' has no exported member 'aql' 

### ISSUE THREAD

**Issue by miff** [arangodb/arangojs#472]
Just follow initial tutorial:

```
// Modern JavaScript
import {Database, aql} from 'arangojs'
...
```
but throw error: module '"arangojs"' has no exported member 'aql'

Thanks

**Comment by nitrog7** [comment]
For now I'm using:
`import aql from 'arangojs/lib/aql-query';`

**Comment by pluma** [comment]
FYI arangojs has been rewritten in TypeScript and now provides official bindings.
