### ISSUE TITLE
Query management API

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangojs#474]
Is there a way to kill a running query?

**Comment by gurisko** [comment]
The answer is *NO*.

Therefore I propose to introduce a new method `asyncQuery`. It would use `POST /_api/cursor` with `x-arango-async: store` header which returns job id. Then we could easily cancel a query by `PUT _api/job/{job-id}/cancel`.

**Comment by zhenruyan** [comment]
https://github.com/arangodb/arangojs/pull/484

PR has been submitted

**Comment by gurisko** [comment]
@zhenruyan Thanks for the PR! It is a great step forward.

However the proposal goes a bit further by introducing an async query that would return **job** ID. This would be very helpful if I want to cancel queries triggered by one HTTP request into my API backend.

**Comment by zhenruyan** [comment]
job id in response header X-Arango-Async-Id
For the time being, I haven't found a way to take it out and merge it into the body.
