### ISSUE TITLE
Cannot access arango db: Response to preflight error

### ISSUE THREAD

**Issue by aguskov1987** [arangodb/arangojs#475]
Hi there,
I am trying to connect to arango db from an Angular application but keep getting the following error:
Failed to load http://localhost:8529/_db/_system/_api/database: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is 'false' which must be 'true' when the request's credentials mode is 'include'. Origin 'http://localhost:4200' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

This is the code:
export class ArangoService {
  public connector : any;

  private host : string = "http://localhost:8529";
  private user : string = "root";
  private password : string = "pass";

  constructor() {
    this.connector = new arango.Database(this.host);
    this.connector.useBasicAuth(this.user, this.password);
    this.connector.listDatabases().then((r) => {
      console.log(r);             <--------error happens here
    });
  }
}

I tried to restart my arangod service with the following parameters (according to the manual found @ https://docs.arangodb.com/devel/HTTP/General/#cross-origin-resource-sharing-cors-requests):
![image](https://user-images.githubusercontent.com/7570134/31238315-980922c8-a9c7-11e7-8a87-4ca03690bad6.png)

but the error keeps occurring. Any advice where to go next? 

Thanks

**Comment by aguskov1987** [comment]
turns out starting ArangoDB as a service does not work. It still does not allow CORS. I had to turn the service off, then start the server with the following command:
`arangod --http.trusted-origin "*"`

only then I could access the server. Keep in mind, that if you close the prompt, the server will die. Anybody knows a way to always start ArangoDB in cross-origin mode?

**Comment by aronse** [comment]
@aguskov1987 You can add
```
[http]
trusted-origin=all
```
in your ***arangod.conf*** file and then restart the service

**Comment by pluma** [comment]
This sounds like a problem with ArangoDB, not the driver. If you need help with setting up ArangoDB for CORS, please check the [relevant documentation](https://docs.arangodb.com/3.2/HTTP/General/index.html#cross-origin-resource-sharing-cors-requests) or drop by the [Community Slack](https://slack.arangodb.com/).

I'm closing this as there doesn't seem to be anything arangojs can do to address this. Please feel free to reopen the issue if you think this is a mistake.

**Comment by positiveneutron** [comment]
Thanks @aronse your solution works for my case.
