### ISSUE TITLE
Wrong type in EdgeCollection save method

### ISSUE THREAD

**Issue by nitrog7** [arangodb/arangojs#476]
https://github.com/arangodb/arangojs/blob/776a148ce574076b57e2499b8b344ca892a3f0be/arangojs.d.ts#L381

The line should read:
save(data: any, fromId?: string, toId?: string): Promise<any>;

In TypeScript, it is requiring the data parameter to be a string instead of also allowing an object or properties.

**Comment by gurisko** [comment]
The maintainers are considering to drop this support altogether #391
