### ISSUE TITLE
Prevent duplicate edges - one _from-_to combination only

### ISSUE THREAD

**Issue by Kustopher** [arangodb/arangojs#477]
Hi, I'm new to ArangoDB and while testing some codes I accidently created multiple edges, and I was wondering how to prevent this.

Example:
_key: 1, _from: "users/user1", _to: "movie/movie1", rate: "3"
_key: 2, _from: "users/user1", _to: "movie/movie1", rate: "3"
_key: 3, _from: "users/user1", _to: "movie/movie1", rate: "3"

Is there a build in way to prevent duplicate entries, like setting to disallow multiple entries of the same _from-_to combination? How do you handle this working with ArangoDB?

**Comment by mpv1989** [comment]
You can create a unique hash index on the fields `_from` & `_to`. See [here](https://docs.arangodb.com/3.2/Manual/Indexing/Hash.html#unique-hash-indexes) for more information about unique hash index. This solution only works in a single server setup because a cluster does not allow unique indexes.
