### ISSUE TITLE
https performance

### ISSUE THREAD

**Issue by legikaloz** [arangodb/arangojs#48]
The driver performance over HTTPS is very poor.
The same query roundtrips are 4-5 times(!) faster with HTTP. In my simple tests the average query RTT was 41.6ms with HTTP, and 196.5ms with HTTPS on a remote server. 
Is there any extra option to pass to the driver? 
My environment:
arangoDB 2.6.0 (stable) and 2.5.2
iojs 2.3.1
arangojs 3.8.1

The performance of the web GUI is as fast with HTTPS than with HTTP.

**Comment by dothebart** [comment]
SSL- handshakes involve more TCP-roundtrips than plain TCP. 
Did you use a connection pool in both tests? If you run tcpdump / wireshark you shold see a set of connections with lots of back and forth talking compared to many connections with little communication.

If your two hosts have slower pings, these additional roundtrips sum up.

did you try to compare it to a simple webserver with http and https?

**Comment by legikaloz** [comment]
I'm using the driver with default settings. Which options should I pass in the agentOptions to use pools, or keepalive?

**Comment by pluma** [comment]
HTTPS should "just work". You only need to mess with the `agentOptions` or `agent` if you want to change the default behaviour. If no agent is provided, it automatically uses http.Agent or https.Agent depending on the URL passed to the constructor.

**Comment by pluma** [comment]
This may be an issue with node itself. The default settings of Node.js are known to cause bad performance when using outbound HTTPS:

https://www.paypal-engineering.com/2014/04/01/outbound-ssl-performance-in-node-js/

**Comment by pluma** [comment]
Can you confirm that it's arangojs rather than the https module itself that is slow?

Try using `https.request` directly vs arangojs with HTTPS and then `http.request` vs arangojs with HTTP. If the relative differences are vastly different, there's probably something wrong.

**Comment by legikaloz** [comment]
I tried several test cases with many different settings (keepalive, connection pools etc). It seems that node https module itself is the problem :( The results of plain HTTPS paired with arangojs are almost equal.
I'm planing to use plain HTTP over VPN as a temporary workaround.
Is there any concrete plan to support websocket/HTTP 2.0 in an upcoming arangoDB version in the near future?

**Comment by pluma** [comment]
I'm not aware of any short-term plans for supporting HTTP 2.0, sorry.

If the performance tweaks for HTTPS aren't sufficient, you could also use HTTP over SSH (establish an SSH tunnel to the database server and just make all HTTP connections over that).
