### ISSUE TITLE
Add official TS typings

### ISSUE THREAD

**Issue by pluma** [arangodb/arangojs#480]
See #391, #447, #460, #472, #476 and 5b25237.

Letting the community maintain the typings is a bad idea because outdated or wrong typings are worse than useless. We should either transition the entire codebase to typescript or add our own typings.

**Comment by gurisko** [comment]
Didn't arango team maintain them like, since forever? The result can be seen in the mentioned tickets.

**Comment by pluma** [comment]
Nope, those were all community contributions, which is why they were usually out of date or incorrect. We just shipped them as part of the official client. What I'm proposing is writing them ourselves and keeping them in sync.

**Comment by gurisko** [comment]
Oh, I get it now. Having typings as part of a npm package makes it look like the maintainer of the package also maintains included typings. Arango team support would be much appreciated!

Have you considered pushing typings into DefinitelyTyped under @types/arangojs name? Community is much more used to this setup and it won't leave us with many pull requests hanging in the air.

**Comment by pluma** [comment]
The idea is to make sure the typings are always in sync (because if we change the API we change the typings). This would eliminate the need for typings-related PRs from the community.

We're starting to dogfood arangojs more and we're currently experimenting with TypeScript internally so it's not entirely unlikely that we'll convert arangojs to TypeScript in the future if it doesn't affect the very tight performance optimisations. Either way we'll be able to dogfood the typings (and thus be able to make sure they remain accurate and up to date) because some team members have grown fond of VS Code which uses typings to provide code intelligence in JavaScript.

Previously we had no use of TypeScript internally so the community-supplied typings were frequently out of date or incorrect and we had no process for determining that unless users reported these issues and provided fixes (which in turn we also couldn't verify).

**Comment by pluma** [comment]
Fixed via #487. The new typings will be included in the next major release, 6.0.0. Arangojs has been rewritten in TypeScript so the typings are generated automatically.
