### ISSUE TITLE
Is there an option to log query when it is executed

### ISSUE THREAD

**Issue by hairinwind** [arangodb/arangojs#486]
Is there an option to log query when it is executed? I doubt my code may trigger duplicated queries. If the arangojs can output the queries to the log file. That can help me to find out the issue. 

Thanks,

**Comment by pluma** [comment]
You could just await the query result and log when it is resolved. There's nothing arangojs can do to help you with this specifically but it's trivial to do yourself:

```
db.query("RETURN 42").then(function(res) {
  console.log("received result from query");
  return res;
}, function (err) {
  console.log("query failed");
  throw err;
}).then(...);

**Comment by Simran-B** [comment]
Also consider to turn on server-side logging of queries:
https://docs.arangodb.com/3.2/Manual/Administration/Configuration/Logging.html

**Comment by pluma** [comment]
I'm closing this as answered. If you disagree or need more specific information, feel free to reopen the issue. Have a nice day.
