### ISSUE TITLE
Arangodb+node.js  where does the query is returned ?

### ISSUE THREAD

**Issue by yuvanesh10** [arangodb/arangojs#489]
I am trying to learn arangodb with node.js and following the arango db documentation and following a syntax to return a query. the compliation is without the errors but i am not able to display the queries. can someone help me out.

```js
db.query(
  'FOR u IN user ' +
  'FILTER u.authData.active == @active ' +
  'RETURN u',
   {active: true}
).then(function (cursor) {
});
```

I have a collection name user in the db with two documents with simple data

**Comment by Simran-B** [comment]
Hi @yuvanesh10,

welcome to ArangoDB 🙂

In case you missed it, have a look at our [Node.js tutorial](https://www.arangodb.com/tutorials/tutorial-node-js/). There is a headline **AQL Queries** a bit further with an example how to handle such queries with arangojs in Node.js.

**Comment by yuvanesh10** [comment]
hai @Simran-B 
I am new to arangodb . I have been following the tutorial but somethings are  not so clear when the db is need authentication. sorry for bothering with simple questions

**Comment by yuvanesh10** [comment]
@Simran-B thank you ..,this works fine with the example given inthe documentation.but i am having little bit problem with INSERT. Getting the following error:
 ArangoError: AQL: unique constraint violated (while executing)
code:409

**Comment by Simran-B** [comment]
Each document must have a `_key` unique to that collection. If you try to insert another document with the same key, you will receive that error (unique constraint violated).

Make sure you assign a new key each time. You can leave out the `_key` attribute when inserting a document to let the database system generate a key. Note that if you retrieve a document from a collection, and try to insert it again (create a duplicate), then it has the system attributes `_key`, `_id` and `_rev`. You need to unset `_key` (or overwrite it with a new, not yet used key) to avoid a duplicate key error.

**Comment by yuvanesh10** [comment]
one quick word back. the example which you gave back to display the document. 
const arangojs = require('arangojs');
const aqlQuery = arangojs.aqlQuery;

// Const variables for connecting to ArangoDB database
const host = '127.0.0.1'
const port = '8529'
const username = 'root' // default user
const password = '' // blank password by default
const database = '_system' // default database

 // Connection to ArangoDB
db = new arangojs.Database({
    url: `http://${host}:${port}`,
    databaseName: database
});
db.useBasicAuth(username, password); // authenticate

// variable to be used in below template string
let active = true;

db.query(aqlQuery`
  FOR u IN user
    FILTER u.authData.active == ${active}
    RETURN u
`).then(
  cursor => cursor.all()
).then(
  docs => docs.forEach(doc => console.log(doc)),
  err => console.error('Query failed:\n', err.response.body)
);

this is complied without any error but doesnt display any out. like the desired output

**Comment by Simran-B** [comment]
Does the user collection in the database contain any documents that fulfill your query? Without any matching records, it won't find anything and therefore print nothing to console.


My example data (zipped): [user.json](https://github.com/arangodb/arangojs/files/1563418/user.zip)

**Comment by yuvanesh10** [comment]
yes..,i have created a new collection as users and added your code to it. still it doesnt not print anything

**Comment by Simran-B** [comment]
Is it called `users` or `user`? The query expects the latter. If that is not it, make sure you connect to the correct instances and database. You can also outcomment the filter in the query to unconditionally return all documents from the collection to narrow it down to a wrong filter statement.

**Comment by yuvanesh10** [comment]
@Simran-B hello..,I did the exact same thing and it was not working. once i  did restarted the whole server and it works just fine. thanks again. cheers !!!

**Comment by Simran-B** [comment]
Seems strange... please let us know if it reproducible fails to return something until a server restart.

**Comment by yuvanesh10** [comment]
ok sure. even sometimes the documents are not saved in arangodb. there is a bug itseems. I have refresh it sometimes and then it works fine

**Comment by Simran-B** [comment]
Are you getting any error persisting the documents? Does it works flawlessly if you create documents in arangosh?

I wouldn't expect any problems if you run server and driver locally in terms of timeouts. The server can refuse to accept writes under extreme load, but you don't seem to work with much data so far.

**Comment by yuvanesh10** [comment]
No i am not getting errors. yes you are right i dont have much data. even then there is a small refresh problem. might be wrong with the installation process or some broken packages ?

**Comment by Simran-B** [comment]
Can you please post details about your full setup? Operating system, hardware specs, software versions (ArangoDB, arangojs, Node.js) and relevant configuration (esp. for cluster).

**Comment by yuvanesh10** [comment]
OS: Debian 8.10.,arango 3.2.6 and node 8.9

**Comment by Simran-B** [comment]
Please try the latest stable release, 3.2.9, and report back if it's still an issue with that version.

**Comment by yuvanesh10** [comment]
@Simran-B yes thank you !!
