### ISSUE TITLE
Request headers for remote connection

### ISSUE THREAD

**Issue by pipechang** [arangodb/arangojs#49]
I'm trying to a simple test call to look for all collections, with the arangodb being in another server:

    config = {
        db: {
            url: 'http://test:test@1.2.3.4:8529'
        }
    };

    Database = require('arangojs');

    var db = new Database(config.db);

    db.collections(function (err, collections) {
        if (err) {
            return console.error(err);
        }
        console.log(collections);
    });

But I keep getting an unknown path error.

    '{"error":true,"code":404,"errorNum":404,"errorMessage":"unknown path \'\\\\_db\\\\_system\\\\_api\\\\collection?excludeSystem=true\'"}' } }

I have no trouble accessing the web interface, so I believe it's a headers issue, but I haven't found a workaround.

**Update: I tried installing arangodb in my local machine (windows 8) and I get the same result.

**Comment by dothebart** [comment]
can you have a look at the service control manager, and netstat
( https://docs.arangodb.com/ConfigureArango/Endpoint.html ) to find out whether its up and running?
If it fails to start, you should see error messages in the windows event log.

**Comment by pipechang** [comment]
hey dothebart, 

I can see it listening.

    Proto Recv-Q Send-Q Local Address           Foreign Address         State
    tcp        0      0 0.0.0.0:8529            0.0.0.0:*               LISTEN      -

Also tried doing a call with 'request' directly to the URL and got a 200, same as with the browser.

I'm sending you the full error output.

    { [ArangoError: unknown path '\_db\_system\_api\collection?excludeSystem=true']
        message: 'unknown path \'\\_db\\_system\\_api\\collection?excludeSystem=true\'',
            errorNum: 404,
        code: 404,
        stack: 'ArangoError: unknown path \'\\_db\\_system\\_api\\collection?excludeSystem=true\'\n    at new ArangoError (C:\\Users\\felipe\\Documents\\current\\oldsite\\node_modules\\arangojs\\lib\\error.js:10:13)\n    at C:\\Users\\felipe\\Documents\\current\\olds
        ite\\node_modules\\arangojs\\lib\\connection.js:91:71\n    at C:\\Users\\felipe\\Documents\\current\\oldsite\\node_modules\\arangojs\\lib\\util\\request.js:58:12\n    at C:\\Users\\felipe\\Documents\\current\\oldsite\\node_modules\\arangojs\\lib\\util\\once.js:
        7:15\n    at IncomingMessage.<anonymous> (C:\\Users\\felipe\\Documents\\current\\oldsite\\node_modules\\arangojs\\lib\\util\\request.js:66:11)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickCallback (node
        .js:355:11)',
        response:
        { _readableState:
        { objectMode: false,
            highWaterMark: 16384,
            buffer: [],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: true,
            endEmitted: true,
            reading: false,
            sync: false,
            needReadable: false,
            emittedReadable: false,
            readableListening: false,
            defaultEncoding: 'utf8',
            ranOut: false,
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null,
            resumeScheduled: false },
            readable: false,
                domain: null,
            _events: { end: [Object], data: [Function] },
            _maxListeners: undefined,
                socket:
            { _connecting: false,
                _hadError: false,
                _handle: [Object],
                _parent: null,
                _host: '192.168.0.10',
                _readableState: [Object],
                readable: true,
                domain: null,
                _events: [Object],
                _maxListeners: undefined,
                _writableState: [Object],
                writable: true,
                allowHalfOpen: false,
                destroyed: false,
                bytesRead: 260,
                _bytesDispatched: 199,
                _pendingData: null,
                _pendingEncoding: '',
                parser: null,
                _httpMessage: [Object],
                read: [Function],
                _consuming: true },
            connection:
            { _connecting: false,
                _hadError: false,
                _handle: [Object],
                _parent: null,
                _host: '192.168.0.10',
                _readableState: [Object],
                readable: true,
                domain: null,
                _events: [Object],
                _maxListeners: undefined,
                _writableState: [Object],
                writable: true,
                allowHalfOpen: false,
                destroyed: false,
                bytesRead: 260,
                _bytesDispatched: 199,
                _pendingData: null,
                _pendingEncoding: '',
                parser: null,
                _httpMessage: [Object],
                read: [Function],
                _consuming: true },
            httpVersionMajor: 1,
                httpVersionMinor: 1,
            httpVersion: '1.1',
            complete: true,
            headers:
            { server: 'ArangoDB',
                connection: 'Keep-Alive',
                'content-type': 'application/json; charset=utf-8',
                'content-length': '124' },
            rawHeaders:
                [ 'Server',
                    'ArangoDB',
                    'Connection',
                    'Keep-Alive',
                    'Content-Type',
                    'application/json; charset=utf-8',
                    'Content-Length',
                    '124' ],
                    trailers: {},
            rawTrailers: [],
                _pendings: [],
            _pendingIndex: 0,
            upgrade: false,
            url: '',
            method: null,
            statusCode: 404,
            statusMessage: 'Not Found',
            client:
            { _connecting: false,
                _hadError: false,
                _handle: [Object],
                _parent: null,
                _host: '192.168.0.10',
                _readableState: [Object],
                readable: true,
                domain: null,
                _events: [Object],
                _maxListeners: undefined,
                _writableState: [Object],
                writable: true,
                allowHalfOpen: false,
                destroyed: false,
                bytesRead: 260,
                _bytesDispatched: 199,
                _pendingData: null,
                _pendingEncoding: '',
                parser: null,
                _httpMessage: [Object],
                read: [Function],
                _consuming: true },
            _consuming: true,
                _dumped: false,
            req:
            { domain: null,
                _events: [Object],
                _maxListeners: undefined,
                output: [],
                outputEncodings: [],
                outputCallbacks: [],
                writable: true,
                _last: true,
                chunkedEncoding: false,
                shouldKeepAlive: true,
                useChunkedEncodingByDefault: false,
                sendDate: false,
                _removedHeader: {},
                _hasBody: true,
                    _trailer: '',
                finished: true,
                _hangupClose: false,
                _headerSent: true,
                socket: [Object],
                connection: [Object],
                _header: 'GET \\_db\\_system\\_api\\collection?excludeSystem=true HTTP/1.1\r\ncontent-type: text/plain\r\nx-arango-version: 20300\r\nHost: 192.168.0.10:8529\r\nAuthorization: Basic dGVzdDp0ZXN0\r\nConnection: keep-alive\r\n\r\n',
                _headers: [Object],
                _headerNames: [Object],
                agent: [Object],
                socketPath: undefined,
                method: 'GET',
                path: '\\_db\\_system\\_api\\collection?excludeSystem=true',
                parser: null,
                res: [Circular] },
            read: [Function],
                body:
            { error: true,
                code: 404,
                errorNum: 404,
                errorMessage: 'unknown path \'\\_db\\_system\\_api\\collection?excludeSystem=true\'' },
            rawBody: '{"error":true,"code":404,"errorNum":404,"errorMessage":"unknown path \'\\\\_db\\\\_system\\\\_api\\\\collection?excludeSystem=true\'"}' } }

**Comment by pluma** [comment]
You're on Windows, I gather? You're encountering the same issue as #47.

I've released 3.8.2, which should solve the paths on Windows.

**Comment by pipechang** [comment]
Just updated, it solves the issue.
Thanks pluma and dothebart .
