### ISSUE TITLE
db.createEdgeCollection is not a function.

### ISSUE THREAD

**Issue by yuvanesh10** [arangodb/arangojs#490]
I am trying to create a edge collection. this seems to be not working at all. I have already declared my db and the rest of const variables such as auth and etc...What am I doing wrong here ? can some one help me out ?

```js
//## Assigning the values

const arangojs = require('arangojs');
const aqlQuery = arangojs.aqlQuery;


//## Const variables for connecting to ArangoDB database

const host = '192.100.00.000'
const port = '8529'
const username = 'xyz'
const password = 'Xyz'
const path = '/_db/sgcdm_app/_api/'
const database = 'sgcdm_app'


//## Connection to ArangoDB

db = new arangojs.Database({
    url: `http://${host}:${port}`,
    databaseName: database
});
db.useBasicAuth(username, password);
db.createEdgeCollection('included_in');
```

**Comment by yuvanesh10** [comment]
@Simran-B Is there any way that you can help me with it ?

**Comment by pluma** [comment]
Looks like you're using a tutorial for an older version of arangojs. The API changes between major version updates so you may want to make sure you either use more recent tutorials or install a specific version of arangojs that matches the tutorial.

You can find the current API documentation in the README. To install an older version, use `arangojs@version` when installing arangojs with npm or yarn, e.g.

```sh
npm install arangojs@4
```

**Comment by yuvanesh10** [comment]
@pluma the version of arangojs is 5.8 and arango db is 3.2.6

**Comment by yuvanesh10** [comment]
const collection = db.edgeCollection('included_in');
const edge = await collection.edge('included_in/595783');

I have created a edge collection manually now and trying to access the data..i am getting the following errors

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by Simran-B** [comment]
`await` is not allowed in the top scope as per the current ECMAScript specs:

https://github.com/tc39/ecmascript-asyncawait/issues/9

**Comment by yuvanesh10** [comment]
@Simran-B thank you !!

**Comment by pluma** [comment]
In other words: if you just want to try things out, wrap your await code in an async function:

```js
(async function() {
  // do stuff here
  blah = await db.whatever();
  // more stuff
}());
```
