### ISSUE TITLE
ArangoError: AQL: syntax error, unexpected

### ISSUE THREAD

**Issue by yuvanesh10** [arangodb/arangojs#498]
I am trying to convert the subquery in to javascript. I would like to get the result in api. so that I can use it from front end service(angular).

server.js

// BASE SETUP
    // ## Assigning the values

const arangojs = require('arangojs');
const express = require('express');
const aqlQuery = arangojs.aqlQuery;
const bodyParser = require('body-parser');

// ## Const variables for connecting to ArangoDB database

const dbConfig = {
        host: '192.100.00.000',
        port: '8529',
        username: 'abc',
        password: 'abc',
        database: 'db1',
};

 // ## Setup express server

const port = process.env.PORT || 8080;
const app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

   // ## Connection to ArangoDB

const db = new arangojs.Database({
    url: `http://${dbConfig.host}:${dbConfig.port}`,
    databaseName: dbConfig.database
});
db.useBasicAuth(dbConfig.username,dbConfig.password);

 // ## START THE SERVER

app.listen(port, function(){
        console.log('Magic happens on port ' + port);
});

app.get('/edge', function(req, res){
db.query(aqlQuery`
     (FOR doc IN spec
     FILTER doc.serial_no == '"12345abc"'
     LIMIT 1
     RETURN doc._id
    )[0]

   FOR v IN 1 ANY startVertex belongs_to
   RETURN v`,
   {
    bindVar1: 'value',
    bindVar2: 'value',
  }
  ).then(function(cursor) {
  cursor.all().then(function(result) {
    console.log(result);
  });
 });

ERROR:
 Unhandled promise rejection (rejection id: 1): ArangoError: AQL: syntax error, unexpected ( near '(FOR doc IN spec
FILTER doc...' at position 2:6 (while parsing)

**Comment by jsteemann** [comment]
The problem seems to be that the AQL query is invalid, so there is this parse error.
The beginning of the query seems to be the particular problem:
```(FOR doc IN spec
FILTER doc.serial_no == '"12345abc"'
LIMIT 1
RETURN doc._id
)[0]
```
This actually starts a subquery, but the result of the subquery is not captured in any variable. This will not work.
You will need to assign the subquery result to a variable `startVertex` if you want to use it later in the query, e.g.
```LET startVertex = (
FOR doc IN spec
FILTER doc.serial_no == '"12345abc"'
LIMIT 1
RETURN doc._id
)[0]
```

**Comment by yuvanesh10** [comment]
something like this ?
LET startVertex = (
FOR doc IN spec
FILTER doc.serial_no == '"12345abc"'
LIMIT 1
RETURN doc._id
)[0]

FOR v IN 1 ANY startVertex belongs_to 
RETURN v

but if insert this query ..,then there is a syntax errror

**Comment by jsteemann** [comment]
Yes, changing the query like this should fix the parse error.
It works for me at least.
What syntax error is there then exactly?

**Comment by yuvanesh10** [comment]
nooo..,it worksss...There was a spelling mistake..,but it just prints in the console. I couldnt get it in api(localhost:8080/edge)

**Comment by jsteemann** [comment]
Sorry, I don't understand.
I understand that the query is now working. Good. What is the exact problem now?

**Comment by yuvanesh10** [comment]
sorry that I didnt explain properly..The query works fine..
I wanted to get the result with app.get('/edge')
instead of that my query result is just got displayed in node console

**Comment by jsteemann** [comment]
It looks like you are looking for a Foxx service then.
That will allow you to execute the query on the server side inside a Foxx application, which you can expose via a custom URL (e.g. `/edge`).

Please have a look at the Foxx manual section for this:
https://docs.arangodb.com/3.3/Manual/Foxx/

**Comment by yuvanesh10** [comment]
nooo not with foxx service

**Comment by Simran-B** [comment]
Looks like some Express.js based server, that is supposed to query ArangoDB and return the result in some form to a client. That is however unrelated to ArangoDB / arangojs.

**Comment by yuvanesh10** [comment]
guys..,dont close it
i found the answer

**Comment by Simran-B** [comment]
It's not an issue of arangojs, which this issue tracker is about. It was a syntax error in AQL, which belongs to the core, hence the [main repository](github.com/arangodb/arangodb). It's not a bug, question or feature request regarding ArangoDB however, but JavaScript and Node.js in general.

Please use the appropriate channels to ask questions about that, like StackOverflow (tags express, node.js, javascript), or make it about ArangoDB and use our Google Group or Slack chat. Issues on GitHub are not a forum intended for community discussions. We use them to track bugs, enhancement proposals and issues with our documentation.
