### ISSUE TITLE
How to get connection status ?

### ISSUE THREAD

**Issue by nvdnkpr** [arangodb/arangojs#50]
How can one get the connection and/or auth status (disconnected, connected, authentication failed etc.)  with this driver ?

**Comment by pluma** [comment]
ArangoDB connections are HTTP based. The Connection object is only a wrapper around the driver configuration and the HTTP API logic. So there's no connection status (except for the sockets of the HTTP agent, but that's too low-level to be meaningful).

Currently authentication and network errors are not handled correctly. See #24 for details on that. In any case you would only find out whether the auth is valid by performing a request.

**Comment by nvdnkpr** [comment]
So if I understand right 
```
var wrong_db = require('arangojs')( {url: 'http://user:wrongPasswordCredentials@localhost:9528', databaseName: '_system' } )

api = wrong_db.route '_api'
api.get 'version', (err, result) ->
  // with the right credentials it should give me version information as json
  // with wrong credentials this should give me an error and no result
```

but when I execute it I have the following 
 - err is null (so officially no error)
 - result is whether undefined nor null
 - result is an empty string

I'd rather expect a an error with a message than a result with no contents

**Comment by pluma** [comment]
Yes, auth errors are currently not handled correctly. Issue #24 tracks that problem. I'm closing this issue in favour of the more general #24.
