### ISSUE TITLE
Wiki Page instead of README ?

### ISSUE THREAD

**Issue by gunawanwijaya** [arangodb/arangojs#500]
can we have a wiki page for API & all related stuff? instead of a very long readme

**Comment by Simran-B** [comment]
We want to split the long readme into smaller files and put them in a subfolder "docs" if I'm not mistaken. A wiki is not really an option, because we might want to pull the docs and build them into the hosted online documentation at some point.

**Comment by gunawanwijaya** [comment]
okay then, can't wait for a better and well documented docs, fell free to close this issue

**Comment by pluma** [comment]
I'm closing this as a duplicate of #123.

**Comment by pluma** [comment]
Forgot to actually close this.
