### ISSUE TITLE
Transaction: throw custom exception, with custom code

### ISSUE THREAD

**Issue by AntoineAA** [arangodb/arangojs#508]
Hi,

Im' trying to throw a custom exception in transaction's action, but I can not set the errorNumber.

 - arangojs: 6.1.1
 - ArangoDB: 3.3.3 [linux] 64bit
 - RocksDB 5.6.0

Code:
```javascript
const action = String((params) => {
	var error = new Error('Conflict');
	error.code = 409;
	error.errorNum = 409;
	error.statusCode = 409;
	error.errorNumber = 409;
	throw error;
});

try {
	await DB.db.transaction(
		{ read: 'test', write: 'test' },
		action,
		{ id: 1 }
	);
} catch (error) {
	console.log(error);
}
```
Output:
```javascript
{
	error: true,
	errorMessage: 'Error: Conflict',
	code: 500,
	errorNum: 4
}
```
I expect to catch an exception with my custom error code.
Did I do something wrong?

Thanks!

**Comment by dothebart** [comment]
Hi, 
its working the following way: 

    const arangodb = require('@arangodb')
    var err = new arangodb.ArangoError();
    err.errorNum = arangodb.ERROR_BAD_PARAMETER; // <usually some well defined arango error
    err.errorNum = 12345; /// but here some random value
    err.errorMessage = "who's bad?";
    throw err;

**Comment by AntoineAA** [comment]
It works!
Thanks

**Comment by dothebart** [comment]
Ok, I've fixed the documentation, and we now will also forward errorNum in other cases, plus added tests. Did you find the examples in the arangojs documentation or just from https://docs.arangodb.com/devel/Manual/Transactions/TransactionInvocation.html#custom-exceptions ?
