### ISSUE TITLE
Errors in callbacks shouldn't be caught

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangojs#51]
```
db.collection('foo', function(error, collection) {
  if (error) return console.error(error);
  programmer.mistake();
  console.log(collection);
});
```
Where's my error?

**Comment by pluma** [comment]
I'm not sure I follow. What is happening and what should be happening?

**Comment by pekeler** [comment]
In node, exceptions in asynchronous code is typically bubbling up to the nearest exception handler. If there isn't a handler, the node process prints detailed information about the exception before terminating.

It seems that something in this adapter is wrapping callbacks in an exception handler. I expect my little example to terminate with a `ReferenceError: programmer is not defined`, but it doesn't. My callback is just ending quietly and the process continuous to run.

**Comment by pekeler** [comment]
Over the weekend, I've refactored my code from callbacks to promises, which are behaving correctly. So I'm not affected by this exceptions-in-callbacks-incorrectly-being-caught issue anymore.

**Comment by pluma** [comment]
Which JS environment are you using? I'm guessing this problem occurs when promises are supported and you're using the callbacks instead.

**Comment by pluma** [comment]
I've adjusted the logic so the errback is invoked outside the promise logic. This should give you the behaviour you're expecting.

**Comment by pekeler** [comment]
iojs v2.2.1
