### ISSUE TITLE
async/await usage example should be wrapped in an async function

### ISSUE THREAD

**Issue by akomm** [arangodb/arangojs#516]
It looks like the source files here declare functions "async", but the d.ts in the npm package are translated as promises, which in turn typescript does not understand when using "await" as it expect the functions to be declared "async", resulting in:

`TS1308: 'await' expression is only allowed within an async function`

Did I miss something or is there a transpiler option you guys could flip to make the d.t.s contain the "async" ?

typescript: 2.7.x & arangojs 6.x

*edit*

Okay, I got a bit confused by this:
https://github.com/arangodb/arangojs#basic-usage-example

Looks like it just need to be wrapped in an async function like this:
```js
async function x() { await y; /* ... */ }
```

When I check how it transpiles It kind of makes sense.

**Comment by pluma** [comment]
If I understand you correctly, the error you saw indicated that in order to use `await` *your* code needs to be an `async function`. This is thus unrelated to arangojs itself.

Can I close this issue?

**Comment by akomm** [comment]
Yes, regarding this issue :)

Just one question. Why is it supposed to work:
https://github.com/arangodb/arangojs#basic-usage-example

Is it possible that this docs is from before you migrated to TS and based on es6 and it works in that case, but the way TS transpiler trinspiles async/awaut requires the async func wrapper?

If not it would mean the doc has error?

**Comment by pluma** [comment]
Yeah, the example isn't entirely truthful. You would indeed need to wrap that part in an async function. However you'd rarely use arangojs directly like that. We might to replace that with a more realistic example.
