### ISSUE TITLE
Get next Batch

### ISSUE THREAD

**Issue by chicarrida** [arangodb/arangojs#528]
Hi there, 
browsing through the documentation I found the cursor API only has a .next() method. 
Is there a way to get the next batch of size _batchsize_ that I set in the options of the initial query?

Thank you

**Comment by jdobber** [comment]
To be more precise: How can I trigger

```
curl -X PUT --dump - http://localhost:8529/_api/cursor/123123
```
through the javascript driver?

So, a dirty hack within my code looks like this:

```
let c = new ArrayCursor(this.dbconn._connection, {id: cursor, result: [], hasMore: true })					
let res = await c.next()
let after = c._id
return {
	cursor: {
		after: after
        },
	docs: [res]
}
```
But is there a better way to achieve cursor-based pagination?

**Comment by pluma** [comment]
You should never need to create a cursor directly. The `next` method automatically fetches the next batch as needed but only returns the next item in the result set (which spans all batches).

Are you looking for a method that returns an array of all results per batch?

**Comment by pluma** [comment]
I'm closing this as the question seems to have been answered.
