### ISSUE TITLE
Dynamic filter template strings in AQL query.

### ISSUE THREAD

**Issue by Arun-KumarH** [arangodb/arangojs#533]
We are switching from `aqbjs` to template strings for constructing our queries and we want to dynamically build a filter for a query, given a list of filter objects, which contain a key, a value and an operator. Is it possible to do this?

DB Data:
```
[ 
  { 
    "id" : "1",
    "testdoc" : "testDocValue1" 
  }, 
  { 
    "id" : "2", 
    "testdoc" : "testDocValue2" 
  }, 
  { 
    "id" : "3",  
    "testdoc" : "testDocValue3" 
  },
  { 
    "id" : "4",  
    "testdoc" : "testDocValue4" 
  }
]
```

Lets say user provides input as two filters ( id > 2 and testdoc=testDocValue4) then this should return doc[3].
Below is my code snippet:

```
let filter = [ { field: "id", operator: ">", value: "2" }, { field: "testdoc", operator: "==", value: "testDocValue4" } ]; // Input filter Object
const collection = db.collection('test'); // collection object
```

Something like this:
```
let queryString = aql`FOR doc IN ${collection}
   LET docsList = ( FOR fil IN ${filter}
   filter doc[${fil.key}] ${fil.operand} ${fil.value} return doc )
   RETURN docsList`;
```

Is there any possibility to dynamically construct such a query using template strings?

**Comment by Arun-KumarH** [comment]
used a template string (with out aql tag) with bind variables as alternative.

**Comment by Simran-B** [comment]
@Arun-KumarH maybe aql literals are of some use too: https://github.com/arangodb/arangodb/pull/5184
