### ISSUE TITLE
Crashing on an error

### ISSUE THREAD

**Issue by ile** [arangodb/arangojs#535]
Got this error a couple of times. It crashes the Node app.

```
May 27 17:16:40 localhost myapp[16362]: _http_client.js:105
May 27 17:16:40 localhost myapp[16362]:       throw new ERR_UNESCAPED_CHARACTERS('Request path');
May 27 17:16:40 localhost myapp[16362]:       ^
May 27 17:16:40 localhost myapp[16362]: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
May 27 17:16:40 localhost myapp[16362]:     at new ClientRequest (_http_client.js:9:9)
May 27 17:16:40 localhost myapp[16362]:     at Object.request (http.js:9:9)
May 27 17:16:40 localhost myapp[16362]:     at /home/app/myapp/node_modules/arangojs/lib/util/request.node.js:9:9
May 27 17:16:40 localhost myapp[16362]:     at drainQueue (/home/app/myapp/node_modules/arangojs/lib/util/request.node.js:9:9)
May 27 17:16:40 localhost myapp[16362]:     at /home/app/myapp/node_modules/arangojs/lib/util/request.node.js:9:9
May 27 17:16:40 localhost myapp[16362]:     at callback (/home/app/myapp/node_modules/arangojs/lib/util/request.node.js:9:9)
May 27 17:16:40 localhost myapp[16362]:     at IncomingMessage.<anonymous> (/home/app/myapp/node_modules/arangojs/lib/util/request.node.js:9:9)
May 27 17:16:40 localhost myapp[16362]:     at IncomingMessage.emit (events.js:9:9)
May 27 17:16:40 localhost myapp[16362]:     at IncomingMessage.EventEmitter.emit (domain.js:9:9)
May 27 17:16:40 localhost myapp[16362]:     at endReadableNT (_stream_readable.js:9:9)
May 27 17:16:40 localhost myapp[16362]:     at process._tickCallback (internal/process/next_tick.js:9:9)
```

**Comment by ile** [comment]
This actually happens quite often. I just don't know what the input to this crashing/failing request is.

**Comment by pluma** [comment]
If I had to guess, I'd say you're probably using non-alphanumeric strings as document keys or collection names. Maybe spaces or special characters (or accented letters)?

**Comment by ile** [comment]
The key may be `[object Object]` and there is some bug in the app.

But that shouldn't crash it, should it?

**Comment by pluma** [comment]
I wouldn't expect it to crash the app but I don't know if Node chokes on it somehow.

We could validate the document key at run time but that would slow things down a bit. I'll look into if there's something we can do to better handle the error when it occurs but if you want arangojs to guard you against passing non-strings as document keys, I'd suggest using TypeScript instead of JS so you benefit from the static type signatures.

**Comment by ile** [comment]
I'll see more about this, but wouldn't a simple `try catch` guard against this?

**Comment by ile** [comment]
I seem to be using an old arangojs (5.8.0) where this happens, and it may not happen with the latest version.

Also the [object Object] key is actually a string "[object Object]".

I think this can be closed. This is what I get when I try to reproduce this:

```
(node:9108) UnhandledPromiseRejectionWarning: ArangoError: illegal document key
    at new ArangoError (/home/app/tmp2/node_modules/arangojs/lib/async/error.js:67:21)
    at Object.resolve (/home/app/tmp2/node_modules/arangojs/lib/async/connection.js:221:32)
    at _hosts.(anonymous function) (/home/app/tmp2/node_modules/arangojs/lib/async/connection.js:96:26)
    at IncomingMessage.res.on (/home/app/tmp2/node_modules/arangojs/lib/async/util/request.node.js:44:17)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by pluma** [comment]
Okay, if it's an unhandled rejection we should probably guard against that with a try/catch. Thanks for pointing that out.

**Comment by pluma** [comment]
Version 6.3.0 now handles sync errors in requests.

**Comment by bzkdjc** [comment]
I'm using **arangojs 6.10.0**, and still I'm having that same error. 

![image](https://user-images.githubusercontent.com/13347655/52354170-dc528f00-2a27-11e9-9938-f157a2456542.png)

![image](https://user-images.githubusercontent.com/13347655/52354678-c4c7d600-2a28-11e9-9ac5-7af35a7660d3.png)

**Comment by bzkdjc** [comment]
Checked! 
Due to **spaces within alphanumeric** value passed to `documentExists()`. 

So, 
If EcmaScript/Javascript permits spaces in keys, if JSON also allows it _(as it does not throws)_, then why **arangojs** hangs on that?

**Comment by pluma** [comment]
@bzkdjc Currently `documentExists` with a malformed key fails if that key is not a valid character in an URL path. I've created a PR that should prevent that exception from causing an unhandled rejection.

I'm currently working on the Collection API for the next semver major release. We should probably escape keys in the future to avoid this kind of error (and get an `ArangoError` instead).

**Comment by Simran-B** [comment]
Whitespace is not allowed in document keys, see:
https://docs.arangodb.com/3.4/Manual/DataModeling/NamingConventions/DocumentKeys.html
