### ISSUE TITLE
Explain query functionality

### ISSUE THREAD

**Issue by marktheis** [arangodb/arangojs#537]
How would I check how a query performs when using a simple query?

Currently I'm using collection.updateByExample and would like to know how the query performs, just like you can press "Explain" in the web interface.

Is that possible or should I rewrite my query in AQL?

**Comment by pluma** [comment]
The "explain" API only works for AQL queries. Simple queries are primarily convenience methods providing a subset of the same functionality.

Generally you should expect the simple queries to be slower than the AQL equivalent.

**Comment by pluma** [comment]
I'm closing this as the question appears to have been answered. If you think there's anything we can do to address this in arangojs, feel free to reopen this at any time.
