### ISSUE TITLE
documentCollection.save not returning full document

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangojs#54]
The documentation for save() implies that the callback gets called with the full document (`doc.some === 'data'` in the documentation's example). However, I only get back the new meta attributes (when using promises, if that makes any difference).

```JavaScript
{
  error: false,
  _id: 'whatever/1645465998905',
  _rev: '1645465998905',
  _key: '1645465998905'
}
```

**Comment by pekeler** [comment]
I think I'm actually OK with this behaviour. Image saving a large document, it would be wasteful to send all that data back and forth. So perhaps this is a just a documentation bug.

What might be nice though, is ArangoDB only replying with the new meta info, and the adapter merging that result with the document I saved, and then calling my callback with that merged object.

**Comment by pluma** [comment]
Merging the input and server response is probably out of scope considering where the driver is heading at the moment.
