### ISSUE TITLE
`db.collection is not a function` when trying to use within the "action" param in db.transaction

### ISSUE THREAD

**Issue by toymachiner62** [arangodb/arangojs#540]
When trying to insert data into a handful of collections within a transaction i'm getting the error `ArangoError: db.collection is not a function`

I'm following the example at the bottom of [this](https://docs.arangodb.com/devel/Drivers/JS/Reference/Database/Transactions.html) page
 
```js
  const query = String(function (params) {
      const db = require('@arangodb').db;
      const mycol = db.collection('mycol')  --> Throws the error: ArangoError: db.collection is not a function
      return []
    })


    let transaction =
      db.transaction({
        write: ['mycol'],
        read: ['mycol']
      },
      query,
      {
        doc: data,
        event: event
      }
    )
  }

  transaction
    .then(result => {
...
```

Am i doing something incorrectly?

**Comment by toymachiner62** [comment]
Solved it myself. Had to use `db._collection`

**Comment by Simran-B** [comment]
The `@arangodb` module is not to be confused with ArangoJS. You will mostly be using its db object:

https://docs.arangodb.com/devel/Manual/Appendix/References/DBObject.html
