### ISSUE TITLE
db._query(...).then is not a function

### ISSUE THREAD

**Issue by toymachiner62** [arangodb/arangojs#541]
I'm trying to run a query within a transaction and use the results of the query to manipulate some of the data.

The documentation on using transactions within arangojs is basically non-existent, but i've managed to get this far and now i'm getting the error `db._query(...).then is not a function` with the transaction code below.

How can I get the results of my query to manipulate them?

```js
const query = String(function (params) {
      const db = require('@arangodb').db

      const query = `some query which i know works`
  
          db._query(query)
            .then(cursor => {
              return cursor.next().then(result => {
                if (result !== undefined) {
                  // do stuff
                }
              })
            })
            .catch(err => {
              throw err
            })

transaction =
      db.transaction({
        write: ['mycollection'],
        read: ['mycollection']
      },
      query,
      {})
```

**Comment by pluma** [comment]
The code inside the `action` function is executed *in ArangoDB*, not in Node, which is why the API is also slightly different:

https://docs.arangodb.com/3.3/Manual/Appendix/JavaScriptModules/ArangoDB.html

Note that among other things unlike arangojs every ArangoDB API is *synchronous*. So the reason the `then` isn't working for you is that it's not returning a promise.

**Comment by toymachiner62** [comment]
Excellent i didn't know that. Is it documented anywhere that ArangoDB is synchronous?

IMO the ArangoDB examples are lacking. Some on transactions, these synchronous returns, etc would be helpful.

**Comment by pluma** [comment]
I agree that the documentation of the ArangoDB JS API is a bit lacking. The primary use cases covered by that documentation right now are [Foxx](https://foxx.arangodb.com) and arangosh. If you can point out any particular things you'd like us to improve, please open a ticket with the [ArangoDB main repo](https://github.com/arangodb/arangodb/issues)

**Comment by Simran-B** [comment]
Added a link to this issue in an internal planning ticket:
"Docs: Distinguish clearer between ArangoJS and arangodb module"
