### ISSUE TITLE
Is there a collection.exists method?

### ISSUE THREAD

**Issue by toymachiner62** [arangodb/arangojs#542]
I'm curious if there is a `.exists()` method in the js lib as there is [here](https://docs.arangodb.com/3.3/Manual/DataModeling/Documents/DatabaseMethods.html#exists) for regular arango queries.

**Comment by pluma** [comment]
There is no equivalent of this in the ArangoDB HTTP API which arangojs uses.

The most straightforward solution is to use `.get()` and check if it throws a 404 error. We might end up implementing a wrapper that does just that but it wouldn't be any more efficient.

**Comment by pluma** [comment]
We've added `exists` methods to the database, collection and graph objects.

**Comment by toymachiner62** [comment]
Is this released? If so which version? Has the documentation been update? I don't see anything regarding the `exists` method in the documentation [here](https://docs.arangodb.com/devel/Drivers/JS/Reference/)

**Comment by Simran-B** [comment]
Docs on docs.arangodb.com do not sync content from other repositories automatically, including ArangoJS.

See the changes here: https://github.com/arangodb/arangojs/commit/182c11a2f8f7a63501814a7b1bf710ce713efbf5

**Comment by pluma** [comment]
Yeah, sadly the docs don't get rebuilt automatically.

@Simran-B If we move the release process to Jenkins, can we force a rebuild of the ArangoDB for every release? I have no idea what triggers the rebuild right now.

**Comment by Simran-B** [comment]
It's not so much about automatically rebuilding, but about syncing the content from external repos. 
We have a Jenkins job to rebuild the docs, but running the sync script is a manual process on purpose. I'm not sure if it's automatically done for a release however.
