### ISSUE TITLE
TypeError: cursor.hasNext is not a function

### ISSUE THREAD

**Issue by toymachiner62** [arangodb/arangojs#543]
I'm looking at the documentation for `cursor.hasNext()` [here](https://docs.arangodb.com/devel/Drivers/JS/Reference/Cursor.html#cursorhasnext) and with the code below i'm getting the error `TypeError: cursor.hasNext is not a function`

```js
// Check if document with this id already exists, if it does, assign it a new id
  const query = `FOR doc IN clindocs
                  FILTER doc.id == "${data.id}"
                  RETURN doc`
  db.query(query)
    .then(cursor => {
      // If there are results with the same id, or if the existing id is falsy, generate a new one
      if (cursor.hasNext() || !data.id) {
...
.catch(err => {
      console.log('err = ', err)  // TypeError: cursor.hasNext is not a function
})
```

**Comment by pluma** [comment]
Can you clarify which version of arangojs you are using? The documentation is for 6.x but the API may have looked differently in the past.

**Comment by toymachiner62** [comment]
I'm using 6.2.4

**Comment by pluma** [comment]
@toymachiner62 can you verify whether the problem still persists with 6.3.0?

Also can you provide a short example demonstrating the error that we can execute? It's difficult to go from a paraphrased code snippet to a reproducible test case.

**Comment by toymachiner62** [comment]
I'm actually not able to reproduce in 6.2.4 in a different section of code i'm working on. `cursor.hasNext()` seems to work fine. I'll try to get back to the code where i originally had this issue in the next day or 2

**Comment by pluma** [comment]
@toymachiner62 I'm closing this for now. Feel free to reopen if you do manage to reproduce the error.

**Comment by ggoetz-bn** [comment]
Hi, I have the same error.  
When a query has an empty result and I call cursor.hasNext(), i get `TypeError: cursor.hasNext is not a function`. 
I need this function tp check if I got results.
