### ISSUE TITLE
Is there a way to import ArangoError?

### ISSUE THREAD

**Issue by kharandziuk** [arangodb/arangojs#547]
Is there a way to import Arango-specific errors in my code?
I want to have a behaviour similar to:

`const { ArangoError }  = require('arangojs/errors');`

**Comment by Simran-B** [comment]
There is `require("@arangodb").errors`, which gives you an object with error name constants mapped to error number and message.

For instance, you can do the following in `arangosh`:

```js
require("@arangodb").errors.ERROR_INVALID_MOUNTPOINT
{
  "code" : 3007,
  "message" : "invalid mountpath"
}
```

There is also a direct mapping to error codes:

```bash
127.0.0.1:8529@_system> require("@arangodb").ERROR_INVALID_MOUNTPOINT
3007
```

And you find an ArangoError method here:

```bash
127.0.0.1:8529@_system> require("@arangodb").ArangoError
function ArangoError() { [native code] }
```

Does this suffice?

**Comment by kharandziuk** [comment]
no, it's not. I don't want to import DB package in a project which uses the client.

also, it's probably two different kinds of errors https://github.com/arangodb/arangojs/blob/master/src/error.ts and the one from DB package. Probably, it's impossible to use instanceof check in the case

**Comment by Simran-B** [comment]
As far as I can tell, `error.ts` provides the standard error messages for HTTP error codes. This is different from ArangoDB error codes. If you copy-paste the mapping from `errors.js` then you don't have to import anything. You can't use the `@arangodb` module in Node.js/browser anyway I believe.

**Comment by pluma** [comment]
The `ArangoError` is currently not exported. Unless you need it for TypeScript I would recommend checking the `isArangoError` property (always `true` if it's an ArangoError instance) if you need to distinguish by error types.

**Comment by kharandziuk** [comment]
@pluma. Thanks.
Is there any design decision behind "not exporting errors"?

**Comment by pluma** [comment]
Not really, it's mostly an artefact of using a compiler. We should probably export at least most of the user-facing classes though, if only for TypeScript users.

**Comment by pluma** [comment]
Fixed via 6.4.0

**Comment by robross0606** [comment]
> Fixed via 6.4.0
If this was "fixed", how are ArangoError classes imported/required?

**Comment by robross0606** [comment]
What about exporting the Error message status code types?

**Comment by pluma** [comment]
@robross0606 those come from the server.
