### ISSUE TITLE
Unable to close a connection to arango established through the nodejs package

### ISSUE THREAD

**Issue by E314c** [arangodb/arangojs#550]
## System
NodeJs Version: 8.11.3
Arango version: 3.2.9
ArangoJs version: 5.8.0 (Also tested in latest: 6.3.0)

## Issue
Unable to close connections to the arango database, which causes a build up of unused connections.  
This causes issues when we may want to open a connection and perform work for a while, but close the connection afterwards, without terminating our entire nodejs application.

## Workaround
Always declare your arango connection at program load time and __NEVER__ from within a function.  
In order to close any connections, you must exit the node process that spawned them.

## Steps to reproduce:
1. Start up arango database, notice that in on `localhost:8529` dashboard that current number of client connections is ~2 (because we've logged in on web interface, which opens some connections)
2. Open an interactive node instance and run the following javascript: (leave the node process open after you have run the code)
```javascript
// Get Arango
const { Database } = require('arangojs');
// open 100 new database connections to run queries.
(new Array(100)).fill(0).forEach(()=>{
    const db = new Database({url: 'http://localhost:8529'});  // connect to localhost
    db.useDatabase('your-database'); 
    db.query('FOR x IN collection RETURN x');
    // there's no method to close the connection, but all handles will be lost
    });
// node terminal should remain open here so you can evaluate the dashboard to see the connections created.
```
3. After the above has run, you will see 100 new connections on the dashboard
4. Even after 5 minutes, the 100 connections are still present in arango
    - despite the fact you cannot access then at all (the handles have been lost and there was no way to terminate the connection)
5. Exit the node process with `.exit`
6. As soon as node process has finished, the 100 connections are terminated

---

I have tried looking in the documentation and through the interface returned by a `new Database()` for a method to close the created instance, but have not found anything. If it already exists, then it needs to be documented.
Else, there should be a method to terminate the connections from a `new Database()`

**Comment by pluma** [comment]
If I understand you correctly, you're generating arangojs instances dynamically at runtime and discarding them after use? Is there any particular reason you're doing it this way? As multiple instances won't share a connection pool you're putting a lot of load on ArangoDB this way. Keep in mind you can adjust the connection pool using the `agentOptions` (particularly `keepAliveMsecs` and `maxSockets` -- if it's a one-off use you could even make the connections single-use by setting `keepAlive: false`).

I guess it would make sense to have an explicit `close` method for situations like this where you want to explicitly disconnect early though. We could simply expose [the underlying agent's `destroy` method](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_agent_destroy) in Node.

**Comment by pluma** [comment]
I'm not flagging this as a bug as the expected use for arangojs so far has been either in short-lived processes or as a single instance in long-lived processes that benefit from an open connection and the impact can be reduced by adjusting `keepAlive` (though it's odd that connections hang around for minutes when the default is supposed to be 1000 ms).

**Comment by E314c** [comment]
Yes, we're dynamically generativing arango instances.

We have long running processes that "wake up" on triggers, perform a large amount of work, then go back to sleep. While they are sleeping there is no need to hold the arrango connections open, but when they awake we need to keep the connections open for ~30minutes. We don't terminate process on going to sleep, as the process is actually running other functions at that time (it just doesn't need arango access).

Our current workaround is to not dynamically generate the instances and keep a global process instance open, but then that means we're permanently holding connections with no need.

Is it worth raising a seperate issue for the fact that the connections don't drop after the default 1000 milliseconds?

**Comment by pluma** [comment]
Looks like `keepAliveMsecs` actually doesn't control the timeout but an unrelated delay so connections Node opens with keepalive seem to simply remain open forever. Seems we need to adjust our documentation.

I'll expose the `destroy` method nevertheless to help use cases like yours.

I'll also look into how we can implement a proper timeout to automatically destroy connections, considering Node apparently doesn't have a mechanism for this after all.

**Comment by pluma** [comment]
@E314c Try the newly published 6.4.0, which now has an explicit `close` method.

**Comment by E314c** [comment]
perfect, just what we needed 👍

**Comment by E314c** [comment]
just realised, is this issue being used to track the `keepAliveMsecs` bug too?
That's still there, so should I reopen it?

**Comment by pluma** [comment]
Well, it seems that isn't a bug and in the arangojs documentation we don't mention what it does, so there's nothing that needs changing. If we add a timeout behavior, we'll probably add a new config option.
