### ISSUE TITLE
Graphs - check if edge definition alread exists ?

### ISSUE THREAD

**Issue by Arun-KumarH** [arangodb/arangojs#551]
Is there any way to check if the edge definition already exists in a graph.
(Because if the edge def already exists the addEdgeDefinition() api throws an error saying collection already used in edge def with status code 400).

```
const db = new Database();
// assuming the collections "edges" and "vertices" exist
const graph = db.graph('some-graph');
await graph.addEdgeDefinition({
  collection: 'edges',
  from: ['vertices'],
  to: ['vertices']
});
```

**Comment by Simran-B** [comment]
You can either try to add an edge definition and catch a possible error, or retrieve the graph to inspect the existing definitions yourself:

```js
let graph = await db.graph('some-graph').get();
console.dir(graph.edgeDefinitions);
```
