### ISSUE TITLE
createDatabase parameters do not follow specfication

### ISSUE THREAD

**Issue by snocorp** [arangodb/arangojs#561]
The reference manual indicates that the users argument should be an array of:
```
username: string
passwd: string (Default: empty)
active: boolean (Default: true)
extra: Object (optional)
```

See https://docs.arangodb.com/3.3/HTTP/Database/DatabaseManagement.html#create-database

The current implementation only allows for an array of strings.

**Comment by pluma** [comment]
Yupp, that seems to be a bug in the type signature. Thanks for spotting this.
