### ISSUE TITLE
Running the test suite and failing tests

### ISSUE THREAD

**Issue by snocorp** [arangodb/arangojs#562]
I am attempting to create a contribution for #561 but there aren't any document on how to run the test suite. I've setup arango to run locally but I'm still seeing 13 of 301 tests fail for various reasons.

Is this currently expected? Is there any CI service that automatically runs the tests (I noticed that Travis was removed)?

If the tests are currently failing, I'd be glad to help where I can.

**Comment by pluma** [comment]
That bug in particular has been fixed locally.

It should be possible to run the tests simply by having ArangoDB run on port 8529 with an empty password for the `root` user. I've noticed the docs in question were accidentally moved out of the README and into the user documentation: https://github.com/arangodb/arangojs/blob/master/docs/Drivers/JS/GettingStarted/README.md

Can you clarify what tests are failing? Some tests are disabled depending on which version of ArangoDB you're testing against. Also the failover tests are always disabled.

**Comment by snocorp** [comment]
After filtering out the ones that should be fixed by #563 here are the remaining tests that fail for me:
```
  1) Managing functions
       database.listFunctions
         should be empty per default:
     AssertionError: expected [] to have property 'result'

  2) Managing functions
       database.listFunctions
         should include before created function:
     AssertionError: expected [ Array(1) ] to have property 'result'

  3) Managing functions
       database.dropFunction
         should drop a existing function:
     AssertionError: expected { error: false, code: 200 } to have property 'deletedCount'

  4) Managing indexes
       collection.createGeoIndex
         should create a geo index for one field:
      AssertionError: expected { Object (constraint, fields, ...) } to have property 'type' of 'geo', but got 'geo1'

  5) Managing indexes
       collection.createGeoIndex
         should create a geo index for two fields:
      AssertionError: expected { Object (constraint, fields, ...) } to have property 'type' of 'geo', but got 'geo2'

  6) AQL Stream queries
       database.query
         supports options:
     AssertionError: expected 10 to equal undefined

  7) AQL Stream queries
       database.query
         supports compact queries with options:
     AssertionError: expected 10 to equal undefined
```

**Comment by pluma** [comment]
Can you clarify which version of ArangoDB you're running?

**Comment by snocorp** [comment]
ArangoDB 3.3.13 [linux] 64bit, using jemalloc, build tags/v3.3.13-0-g92a0c395de, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0f  25 May 2017

**Comment by pluma** [comment]
The arangojs tests currently assume you're running the latest version of ArangoDB i.e. the 3.4 development version, which hasn't been released yet.

To explicitly tell arangojs that you're using 3.3.13 you should run the tests like this:

```
ARANGO_VERSION=30313 npm test
# or
ARANGO_VERSION=30313 yarn test
```

This sets the `arangoVersion` config, which arangojs uses to toggle its behavior, but it also selectively disables or enables tests.

**Comment by snocorp** [comment]
That worked! Thanks for your help. Feel free to close this issue.
