### ISSUE TITLE
Invalid edge can be created although the vertex does not exist ?

### ISSUE THREAD

**Issue by Arun-KumarH** [arangodb/arangojs#565]
Hello,

I have created a vertex collection named 'vertices'  and created an edge named ('vertice_to_vertice_edge') between the 'vertices' collection.
I inserted two vertices (with keys 1 and 2) and created and edge between them.

// Valid Edge created
  await createEdge('vertice_to_vertice_edge', {some: 'edgeData1'}, 'vertices/1', 'vertices/2');

// Invalid Edge should not have been created
  await createEdge('vertice_to_vertice_edge', {some: 'edgeData2'}, 'vertices/3', 'vertices/4');

If I try to create one more edge between vertex keys (3 and 4) the edge still gets created although the vertices 3 and 4 does not exist ?
Is this the expected behaviour ?
(I can post the code snippet if needed to reproduce).

Thank you.

```
async function createEdge(edgeCollectionName, data, fromID, toID) {
  if (_.isNil(edgeCollectionName)) {
    throw new Error('missing edge collection name');
  }
  if (_.isNil(data)) {
    data = {};
  }

  try {
    const collection = graph.edgeCollection(edgeCollectionName);
    collection.save(data, fromID, toID);
  } catch(ex) {
    console.log('Ex caught creating edge:', ex.message);
  }
}
```

**Comment by pluma** [comment]
Since arangojs just uses the HTTP API, this sounds like a bug in ArangoDB, not arangojs. The code you have posted here seems to correctly use the `GraphEdgeCollection`, which uses the graph API to save documents.

Can you please create an issue at https://github.com/arangodb/arangodb/issues/new and reference this one in it?

**Comment by Simran-B** [comment]
@pluma Does arangojs wrap the Gharial API, or does it use the document API for this?

**Comment by pluma** [comment]
@Simran-B As I said, it uses the graph API (i.e. gharial).

**Comment by pluma** [comment]
@Simran-B That is why I clarified it. Regular `EdgeCollection` uses the regular edge API. But the code example uses `graph.edgeCollection` which returns a `GraphEdgeCollection`.

This is the route `GraphEdgeCollection#save` uses:

```
/_api/gharial/${this.graph.name}/edge/${this.name}
```

**Comment by pluma** [comment]
To clarify: I'm assuming `graph` is indeed a Graph, not a Database.

**Comment by Arun-KumarH** [comment]
Works with DB version 3.3.9.
