### ISSUE TITLE
Add a way to cancel a query after a while (timeout option)

### ISSUE THREAD

**Issue by AntoineAA** [arangodb/arangojs#572]
In our production environment, we want to prevent requests that are too long to run indefinitely. A timeout option would be very useful for stopping the execution of these queries. Since there is no option on ArangoDB, we have to cancel the query manually from aardvark.

Do you think it would be possible to add a timeout option, at query level, that would do this automatically?

Best,

Antoine

**Comment by pluma** [comment]
This sounds like something that would need to be implemented in ArangoDB itself. Currently the API only provides a ttl (which is only relevant for the results after the query has executed):
https://docs.arangodb.com/3.3/HTTP/AqlQueryCursor/AccessingCursors.html

Implementing the API for managing queries would help by making it possible to cancel these queries using arangojs but I see no way to easily solve the timeout within arangojs itself. If you want an automatic timeout I'd suggest opening a new issue on the ArangoDB repo: https://github.com/arangodb/arangodb/issues

**Comment by pluma** [comment]
See also https://github.com/arangodb/arangojs/issues/474

**Comment by AntoineAA** [comment]
Hi @pluma,
Thanks for your reply!

**Comment by AntoineAA** [comment]
We already opened this: https://github.com/arangodb/arangodb/issues/6146

**Comment by pluma** [comment]
I'm closing this since an issue on the ArangoDB repo exists for this and there's nothing else we can do in arangojs in the meantime. Feel free to reopen when the option is supported by ArangoDB.

**Comment by AntoineAA** [comment]
@pluma OK, thanks!

**Comment by pluma** [comment]
@Puneeth-Kadamba Please check the issue on the ArangoDB repo linked above.
