### ISSUE TITLE
sort not working when using bindvars

### ISSUE THREAD

**Issue by Soultripper** [arangodb/arangojs#58]
Hey

I seem to not be able to pick up the sort function when using a AQL with a @sort binding

Here's a most basic example

```` db.query("FOR f IN films SORT @sort LIMIT 3 RETURN f.title",  {sort: 'f.title asc'}, callback) ````

returns
````[ 'Test Film 127933', 'Test Film 123403', 'Test Film 31017' ]````

but 

```` db.query("FOR f IN films SORT f.title asc LIMIT 3 RETURN f.title", callback) ````
returns
````[ 'Test Film 1', 'Test Film 10', 'Test Film 100' ]````

Is there something I'm doing wrong?

Turns out there was

```` db.query("FOR f IN films SORT f.@sort LIMIT 3 RETURN f.title",  {sort: 'title asc'}, callback) ````

need to key on the property only ;)

**Comment by matikucharski** [comment]
@Soultripper How did you solved that?
