### ISSUE TITLE
regexp support in nodejs

### ISSUE THREAD

**Issue by OzqurYalcin** [arangodb/arangojs#582]
```js
    var Arango = require("arangojs").Database;
    var arangoconn = new Arango("http://username:password@localhost:8529");
    var search1 = async (key) => {
        return new Promise((resolve, reject) => {
            arangoconn.useDatabase("db").query({
                query: "FOR data IN keywords FILTER data.keyword LIKE @key RETURN data",
                bindVars: {
                    key: "%" + key + "%"
                }
            }).then(
                cursor => cursor.all()
            ).then(
                res => resolve(res),
                err => reject(err)
            );
        });
    };
    var search2 = async (key) => {
        return new Promise((resolve, reject) => {
            arangoconn.useDatabase("db").collection("keywords").byExample({
                keyword: new RegExp(key)
            }).then(
                cursor => cursor.all()
            ).then(
                res => resolve(res),
                err => reject(err)
            );
        });
    };
    var data1 = await search1("keyword");
    var data2 = await search2("keyword");
    console.log(data1);
    console.log(data2);
```
search1 functions worked fine, but search2 failed.
i think, arrangodb must support regex search as in search2 function.

**Comment by Simran-B** [comment]
`byExample()` maps to the endpoint `PUT /_api/simple/by-example`. This belongs to the [HTTP interface for Simple Queries](https://docs.arangodb.com/3.4/HTTP/SimpleQuery/). All `/_api/simple` routes are deprecated from 3.4.0 on. Simple Queries in the JS API were [deprecated](https://docs.arangodb.com/3.4/Manual/Appendix/Deprecated/) in 3.0 already. Support for regular expressions in the by-example route on the server side is therefore not to be expected.

On the driver side it might be possible to transform the query, but I am against such a solution. You should use an AQL query with a [regex function](https://docs.arangodb.com/3.3/AQL/Functions/String.html#regextest) instead:

```js
                query: "FOR data IN keywords FILTER REGEX_TEST(data.keyword, @key) RETURN data",
                bindVars: {
                    key: "#[0-9a-fA-F]{6}"
                }
```

**Comment by pluma** [comment]
In order to support regular expressions for example queries, those queries would need to support regular expressions on the ArangoDB side. As the simple queries are no longer being developed and will be removed in a future version of ArangoDB, I don't see anything actionable here.
