### ISSUE TITLE
Feature request: Support VelocyPack in arangojs

### ISSUE THREAD

**Issue by neunhoef** [arangodb/arangojs#584]
It would be good to be able to use VelocyPack in JavaScript. Some sort of support library would have to be created as well.

**Comment by pluma** [comment]
If we want to pursue the path of native bindings, I think we should revive the Node.js VelocyStream implementation, i.e. a vst library that arangojs can build on. If we just want to support the VelocyPack format in JS I could implement it in JS myself, but that would overall be slower than just using JSON.

Whoever implements the VelocyStream library needs a strong grasp of C++, V8 and gyp (or whatever is currently used for Node native bindings). That person isn't me.

**Comment by Simran-B** [comment]
It wouldn't work in browsers, would it?

If we want to target both Node and browsers, then e.g. Rust -> WebAssembly could be interesting. It might end up being a lot slower though, because of JS <-> WASM. Maybe check again in a year or so.

**Comment by pluma** [comment]
I'm closing this for now as there is no clear way forward at the moment. The issue might be revisited in the future.
