### ISSUE TITLE
Help understanding the route api

### ISSUE THREAD

**Issue by darlenya** [arangodb/arangojs#587]
The documentation of the route API says I can use it to execute API calls not yet implemented in the driver directly. But I was not able to make it work. For example I would like to execute this HTTP API call:

```
curl --header 'accept: application/json' --header 'Authorization: Basic cm2vd4pybfa0' --dump - http://localhost:8529/_api/user
```

I have created this js code
```
const Database = require('arangojs')
const db = new Database({ url: `http://localhost:8529` })
db.useBasicAuth('root', 'root')
db.useDatabase('_system')

db.route().request({
  path: `/user/`,
  method: 'GET'
}).then((response) => {
  console.log('users:', response)
})
.catch(err => {
  console.log(err)
})
```

This results in an API call:
```
/_db/_system/user
```

**Comment by pluma** [comment]
@darlenya keep in mind that `/_api` is just a shorthand for `/_db/_system/_api` so you're almost on track.

The full URL you want is `/_db/_system/_api/user`, just set the path to `/_api/user` and you should be fine.

**Comment by darlenya** [comment]
it works!

Thanks a lot!
