### ISSUE TITLE
keepNull not supported (anymore) for aql update queries?

### ISSUE THREAD

**Issue by santo74** [arangodb/arangojs#588]
I need to update documents via an AQL query while removing / ignoring attributes with a null value.
To achieve this, I'm specifying "keepNull: false" as an option, but attributes with null values are still inserted in the document.
This did work in the past (with an old project about a year ago).

Simplified example:
```
const query = 'FOR doc IN users FILTER doc.key == @key UPDATE doc WITH @newValue IN users';
const bindVars = {key: '123456', newValue: { active: true, referrals: null}};
const dbOpts = {keepNull: false};
db.query(query, bindVars, dbOpts).then(...)
```

**Comment by Simran-B** [comment]
The [documentation of `database.query()`](https://docs.arangodb.com/3.4/Drivers/JS/Reference/Database/Queries.html#databasequery) refers to [Setting Options](https://docs.arangodb.com/3.4/AQL/Invocation/WithArangosh.html#setting-options) for a list of supported options, which does not mention `keepNull` at all.

I think what you want is `OPTIONS { keepNull: false }` in the AQL query itself:

```js
const query = 'FOR doc IN users FILTER doc.key == @key UPDATE doc WITH @newValue IN users OPTIONS { keepNull: false }';
const bindVars = {key: '123456', newValue: { active: true, referrals: null}};
db.query(query, bindVars).then(...)
```

**Comment by santo74** [comment]
Actually I already tried that but it returned an "AQL: syntax error" so I thought it was not the right solution.
But after your suggestion to try it that way I tried again and after some more digging I found there was a LIMIT statement in my update query, which isn't compatible with the OPTIONS attribute.
Removing the LIMIT (which isn't necessary here) solved it.

Thanks for your help!

**Comment by Simran-B** [comment]
You can use LIMIT together with OPTIONS, but remember that OPTIONS belongs to the UPDATE operation. So you must not place a LIMIT anywhere between UPDATE ... WITH ... IN ... OPTIONS, but before or after this operation.

**Comment by santo74** [comment]
Ok, thanks for the clarification.
