### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by iraycd** [arangodb/arangojs#594]
```
(node:9190) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at Socket.socketCloseListener (_http_client.js:354:25)
    at Socket.emit (events.js:187:15)
    at TCP._handle.close [as _onclose] (net.js:596:12)
(node:9190) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9190) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by iraycd** [comment]
Latest docker

https://github.com/arangodb/arangodb-docker/blob/c98889cf79d8cdeaf56cdedb0c8748ca434f1094/alpine/3.4.1/Dockerfile

First observed it while creating and dropping multiple databases at time. 

But, not I see it happening for many queries.

**Comment by iraycd** [comment]
https://github.com/request/request/issues/2047
https://github.com/firebase/firebase-tools/pull/1096/files

```javascript
  options.headers = options.headers || {};
  options.headers["connection"] = "keep-alive";
```

I guess this might help. Thank you.

**Comment by pluma** [comment]
That seems unlikely unless something changed in Node. Arangojs already uses keep-alive by default. I'd have to investigate this. Can you check a more recent version of Node than LTS? An unhandled rejection should cause an uncaught error in newer versions, so this would not only log the warning but actually kill the container.

Sadly the stack trace doesn't really provide a lot of information. You might want to try installing this library and importing it at some point in your code: https://www.npmjs.com/package/asynctrace That might provide more detailed stacktraces that could help figuring out what's going on.

**Comment by iraycd** [comment]
Sorry, I am not sure how to do it JEST, I am using JEST for testing.
I don't know how to exactly how to get it a better stack trace. I have tried.

https://github.com/facebook/jest/issues/5104

I am using https://github.com/roboncode/orango/ to connect and disconnect.

I would suggest you on closing the issue until me/someone comes up with a stack-trace, thank you.
