### ISSUE TITLE
Memory leak in node-linkedlist

### ISSUE THREAD

**Issue by x3cion** [arangodb/arangojs#601]
Hey there,

I created a pull request ( https://github.com/kilianc/node-linkedlist/pull/7 ) for node-linkedlist quite some time ago, but it's not accepted yet and it seems the project is not very active.

The package has a memory leak that I found because I'm using arangojs. On shift(), the reference to the old head is not removed, thus keeping all old heads as long as there's pressure on the queue.

You might want to integrate the whole library (with my fix) or switch to another implementation.

Hope you can fix this soon, so I can drop my workaround github dependency.

**Comment by pluma** [comment]
Thanks. The project hasn't been touched in years and uses some outdated APIs. I think I'll inline it and apply the changes.

**Comment by breakbild** [comment]
Looks like only Array like methods (push/shift/length) are used on _queue. As a quick fix I replaced this._queue = new LinkedList(); with this._queue = []; in class Connection (connection.js).

**Comment by pluma** [comment]
@breakbild the problem is that unintuitive as it may seem, LinkedList is significantly faster than native array operations. I tried replacing it but the slowdown was noticeable when performing a large number of queries at the same time.

**Comment by x3cion** [comment]
I merged master and the pull request #609 is conflict free again. I also updated my library. 

I'm still using my linkedlist branch in production environments to override the broken linkedlist implementation, which should not be the way to do things. Please let me know if I can help somehow.
