### ISSUE TITLE
db.graph('name') returns empty instance

### ISSUE THREAD

**Issue by VPaulV** [arangodb/arangojs#61]
Hi, I have problem with graph creation. Looks like arangojs handle it incorrectly -  db.graph('name') returns empty intsance instead of Graph.

Error:
```
api_1    | /app/dataServices.js:194
api_1    |          graph.create(
api_1    |               ^
api_1    | TypeError: undefined is not a function

```

Code example:
```javascript
var Database = require('arangojs');
var db = new Database({url:'http://arango_1:8529'});

db.database('someDB', true, function(err, database) 
    {
        if(err) 
            return cb(new Error("count too low"));

        console.log('DB exist: %j', database.name);

        var graph = database.graph('connectionsGraph');
        graph.create(
                {
                name: 'connectionsGraph',
                edgeDefinitions: [
                {
                    collection: 'connections',
                    from: [
                        'nodes'
                    ],
                    to: [
                        'nodes'
                    ]
                }
            ]
        }, function (err, graph) 
        {
            if(err) 
                return console.log('fail');        

            console.log('Graph was created: %j', graph.name);
        });
```

Could you help with this issue, please?

Best regards,

Paul

**Comment by pluma** [comment]
I'm not sure which version of arangojs you're trying to use, but it looks like you're on arangojs@latest (i.e. 3.9.1) which is what you get if you just install arangojs with npm without specifying a different dist-tag.

The documentation reflects the latest 4.0.0-alpha release -- what you get if you `npm install arangojs@alpha`. The important change is that `db.database` no longer exists (it has been replaced by `db.useDatabase`) and `db.graph` is no longer async (it no longer makes a roundtrip call to the server).

The documentation you want to refer to for 3.9.1 is [this one](https://github.com/arangodb/arangojs/tree/v3.9.1). The new version of arangojs will be available as arangojs@latest as soon as the kinks have been ironed out and its test coverage is less horrible.
