### ISSUE TITLE
Response takes longer time when using arangojs driver.

### ISSUE THREAD

**Issue by nkanand4** [arangodb/arangojs#612]
ArangoJS Version: Tested on both 6.9.0 and 5.6.1
I have a query that takes longer, 4 seconds to 9 seconds, to return when using js driver but works swiftly on UI interface.
<img width="1432" alt="Screen_Shot_2019-07-07_at_9 55 05_PM" src="https://user-images.githubusercontent.com/667996/60780070-9d258880-a102-11e9-87c8-bc889e5b92de.png">

When using web interface, the same query takes hardly 2 ms.
<img width="1270" alt="Screen_Shot_2019-07-07_at_9_55_59_PM" src="https://user-images.githubusercontent.com/667996/60780077-a57dc380-a102-11e9-8d40-91d02e32e527.png">

Query Explain:
```
Query string:
 FOR contact in contacts
     FOR cla in contact_location_associations
             let locations = (FOR cl in customer_location FILTER cl._from == @customerId RETURN 
 cl._to)
             FILTER cla._from == @actorLocation && cla.toCustomerLocation IN locations
                 && contact._id == cla._to
 RETURN contact

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
 15   IndexNode          569     - FOR cla IN contact_location_associations   /* edge index scan */
 14   IndexNode          569       - FOR contact IN contacts   /* primary index scan */
 10   SubqueryNode       569         - LET locations = ...   /* const subquery */
  4   SingletonNode        1           * ROOT
 16   IndexNode            1             - FOR cl IN customer_location   /* edge index scan */
  8   CalculationNode      1               - LET #8 = cl.`_to`   /* attribute expression */   /* collections used: cl : customer_location */
  9   ReturnNode           1               - RETURN #8
 17   CalculationNode    569         - LET #10 = ((cla.`toCustomerLocation` in locations) && (cla.`_from` == "location/1313"))   /* simple expression */   /* collections used: cla : contact_location_associations */
 12   FilterNode         569         - FILTER #10
 13   ReturnNode         569         - RETURN contact

Indexes used:
 By   Type      Collection                      Unique   Sparse   Selectivity   Fields               Ranges
 15   edge      contact_location_associations   false    false        50.09 %   [ `_from`, `_to` ]   (cla.`_from` == "location/1313")
 14   primary   contacts                        true     false       100.00 %   [ `_key` ]           (contact.`_id` == cla.`_to`)
 16   edge      customer_location               false    false        99.93 %   [ `_from`, `_to` ]   (cl.`_from` == "customers/13518385")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   interchange-adjacent-enumerations
  4   move-calculations-up-2
  5   move-filters-up-2
  6   use-indexes
  7   remove-filter-covered-by-index
  8   remove-unnecessary-calculations-2
```

**Comment by pluma** [comment]
Note that the web UI is showing the time it took ArangoDB to execute the query whereas your code likely measures a lot of overhead (i.e. everything that happens between the function call and the promise resolving).

Some overhead is expected but 4 seconds seems a bit much. Is ArangoDB running locally? If not, there might be some network overhead involved. It looks also like your code is running with some debug instrumentation in your IDE, which may also incur some additional overhead.

**Comment by nkanand4** [comment]
Yup, it's running locally. It was running fine when we had lesser records than 100. Then to scale test, I kept running tests and after 1500 rows, I am getting slow responses. Instrumentation is added only to show the slowness right before db.query using console.time and console.timeEnd before any processing of data happens. Basically, I am profiling only db.query.

**Comment by pluma** [comment]
Can you show the code with the db.query? Are you just `await`ing for the cursor it returns or consuming it (e.g. fetching all results)?

**Comment by nkanand4** [comment]
<img width="604" alt="Screen Shot 2019-07-08 at 8 02 53 AM" src="https://user-images.githubusercontent.com/667996/60812331-da1b6a80-a156-11e9-8463-24a6c5bec549.png">

**Comment by pluma** [comment]
Okay, that IS weird.

Are you confident there isn't anything else using arangojs at the same time in your code? The only thing I can think of that would explain a 9 second latency would be a delay from other requests having already filled up the request queue.

I think the web UI by default limits the response to the first 1000 rows (there's a dropdown in the top right in your screenshot). Maybe the reason the web UI seems so much faster is that you're not actually fetching the same result set as in arangojs? Try setting the limit to a much higher setting and see if the web UI also becomes much slower.

**Comment by nkanand4** [comment]
Yup, I had made sure and isolated it to only 1 xhr before creating this issue.

<img width="1440" alt="Screen Shot 2019-07-08 at 9 06 59 AM" src="https://user-images.githubusercontent.com/667996/60816718-ea841300-a15f-11e9-89f4-7aea0803e21d.png">

**Comment by pluma** [comment]
In that case I'm convinced your query simply doesn't scale well and you're seeing faster responses in the web UI because you just never fetch more than 1000 results (because of the dropdown that limits the result set). The web UI should show similar slowdowns if you bump up the result size.

**Comment by nkanand4** [comment]
Bumped up the numbers to 10k on web UI, still performing good.
<img width="1288" alt="Screen Shot 2019-07-08 at 9 38 58 AM" src="https://user-images.githubusercontent.com/667996/60818993-523c5d00-a164-11e9-87ce-627da0a22536.png">

**Comment by pluma** [comment]
Oof. That's odd. The only other thing I can think of would be that arangojs parses the JSON response whereas the web UI just dumps it as a string into the JSON editor (AFAIK). Depending on the size of the response this might have an impact.

That said, the network monitor screenshot also shows a 4 second response time. Is that related? Also, what's the _actual_ response time for the web UI? The milliseconds reported by it are just the actual query execution time, so you'd probably have to time the response manually (also check the network monitor for the raw response time).

**Comment by nkanand4** [comment]
Well, today I made request using curl and noticed that even that takes 4 seconds.
<img width="1289" alt="Screen Shot 2019-07-11 at 11 23 42 PM" src="https://user-images.githubusercontent.com/667996/61102333-0410ad80-a433-11e9-9523-96a971ecce8b.png">

However, this contains some information about stats. Can someone guide me what causing the slowness?

**Comment by nkanand4** [comment]
Issue isolated to not being ArangoJS driver, hence closing it here. Will take it up in ArangoDB issue list. Thanks for all the help @pluma.
