### ISSUE TITLE
VertexCollection cannot save an array of documents

### ISSUE THREAD

**Issue by Arun-KumarH** [arangodb/arangojs#619]
The graphVertexCollection does not allow to store an array of documents (This was working earlier in DBv3.3.14 but not in DBv3.4.7).

https://github.com/arangodb/arangojs/blob/master/src/test/19-graph-vertex-collections.ts#L59

Changing  `const data = { foo: "bar" };` to an array `const data=[{foo:"bar"}]` spits out below error.
Should this be reported to ArangoDB or an issue with driver ?

```
ArangoError: VPack error: Expecting Object (exception location: /work/ArangoDB/arangod/GeneralServer/RestHandler.cpp:464). Please report this error to arangodb.com
      at new ArangoError (src/error.ts:76:17)
      at Object.resolve (src/connection.ts:356:20)
      at callback (src/connection.ts:210:16)
      at IncomingMessage.<anonymous> (src/util/request.node.ts:117:15)
      at endReadableNT (_stream_readable.js:1130:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by pluma** [comment]
This should probably not result in a VPack error that includes a file path.

Looks like an ArangoDB bug to me. Can you please open an issue on the main ArangoDB repo for this? https://github.com/arangodb/arangodb/issues/new

This should either still work or result in a less exotic error.

**Comment by pluma** [comment]
I'm closing this as it seems to be an issue with ArangoDB rather than the driver and there hasn't been any activity in a while. If the issue persists, please open an issue with the ArangoDB repo.
