### ISSUE TITLE
Return array of documents with cursor.next()

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangojs#624]
We used to run into `cursor not found` error quite often despite having a basic ArangoDB deployment. The investigation showed that we had misunderstood `cursor.next()` implementation. 

I believe it is confusing to use since it doesn't always make a request into `/_api/cursor` and therefore it doesn't restart `ttl` of the cursor. So the following code will fail with `cursor not found` error despite calling `cursor.next()` every 1s and my `ttl` is 2s:
```
const consumeData = (data) => new Promise((resolve) => setTimeout(() => resolve(data), 1000));

const cursor = await db.query("FOR i IN 1..10 RETURN i", {}, {batchSize: 5, ttl: 2});
while (cursor.hasNext()) {
    await consumeData(await cursor.next());
}
```

I would expect `cursor.next()` to always "ping" the cursor in the database, so `ttl` restarts. However, since this doesn't exist in arangodb API, I suggest changing the return value of `cursor.next()` to an array of documents. This change will also make arangojs consistent with arangodb API.

**Comment by gurisko** [comment]
@pluma Any thoughts?

**Comment by pluma** [comment]
The problem I see is that it's unintuitive for the result cursor of a query that returns X items to instead return X/Y batches of Y items each. This would require nested while-loops to consume the data iteratively. It would also diverge from the server-side JS API.

Also the problem you're describing would be timing dependent even if you did consume the data batchwise if the `consumeData` function is slow enough. You could solve your case by setting a `batchSize` of 1 or fetching all results at once (via `await cursor.all()`).

Alternatively I could imagine adding a  `nextBatch` method (with `hasNextBatch`) that operates batch-wise.

**Comment by pluma** [comment]
I've added a method `cursor.nextBatch` which behaves like `cursor.next` but for batches instead of individual values.
