### ISSUE TITLE
Poor errors for when providing bad to/from values

### ISSUE THREAD

**Issue by janat08** [arangodb/arangojs#635]
The error for bad to/from value during insert is somewhat vague, but what exacerbates it is that it doesn't show the value that was provided.

**Comment by pluma** [comment]
Can you give an example for the kind of error message you're referring to?

**Comment by janat08** [comment]
I imagine it might relate to nested writes. Something like in https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/janat08/recommendationQuiz&ved=2ahUKEwjq9ZGcq_TmAhUMOSsKHQL1AUkQFjAAegQIBRAB&usg=AOvVaw3_3pQDP_ewpik_BCK6-XIM

**Comment by pluma** [comment]
@janat08 can you link to specific lines of code? That seems to be the google search result page link for a GitHub repo.

**Comment by janat08** [comment]
I no longer remember.

**Comment by pluma** [comment]
I'm closing this issue as there's not much actionable without additional information. This seems to be more about ArangoDB than the driver.

The upcoming major release of ArangoDB changes the signature of the `save` method so the `from` and `to` fields are no longer passed as positional arguments, which should reduce the chances for mistakes.
