### ISSUE TITLE
Transaction Rollbacks

### ISSUE THREAD

**Issue by thelebdev** [arangodb/arangojs#637]
As in MySQL for Javascript, a developer has the ability to manually `commit()` and `rollback()` a transaction.

So assume we have the following structure in a NodeJS application using MySQL.
```
const MYSQL_CLIENT = [...] // already instantiated transaction.
try {
    let queryRes = await MYSQL_CLIENT.query(...); // an insert query
    /**
    * other
    * logic
    * here
    */
    await MYSQL_CLIENT.commit();
    return 200;

} catch (err) {
    await MYSQL_CLIENT.rollback(); // rollback the transaction
    await MYSQL_CLIENT.close(); // close the connection with MySQL
}
```

I'm trying to figure out if the same behavior can be applied for ArangoJS
```
const ARANGO_CLIENT = [...] // already instantiated arango client.
try {
    ARANGO_CLIENT.query(...) // an insert query
    /**
    * other
    * logic
    * here
    */
    await ARANGO_CLIENT.commit();
    return 200;
} catch (err) {
    await ARANGO_CLIENT.rollback();
}
```
The reason why I'm doing this is because I've got several controllers that perform an insert / update / delete query on Arango before several pieces of logic. In the case where any part of the code crashes, I want to rollback those changes.

**Comment by pluma** [comment]
Check the streaming transactions API: https://github.com/arangodb/arangojs/blob/v6.12.0/docs/Drivers/JS/Reference/Database/Transactions.md#databasebegintransaction

`transaction.abort` is the ArangoDB equivalent of SQL rollback.

**Comment by pluma** [comment]
I'm closing this issue as I understand the rocket emoji to be affirmative.
