### ISSUE TITLE
ensureIndex is not a function

### ISSUE THREAD

**Issue by noahehall** [arangodb/arangojs#639]
according to the docs, you create indexes against a collection, best practice using the ensureIndex method.

However, in yoru tests there is no ensureIndex (https://github.com/arangodb/arangojs/blob/master/src/test/11-managing-indexes.ts)

Are we forced to use create index?

[according to docs](https://www.arangodb.com/docs/stable/indexing-working-with-indexes.html#creating-an-index
```
ndexes should be created using the general method ensureIndex. This method obsoletes 
the specialized index-specific methods ensureHashIndex, ensureSkiplist, 
ensureUniqueConstraint etc.
```

**Comment by noahehall** [comment]
just a note for anyone else pulling out there dreadlocs,

the http createIndex method behaves similarly to arangosh ensureIndex 

https://www.arangodb.com/docs/stable/http/indexes-working-with.html
`200: If the index exists, then a HTTP 200 is returned.`

**Comment by pluma** [comment]
The `createIndex` method will be renamed to `ensureIndex` in the upcoming major release to address this confusion.

**Comment by noahehall** [comment]
thank you
