### ISSUE TITLE
Improved ESM support

### ISSUE THREAD

**Issue by LJNeon** [arangodb/arangojs#641]
In Node.js 12 ESM is behind a flag, but in Node.js 13 it's not, and based on that and how the Node.js team initially planned to [stabilize ESM by Node.js 12 LTS](https://medium.com/@nodejs/announcing-a-new-experimental-modules-1be8d2d6c2ff) it is highly likely that ESM will be stable by Node.js 14 this April. You can already [import CommonJS modules](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_code_import_code_statements), however it has no support for named exports and simply stores everything as an object with the default export. Adding named exports is relatively easy, you simply need to [make a wrapper .mjs file](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_approach_1_use_an_es_module_wrapper) to export everything as ESM. This has full backwards and forwards compatibility with ESM and CommonJS modules if you use some fallbacks. In Node.js 12 and 13, this could currently be done with some sort of `/esm` subpath, where you would import `"arangojs/esm"` instead. In future versions where [conditional exports](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_conditional_exports) are unflagged, the subpath wouldn't even be needed and simply importing `"arangojs"` would work. This not only maintains backwards compatibility with CommonJS modules, but also with existing ESM code, as without the subpath in both Node.js 12 and 13 it will still have everything in the default export.

**Comment by pluma** [comment]
There's currently no clear benefit to supporting ESM. The main use case would be bundle size reduction for the browser version but that would require conditional imports which currently don't make any sense given how the arangojs implementation is structured.

It's mid-2020 and the Node.js ESM story is still not looking like it will be fully settled anytime soon (at least that's what I've heard from the core team), so I'm postponing this until after v7.

**Comment by LJNeon** [comment]
That's a fair point, also looking back on this the issue description is a giant mess of inaccurate predictions, it may be better to open a new issue down the road instead of postponing this one.

**Comment by pluma** [comment]
Okay, I'll close this issue then. Feel free to open a new one should ESM support become viable in the future.
