### ISSUE TITLE
Joins across databases possible?

### ISSUE THREAD

**Issue by noahehall** [arangodb/arangojs#649]
lets say i have two imaginary databases: **Guild** and **Msg**

players join guilds. guilds have chat rooms. players join a guild's chat room and send messages to each other.

lets also say when a player joins a guilds chat room, I want to fetch:
- the guild from the Guild database 
- the guilds msgs from the Msg database

currently i am doing ```fetchGuild(someguild).thenOnSuccess().fetchGuildsMsgs()```

the [aql docs concerning joins](https://www.arangodb.com/docs/3.6/aql/examples-join.html) has examples for joining documents from *distinct* collections, but in my case i  need to join *across databases* and none of my attempts are working..

To add some context, here is a copypasta of my file for chatting with arango

```js
import { aql } from 'arangojs';


const getDocKey = record => (
  record._key
    || record.key
    || record.id
    || record.name
    || record.handle
);

const query = (type) => ({
  data: {
    collectionName,
    docKey,
    projection,
    filter,

    ...data
  },
  db
}) => {
  const thisDocKey = docKey || getDocKey(data);

  switch (type) {
    // should be upsert replace
    case 'bulk': return (
      aql`
        let records = ${data.records.map(r => ({ ...r, _key: getDocKey(r) }))}
        FOR record in records
        UPSERT { _key: record._key }
        INSERT record
        UPDATE record
        INTO ${db.collection(collectionName)}
      `
    );


    case 'update': {
      const record = {
        ...data,
        _key: thisDocKey,
      };

      return  (
        aql`
          let key = ${thisDocKey}
          let record = ${record}
          UPSERT { _key: key }
          INSERT record
          UPDATE record
          IN ${db.collection(collectionName)}
        `
      )
    };

    case 'updateReturn': {
      const record = {
        ...data,
        _key: thisDocKey,
      };

      return  (
        aql`
          let key = ${thisDocKey}
          let record = ${record}
          UPSERT { _key: key }
          INSERT record
          UPDATE record
          IN ${db.collection(collectionName)}
          RETURN NEW
        `
      )
    };

    // TODO
    // need to add reverse of this logic, i.e. remove a
    case 'updateReturnUnionPlayerIds': {
      const record = {
        ...data,
        _key: thisDocKey,
      };

      return  (
        aql`
          let key = ${thisDocKey}
          let record = ${record}
          UPSERT { _key: key }
          INSERT record
          UPDATE { playerIds: UNION_DISTINCT(OLD.playerIds, record.playerIds) }
          IN ${db.collection(collectionName)}
          RETURN NEW
        `
      )
    };

    case 'replace': {
      const record = {
        ...data,
        _key: thisDocKey,
      };

      return (
        aql`
          let key = ${thisDocKey}
          let record = ${record}
          UPSERT { _key: key }
          INSERT record
          REPLACE record
          IN ${db.collection(collectionName)}
        `
      )
    };


    case 'byKey': return (
      `
        RETURN DOCUMENT("${collectionName}/${thisDocKey}")
      `
    );


    case 'filter': return (
      aql`
        FOR doc in ${db.collection(collectionName)}
        FILTER ${aql.literal(filter)}
        return doc
      `
    );

    case 'filterProjection': return (
      aql`
        FOR doc in ${db.collection(collectionName)}
        FILTER ${aql.literal(filter)}
        return ${aql.literal(projection)}
      `
    );

    case 'all': return (
      `
        RETURN ${collectionName}
      `
    );


    default: throw `${type} not setup for qureyArango.query`
  }
}


export default {
  // utility
  // write
  bulk: query('bulk'),
  replace: query('replace'),
  update: query('update'),
  updateReturn: query('updateReturn'),
  updateReturnUnionPlayerIds: query('updateReturnUnionPlayerIds'),

  // read
  all: query('all'),
  byKey: query('byKey'),
  filter: query('filter'),
  filterProjection: query('filterProjection'),

  // specific - hoever should all use one of the above
  newActivityActionEvent: query('newActivityActionEvent'),
}

```

now what ive been trying to do is add another utility method for joining arbitrary collections across databases

```js
case 'joinSomeThing': return (
   aql`
        FOR poop in ${dbONE.collection(collectionNameONE)}
          FOR flush in ${dbTWO.collection(collectionNameTWO)}
       FILTER poop.toiletId == flush.toiletid RETURN { ... }"
      `
)
```

but its not working

**Comment by jsteemann** [comment]
Joins between collections of different databases are unsupported in AQL and ArangoDB.
Any operation that is carried out, e.g. running a transaction or an AQL query, is always restricted to being executed in one database.
This is also expressed in the setup of the HTTP API, as the database name is part of an operation's URL path, e.g. `/_db/_system/_api/collection/users`.
It is possible to omit the database name from API calls, but then the operation will implicitly use the `_system` database.

But to cut a long story short: if you want to make use of joins, it is required that the collections are in the same database. An alternative is to still have different databases, and then run two separate database-local queries. But that requires joining the data later in the application somehow, so I wouldn't really recommend that.

**Comment by noahehall** [comment]
@jsteemann your idea of running two database-local queries can occur in a single trip over the wire?

e.g. can I say `arrango.runAll([queriy, ...])`

**Comment by noahehall** [comment]
still dont think its possible to eliminate the extra trip, as [even with statements](https://github.com/arangodb/arangodb/blob/master/js/client/modules/@arangodb/arango-statement.js#L144) the execution occurs at the db level
