### ISSUE TITLE
Query results in a single roundtrip / network request

### ISSUE THREAD

**Issue by lostpebble** [arangodb/arangojs#653]
I've been messing around with the querying today, and I've noticed that for all queries I've only been able to get a cursor returned - but to actually get results, we need to call the various APIs on that cursor. This surely entails making an unnecessary extra roundtrip?

It kinda seems to go against the documentation outlined here: https://www.arangodb.com/docs/stable/http/aql-query-cursor-query-results.html#single-roundtrip

I've tried setting `batchSize`, but from what I can tell, there are no initial results in the query response, until a separate call is made on the returned cursor.

I'd like to be able to do something like so:

```ts
const query = await db.query(aql`
  FOR d IN ${dataSourceCollection}
    FILTER
      'es_qa_rat_hig' IN d.tags
      AND d.startDate <= "2020-10-01"
    SORT d.title ASC
    RETURN d
  `, {
    batchSize: 20,
    count: true,
  });
  
console.log(query.initialBatch); // <- synchronous, initial batch of 20
```

Is there something I'm missing? I've been searching high and low in the documentation and looked at all the returned objects in the API- but it seems, for the JS driver at least, that there is no way to avoid making a second network trip to the database.

**Comment by pluma** [comment]
The method calls only incur additional requests if necessary. Interacting with a cursor is async to ensure any necessary requests can be made transparently as needed but if the cursor has `hasMore` set to true, there's nothing more to fetch so consuming it won't result in additional requests.

**Comment by lostpebble** [comment]
Thanks, I also just confirmed that this is the case by using some performance timing - just one extra question then, how do we get a hold of `hasMore` ? It seems on the cursor it is called `_hasMore` (`cursor.hasMore` is `undefined`) so I can do something like:

```ts
console.log(query._hasMore);
```

But this is not typed correctly, so TypeScript gives me an error.

Is this the correct usage? Or is there another way to check that there is still another batch to come? Right now we only have `hasNext()`, but nothing in the way of `hasNextBatch()`.

Looking at it more, I'm guessing the common usage would be to pull the batch first and then just check `hasNext()`:

```ts
let batchResults = await query.nextBatch();
console.log(`Has next: ${query.hasNext()}`);
```

---

> if the cursor has `hasMore` set to true

I'm assuming you meant `false` here.

~Also, lastly, is `ArrayCursor.extra.stats.executionTime` the actual execution time for the query? It doesn't seem to change either, as we call more cursor methods. Because taking into account the other cursor methods, a roundtrip is taking at most `1.1ms`, but my initial query takes `3.7ms` in total - the execution time given however is super low.~

Nevermind, just managed to find (in a random github issue somewhere) that `executionTime` is measured in seconds. Seems like a strange metric to choose, but at least it makes sense in my performance measurements now.
