### ISSUE TITLE
how to set the replicationFactor on a graph?

### ISSUE THREAD

**Issue by mikestaub** [arangodb/arangojs#659]
I tried this but it is not working:

```
const db = new Database();
const graph = db.graph('some-graph');
const info = await graph.create({
  replicationFactor: 3,
  options: {
    replicationFactor: 3,
  },
  edgeDefinitions: [{
    collection: 'edges',
    from: ['start-vertices'],
    to: ['end-vertices']
  }]
}, {
  replicationFactor: 3
});
```

**Comment by pluma** [comment]
The HTTP API indicates that the only place the `replicationFactor` is expected is in the `options` property, so the other two are redundant.

On Slack you indicated that this is the error you're seeing:

> Failed to initialize database: replicationFactor must not be lower than minimum allowed replicationFactor (3)

Can you clarify if this is an exception the `await graph.create` call throws or something you're seeing elsewhere?

**Comment by mikestaub** [comment]
Thanks for that tip, it was in fact a bug in my code. It works now!
