### ISSUE TITLE
Javascript query not working

### ISSUE THREAD

**Issue by gitgkk** [arangodb/arangojs#663]
I'm using arangodb javascript driver version 6 and trying to setup document database and query system. I'm not able to get the desired result.

```js
const view = db.arangoSearchView("docsView", "arangosearch", {});
view.properties({
  links: {
    /* collection Link 0 with additional custom configuration: */
    'docsView':
    {
      /* examine fields of all linked collections,
         using default configuration: */
      includeAllFields: true,
      fields:
      {
        /* a field to apply custom configuration
           that will index English text: */
        name:
        {
          analyzers: ["text_en"]
        },
      }
    },
  }
}
);

var docList = db.query(`FOR doc IN docsView
  SEARCH PHRASE(doc.content, "aibelte", "text_en")
  RETURN doc`);
```
The returned result is empty.

**Comment by pluma** [comment]
(I've edited your comment to add a code fence around your JS code.)

This doesn't seem like an issue with arangojs itself. For support with using ArangoDB please try out the ArangoDB Community Slack: https://slack.arangodb.com/

**Comment by pluma** [comment]
I'm closing this ArangoDB-related question due to inactivity. Please check the community slack if you need further assistance: https://slack.arangodb.com
