### ISSUE TITLE
ArangoCollection interface should also include 'type' 

### ISSUE THREAD

**Issue by sweeneki** [arangodb/arangojs#668]
current:
export interface ArangoCollection {
  isArangoCollection: true;
  name: string;
}

should be:
export interface ArangoCollection {
  isArangoCollection: true;
  name: string;
  type: CollectionType
}

This allows user to determine the collection type which is quite useful when handling the two different types of collections.

**Comment by pluma** [comment]
There's no difference between `DocumentCollection` and `EdgeCollection` in arangojs 7 (both are simply different interfaces implemented by the `Collection` type) so the only way to determine which kind of collection you're dealing with if you don't know in advance is to "ask the server", i.e. use `await collection.get()`. Also the `ArangoCollection` interface is the lowest common denominator and primarily serves to identify objects that can be passed into AQL queries.

**Comment by pluma** [comment]
I'm closing this question because of inactivity. If you need further assistance, feel free to reopen it.
