### ISSUE TITLE
jsdoc?

### ISSUE THREAD

**Issue by robross0606** [arangodb/arangojs#678]
I've tried multiple ways to get jsdoc imported from arangojs into our project.  From what I can tell, the npm library itself is completely devoid of any inline documentation.  Is there any way to get jsdoc available on the npm library so we get more than undocumented type-ahead?

**Comment by pluma** [comment]
@robross0606 The typedoc comments are only provided in the v7 branch. The current `latest` release of arangojs on npm is still v6. If you want to install the latest release candidate, try `npm install arangojs@next`.

**Comment by pluma** [comment]
I'm closing this as v7 has been out for a while, which should solve this issue. Feel free to reopen if there's anything we can do.
