### ISSUE TITLE
Where did the API reference go?

### ISSUE THREAD

**Issue by epluribusunix** [arangodb/arangojs#686]
The drivers page on the ArangoDB web site used to have two links under "ArangoJS":
   - Getting Started
   - Reference

Clicking on "Reference" would expand the menu, giving you access to the rest of the API spec and example code.  Now, it points to the [home page](https://arangodb.github.io/arangojs/) for the arangojs repo.  Selecting any of the v7.x options sends you to a repo where there is only a skimpy (although very useful) readme.

Where can I find documentation similar to the v6.x driver, [like this](https://arangodb.github.io/arangojs/6.14.1/Reference/index.html)?

**Comment by pluma** [comment]
You were on the right track. The API reference is split up into modules, which are linked on the right hand side of the README you were looking at:

![image](https://user-images.githubusercontent.com/1280922/93601001-ce653e00-f9c0-11ea-99b8-3665c7bb70cf.png)

You should probably start here: https://arangodb.github.io/arangojs/7.0.1/modules/_index_.html

**Comment by pluma** [comment]
I've added a direct link to the index module of the latest API docs to the README, which should help point people in the right direction: https://github.com/arangodb/arangojs/commit/e6157d2756cc3b3e50533db7624d0ebdd4f370b6
