### ISSUE TITLE
How to check if edgeCollection exists, in v7.0.1

### ISSUE THREAD

**Issue by KrishnaPG** [arangodb/arangojs#688]
After upgrading to latest version 7.0.1, encountering some problems with edgeCollections. For example, the below code used to work fine in v6:
````javascript
	const coll = db.edgeCollection(edgeName);
	return coll.exists().then(exists => {
		if (exists) return coll;
		// create if it does not exist
		return coll.create({ waitForSync: true })
			.then(() => g.addEdgeDefinition({ collection: edgeName, from: [fromName], to: [toName] }))
			.then(() => coll)
	});
````

The goal is to first verify if the `edgeCollection` exists or not, and create it if it does not exist. But there does not seem to be any `exists()` method available in the `GraphEdgeCollection` class

I am trying the below code, it is giving error:
````javascript
	const coll = g.edgeCollection(edgeName); 
	return coll.exists().then(  //<-ERROR: .exists() is not a function

````
What is the right way to verify and create the `edgeCollection` on a graph?

**Comment by pluma** [comment]
In v7 graph collections only include methods that are actually part of the graph API to avoid confusion between which actions will be "managed" or not (e.g. if edges will be deleted along with vertices or not). So you need to talk to the underlying actual collection instead of the graph (edge) collection.

Normally you would do this by using `db.collection(edgeName)` but if you already use the graph API then switching back and forth between graph collections and the underlying actual collections can be tedious, so there's a convenience property called `collection` on each graph collection that exposes the underlying actual collection:

```js
const coll = g.edgeCollection(edgeName);
return coll.collection.exists().then(exists => {
  if (exists) return coll;
  return coll.collection.create({ waitForSync: true })
    .then(() => g.addEdgeDefinition({ collection: coll, from: [fromName], to: [toName] }))
    .then(() => coll);
});
```

**Comment by pluma** [comment]
FYI I'd recommend checking out the [migration guide](https://arangodb.github.io/arangojs/MIGRATING#graph-collections) for more examples on the changes between v6 and v7. The section _Graph collections_ gives the following explanation:

> Graph vertex and edge collections no longer implement the generic collection API methods to avoid confusion between operations that are aware of the graph definition (and can trigger graph-related side-effects) and those that directly access low-level operations.
>
> As a convenience both graph collection types still provide access to the low-level collection interface via the collection property:
>
> ```diff
>  const graphEdges = graph.edgeCollection("edges");
> -const outEdges = graphEdges.outEdges("vertices/start");
> +const outEdges = graphEdges.collection.outEdges("vertices/start");
> ```

Feel free to reopen this issue if you think there's anything we can do to make the migration eaier.

**Comment by KrishnaPG** [comment]
Thank you @pluma .

It is slightly confusing that the documentation (ref: https://arangodb.github.io/arangojs/7.0.1/interfaces/_collection_.documentcollection.html ) illustrates the `document collection` and `edge collection` in hierarchical relationship listing all the methods in both of them, and in the code some of these methods give error, being not available. 

Your explanation is helpful.

![image](https://user-images.githubusercontent.com/4610831/93607948-a2a97e80-f9e7-11ea-8efb-f11ee5736fa2.png)

**Comment by pluma** [comment]
Yeah, that's ambiguous, but that's for [EdgeCollection](https://arangodb.github.io/arangojs/7.0.1/interfaces/_collection_.edgecollection.html), not [GraphEdgeCollection](https://arangodb.github.io/arangojs/7.0.1/classes/_graph_.graphedgecollection.html). It's slightly more obvious with `DocumentCollection` vs `GraphVertexCollection` but sadly the term "edges" is used both in ArangoDB in general and in the graph API.

**Comment by pluma** [comment]
FYI the changes can currently only be seen in the development build of the documentation as release versions are permanent. The changes will show up in the documentation of 7.0.2 when it it published, though.

You can find the most recent development build at this URL, which always reflects the current `main` branch: https://arangodb.github.io/arangojs/devel/index.html

I've added a sentence to the definition of `EdgeCollection` to help resolve the ambiguity: https://arangodb.github.io/arangojs/devel/interfaces/_collection_.edgecollection.html

**Comment by KrishnaPG** [comment]
Thank you @pluma The links are helpful.

I am slightly confused: this "EdgeCollection" vs "GraphEdgeCollection" - are there two kinds of edge collections? I thought only graphs can have edges. Or, is it more like `EdgeCollection == GraphEdgeCollection.collection` from your above code?

I guess from your above reply, this has something to do with the actions being "managed". That raises an interesting point I did not consider before (but you have rightly pointed in your reply): so, if a vertex is removed, would the edges to/from it be removed? 

From the documentation of the `vertex collection`'s `remove` method it is not clear if that happens (or not): https://arangodb.github.io/arangojs/devel/classes/_graph_.graphvertexcollection.html#remove

I am trying to understand, when I should use the `GraphEdgeCollection` and when I can just simply use `GraphEdgeCollection.collection`, since apparently both seem to support some methods, such as `remove`, `save` etc. as common, and it is not clear which one should be used in which case. Or is it safe to assume that both can be used in any scenario safely? 

I guess if one has to satisfy the referential criteria (such as removing the associated vertices, edges etc.) one has to use the Graph collection methods and if one just wants to only manipulate the underlying document (without regard to the graph integrity / constraints) then one should use the underlying `.collection` - is that correct?

**Comment by pluma** [comment]
The graph collection types implement the General Graph API (what the documentation calls "named graphs"): https://www.arangodb.com/docs/stable/http/gharial.html

ArangoDB has edge collections and document collections. The Graph API builds on top of those: https://www.arangodb.com/docs/stable/graphs-general-graphs.html

The arangojs documentation assumes a certain level of familiarity with ArangoDB. You can find a primer on the differences between named graphs and "anonymous graphs" (i.e. working with the underlying edge collections directly) here, also linked in the above documentation: https://www.arangodb.com/docs/stable/graphs.html

If you are not interested in any of the graph features beyond traversing along edges in AQL, you don't strictly need to use graphs and can instead work with the underlying edge collections directly. You can also "upgrade" to using the Graph API later if you decide to stick with directly using the edge collections for now.
