### ISSUE TITLE
I am getting connection reset error when trying execute two queries at the same time?

### ISSUE THREAD

**Issue by syam0000x** [arangodb/arangojs#690]
Hello All,

I am using arangojs v6.14.1 and arangodb version 3.6.4. 

I have nodejs express app which intended to serve client requests. 

I am experiencing an issue while executing concurrent requests. The database connection hangup when I concurrently process client requests:

What the app will do when it receives a request?
- Open a database connection - 
`db = new Database(dbConfig.url);
  db.useDatabase(dbConfig.name);
 db.useBasicAuth(dbConfig.username, dbConfig.password);`

There are multiple middleware functions that need to access to perform various functions and accessibility checks. And for each middleware I tried to 
* open a new database connection -> 
* perform the action ->
*  close the connection -> 
* return the result to next middleware.

This works fine with single request at a time. But if I tried to call two APIs at same time, I am getting CONNECTIONRESET error. And also throwing socket hangup error.

I tried to commend out the close connection method and it started working fine for a while. But when I increased the number of connections, it again showing the same error as "CONNECTIONRESET".

I have searched the documentation of arangojs regarding the connection manipulation. But I havent found any information regarding the same.

I hope to get some help from the community here.

Any help would be deeply appreciated.

Thanks
Syam

**Comment by pluma** [comment]
You shouldn't generally need to use `.close` unless you want to discard the arangojs driver instance (e.g. if you're just using arangojs once in a long-running script). Arangojs communicates over HTTP, which means it merely uses keep-alive to keep the HTTP sockets open a little longer after the response has been received in case it needs to perform another request.

Generally speaking, the expected workflow is

1. Create your db instance (with auth, db, etc)
2. Eventually perform your request
3. Handle the response
4. There is no step 4

**Comment by syam0000x** [comment]
@pluma  Thanks a lot for the reply :) 

Its working fine now 👍
