### ISSUE TITLE
Special characters are not decoding properly

### ISSUE THREAD

**Issue by sudhish-ps** [arangodb/arangojs#691]
The special characters in the _id fields especially child attributes are not decoding properly for example
{
    "_id": "7b573a0a-e51e-53a0-8a7b-585b9192e068",
    "type": "dimensional",
    "fields": [
      {
        "_id": "Hole Top Small_Ø",
        "name": "Hole Top Small.Ø",
        "type": "number"

If we read this document we are getting _id of fields as "Hole Top Big_Ã".
So how to correct this issue. This can impact in migration activities from another DB's

**Comment by pluma** [comment]
Interesting. Does this only affect fields named `_id` or does it also affect `name` in this example?

**Comment by sudhish-ps** [comment]
> Interesting. Does this only affect fields named `_id` or does it also affect `name` in this example?

It affect only the field named '_id'.

**Comment by pluma** [comment]
@jsteemann This sounds familiar. I remember an early 3.x issue with fields named `_key` being handled differently. Is it possible there's a bug when documents have nested fields named `_id` and this interferes with character encoding?

/cc @joerg84

**Comment by sudhish-ps** [comment]
Hi @pluma , @jsteemann ,

Do we have any fix for this _id field encoding issue ?.

**Comment by pluma** [comment]
@sudhish-ps can you provide additional information like which version of ArangoDB you're using? @jsteemann and I were unable to reproduce this problem with 3.6, 3.7 and the current devel branch of ArangoDB, neither via ArangoDB directly nor via arangojs. There's no reason the field named `_id` should be encoded any differently either.

**Comment by sudhish-ps** [comment]
Hi @pluma , @jsteemann , @joerg84,

Earlier I used 3.6.5v of ArangoDB where I used to see this encoding issue.
However, after installing 3.7.3v of ArangoDB I was not able to reproduce or see this encoding issue, looks like it is resolved.
Thanks for the time.
