### ISSUE TITLE
outEdges() and inEdges() no longer works on 7.x

### ISSUE THREAD

**Issue by robross0606** [arangodb/arangojs#704]
It appears that `outEdges()` and `inEdges()` are incorrectly validating the collection against the passed in IDs on 7.x driver.

This Jest unit test fails:
```js
  it('Gets in edges and out edges from Arango', async () => {
    const db = new Database({
      url: config.arangoDb.url,
      databaseName: config.arangoDb.database
    })
    const edgeCollection = await db.createEdgeCollection('links')
    const edgeCollectionData = await edgeCollection.get()
    expect(edgeCollectionData.type).toBe(CollectionType.EDGE_COLLECTION)
    
    await expect(edgeCollection.outEdges('notLinks/test1')).resolves.toBeEmptyArray()
    await expect(edgeCollection.inEdges('notLinks/test1')).resolves.toBeEmptyArray()
  })
```
The error message is:
```    
Document ID "notLinks/test1" does not match collection name "links"
```

How are these functions, which are available only on `EdgeCollection` types, supposed to work now?  The entire semantics of the functions rely on the document IDs _not_ matching the edge collection name.

I suspect this is a regression caused by http://arangodb.github.io/arangojs/MIGRATING#cross-collection-operations.

**Comment by pluma** [comment]
Oops, you're right. `documentHandle` should take a flag to decide whether it should allow foreign collections to support this use case. This also affects `edges`.

**Comment by wilsongoode** [comment]
Having this same issue trying to retrieve in/out edges on a particular document. @robross0606 thank you for the clear issue report! I think I can manage a workaround in my app, but was feeling like I was crazy for expecting the edge collection to be able to reference a document's id. Always good to be able to point to a clear bug rather than a mystery.

**Comment by robross0606** [comment]
@pluma, why was this closed?  Has it been addressed with a PR?
