### ISSUE TITLE
createGraph() doesn't write to the database but createCollection does!

### ISSUE THREAD

**Issue by enjoysmath** [arangodb/arangojs#718]
Is there any reason why my code is not writing to the database?  I am calling each successfully without errors and collections are writing to the database and I'm able to do a for-loop insert query to add documents to the collection.

However, createGraph is not writing to the database any graph.

**Comment by pluma** [comment]
I'm not sure what you mean by "not writing to the database". How do you determine whether it succeeded?

**Comment by pluma** [comment]
I'm closing this question due to inactivity. Please check the community slack if you need further assistance: https://slack.arangodb.com
