### ISSUE TITLE
Proper way of handling ECONNRESET error

### ISSUE THREAD

**Issue by orgrimarr** [arangodb/arangojs#719]
Hi,
The issue #709 say that ECONNRESET error shouldn't be retried by arangojs because it can lead to data corruption. 

My question is, if this error cannot be handled by arangojs, what is the best way to handle it in order to provide high availability / no downtime ? 

If my query is a simple search, retrying the request in my code shouldn't be an issue. But what about an insert / update / a transaction ?

Is there a mecanism to check if a query as been processed by arango that i can use to retry my query safely ? 

It is safe to retry every failed query outside arangojs ?

**Comment by pluma** [comment]
This question is really up to the application, not ArangoDB and depends on what exactly you were trying to do.

I don't think there's any generic way ArangoDB can tell you if whatever you tried succeeded. Depending on what you were trying to do you'll need to think about how to recover from a potential error before trying again.

Note that this isn't a problem unique to ArangoDB. This can happen with any network request if the connection drops before the response is received.

**Comment by pluma** [comment]
I'm closing this ArangoDB-related question due to inactivity. Please check the community slack if you need further assistance: https://slack.arangodb.com
