### ISSUE TITLE
Which client driver for 2.7 arangodb server

### ISSUE THREAD

**Issue by petitchevalroux** [arangodb/arangojs#72]
Hello,

I test this lib with a 2.6 arangodb server and everything is ok. But now, I want to use batch request for insert/update.

I saw that Triagens once support batch but not this one.

The following desc is a bit confusing to me : "The official ArangoDB JavaScript driver. This is the repository for the new driver starting with version 3.0.0. For the legacy 2.x version see https://github.com/triAGENS/ArangoDB-JavaScript. "

When you say "3.0" is it for the driver or server version ?

**Comment by jsteemann** [comment]
The server version is still 2.6, with 2.7 to be released soon.
The "3.0.0" and "legacy 2.x version" mentions refer to the version of the arangojs driver.

**Comment by petitchevalroux** [comment]
@jsteemann ty for your answer so I cant use batch with arangodb/arangojs :'(

**Comment by petitchevalroux** [comment]
@jsteemann btw do your lib works with 2.6 arangodb server ? :dancers:

**Comment by jsteemann** [comment]
I am not the maintainer of arangojs, but AFAIK it works with a 2.6 server. The REST API changes between the 2.6 and 2.7 server versions are minimal.

**Comment by pcraum** [comment]
by "your lib", i meaned "triAGENS/ArangoDB-JavaScript" ;)

**Comment by petitchevalroux** [comment]
by "your lib", i meaned "triAGENS/ArangoDB-JavaScript" ;)

**Comment by jsteemann** [comment]
arangojs doesn't support batch requests, but if the goal is to insert multiple documents into a collection at once, there is the `import` method: https://www.npmjs.com/package/arangojs#bulk-importing-documents

**Comment by pcraum** [comment]
the goal is to fetch document => if not exist => insert else update in batch

**Comment by petitchevalroux** [comment]
the goal is to fetch document => if not exist => insert else update in batch

**Comment by pluma** [comment]
Yes, there currently isn't any support for batch requests in arangojs.

**Comment by jsteemann** [comment]
The ArangoDB REST API for `/_api/import` should support conditional insert/updates. Quoting from the source code:
> @RESTQUERYPARAM{onDuplicate,string,optional}
> Controls what action is carried out in case of a unique key constraint
> violation. Possible values are:
>
> - *error*: this will not import the current document because of the unique
>   key constraint violation. This is the default setting.
>
> - *update*: this will update an existing document in the database with the 
>   data specified in the request. Attributes of the existing document that
>   are not present in the request will be preseved.
>
> - *replace*: this will replace an existing document in the database with the
>   data specified in the request. 
>
> - *ignore*: this will not update an existing document and simply ignore the
>   error caused by a unique key constraint violation.
>
> Note that that *update*, *replace* and *ignore* will only work when the
> import document in the request contains the *_key* attribute. *update* and
> *replace* may also fail because of secondary unique key constraint violations.

So maybe it's only a matter of which options to pass when calling `import()`?

**Comment by petitchevalroux** [comment]
@jsteemann Thanks a lot
adding onDuplicate=update on the POST query string does the tricks.
and using arangojs collection.import([document], {"onDuplicate": "update"}, callback);

**Comment by jsteemann** [comment]
@petitchevalroux : thanks for the confirmation. I have also adjusted the repository description so there shouldn't be any future confusion about which ArangoDB server versions the driver supports.
Should we close this issue now?

**Comment by petitchevalroux** [comment]
Yep ;-)
