### ISSUE TITLE
fullCount value not provided in output (version >= 7.0.0)

### ISSUE THREAD

**Issue by andrea-tesei** [arangodb/arangojs#721]
Hello,
I'm experiencing a problem while executing query with arangojs version greater or equal than 7.0.0. When I request fullCount output via query options, the `extra.stats.fullCount` attribute is not present in the output as specified in API documentation.

This behavior is not present for arangojs version lower than 7.0.0 (successfully tested with v.6.14.1).

If you need other information please let me know. Looking forward to hearing from you. Thanks

**Comment by pluma** [comment]
I can't replicate this issue:

```js
const cursor = await db.query(aql`FOR i IN 1..999 RETURN i`, {fullCount: true});
console.log(cursor.extra.stats.fullCount); // 999
```

Can you provide an example of the code that's causing this problem?

**Comment by pluma** [comment]
I'm closing this issue as not replicable.
