### ISSUE TITLE
precaptureStackTraces does not enhance stack traces for common errors.

### ISSUE THREAD

**Issue by radicaled** [arangodb/arangojs#722]
For common mistakes, like a malformed AQL query via `db.query`, or an operation like `db.save` on an edge collection missing `_to` or `_from`, the stack traces arangojs generates aren't coherent even with precaptureStackTraces.

I think that's because error responses from the server don't have the enhanced stack traces added to them? EG https://github.com/arangodb/arangojs/blob/8fe4682252ad2771e1c721fd2d8f05807cfe6dce/src/connection.ts#L900

These kinds of errors account for almost all the errors I see, so it would be great if `precaptureStackTraces` enhanced these ones as well.

**Comment by radicaled** [comment]
Some minor experimentation indicates that modifying https://github.com/arangodb/arangojs/blob/8fe4682252ad2771e1c721fd2d8f05807cfe6dce/src/connection.ts#L900 to append `task.stack` to the ArangoError used for rejecting the promise improves error diagnostics considerably.

Would a PR that appends stack traces generated by `precaptureStackTraces` to these kinds of errors be accepted?

**Comment by pluma** [comment]
Looking at this code now, I'm not sure _when_ the stack traces even get added. I'm pretty sure the intention was to also augment the stack traces of `HttpError`s and `ArangoError`s but I think they're currently bypassing that logic entirely so this probably only affects network errors or something?

I'll look into this.

**Comment by radicaled** [comment]
> ... but I think they're currently bypassing that logic entirely so this probably only affects network errors or something?

I believe this is correct: I've only ever seen `precaptureStackTrace` seem to work when I can't connect to my local ArangoDB instance because I haven't brought it up yet. Currently we're using a framework to capture and enhance ArangoDB errors locally via `Error.captureStackTrace` + dumping any provided AQL queries into the exception text, but it'd be great to see `precatureStackTrace` working across more error situations so we can drop that part from our codebase.
