### ISSUE TITLE
produce esm build for bundlers

### ISSUE THREAD

**Issue by autumnblazey** [arangodb/arangojs#731]
would it be possible to create an es module build for use in bundlers like rollup?

**Comment by pluma** [comment]
We did this in an older major version and it got messy to maintain. There are currently no plans to do this as the main benefit tends to be tree shaking, which doesn't seem to have any effect because of how this library's API works.

**Comment by autumnblazey** [comment]
ah I see. I'm using this in node and don't really care much about tree shaking.

My main concern is about having to use [`@rollup/plugin-commonjs`](https://www.npmjs.com/package/@rollup/plugin-commonjs), which takes a commonjs module and converts it to esm so it can be used in rollup. I feel like it would emit a lot of unnecessary code because the code was transpiled from typescript esm, down to commonjs, then back up to esm.

As an alternative, I could try installing the Github repo and then importing the source files, and have rollup typescript plugin handle transpilation from typescript

**Comment by autumnblazey** [comment]
hmm.. I am not actively needing or pursuing this at the moment, and if it is too difficult to maintain I understand that it is not worth the maintenance cost. I will close this, but thank you for considering!
