### ISSUE TITLE
documentCollection.update not updates an existing value with empty object

### ISSUE THREAD

**Issue by hasithajayasundara** [arangodb/arangojs#733]
I have modified [this](https://github.com/arangodb/arangojs/blob/53807e9c1526d91419e303d58c70cb77232226ed/src/test/14-document-collections.ts#L168) test as follows to illustrate what I was trying to do. 

```js
it("updates the given document", async () => {
      // New person entry
      const data = { potato: "tomato", person: { info: { name: "Jane", age: "10"} } };
      const meta = await collection.save(data, { returnNew: true });
      const doc = meta.new!;
      // Update person entry with {}
      await collection.update(doc, { sup: "dawg", person: {} });
      const newData = await collection.document(doc._key);
      expect(newData).to.have.property("potato").that.equals(doc.potato);
      expect(newData).to.have.property("sup").that.equals("dawg");
      // This fails as update did not update the person to {} but keeps the old value
      expect(newData).to.have.property("person").that.equals({});
 });
```
Idea is I'm trying to update the `person` to `{}` which holds a value of `{ info: { name: "Jane", age: "10"} } }`. 

## Issue
`collection.update` does not update the person entry to {} but keeps the old value  `info: { name: "Jane", age: "10"} }`.

**Comment by autumnblazey** [comment]
i think thats intended behavior... maybe modify the js object to have `person: {}` then replace the object in the database?

**Comment by pluma** [comment]
Update does a "merge" by default. You probably want to set `mergeObjects` to `false`: http://arangodb.github.io/arangojs/7.5.0/modules/_collection_.html#collectionupdateoptions

**Comment by hasithajayasundara** [comment]
@pluma @autumnblazey thanks for the replies. `mergeObjects to false` resolved the issues. Closing this.
