### ISSUE TITLE
[Cluster] Issues with ECONNRESET / socket hang up

### ISSUE THREAD

**Issue by Vouk** [arangodb/arangojs#739]
We're having issues when the setup is based on clusters (behind a load balancer).

As a health test we are getting the list of databases each minute.

11:31 21/07/21	Error while getting the list of databases. (socket hang up)
11:21 21/07/21	Error while getting the list of databases. (socket hang up)
10:33 21/07/21	Error while getting the list of databases. (socket hang up)
09:13 21/07/21	Error while getting the list of databases. (socket hang up)
08:48 21/07/21	Error while getting the list of databases. (socket hang up)
08:07 21/07/21	Error while getting the list of databases. (socket hang up)
07:42 21/07/21	Error while getting the list of databases. (socket hang up)
07:14 21/07/21	Error while getting the list of databases. (socket hang up)
06:23 21/07/21	Error while getting the list of databases. (socket hang up)
05:57 21/07/21	Error while getting the list of databases. (socket hang up)
05:04 21/07/21	Error while getting the list of databases. (read ECONNRESET)
04:47 21/07/21	Error while getting the list of databases. (socket hang up)
04:28 21/07/21	Error while getting the list of databases. (socket hang up)

When there is just a single node everything works fine. But as soon as there are multiple nodes (like 3) we are getting this errors.

**Comment by pluma** [comment]
I'm closing this ArangoDB-related question due to inactivity. Please check the community slack if you need further assistance: https://slack.arangodb.com
