### ISSUE TITLE
Accessing collection when using Promise

### ISSUE THREAD

**Issue by Kurtas** [arangodb/arangojs#74]
Hi, 

 I am using Promise with arrango, but I find that accessing collection is also promisify.
I want to ask if it bug, this isn't makred as async method in API https://github.com/arangodb/arangojs#accessing-collections

```javascript
const e = self.arDb.edgeCollection('edge');
const c = self.arDb.collection('vertex');
console.log(c);
console.log(e);


Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _progressHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _settledValue: undefined }
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _progressHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _settledValue: undefined }

```

**Comment by pluma** [comment]
You're probably using the latest stable release (3.9.1). The API docs reflect the latest alpha (4.0.0-alpha7 at this time). Sadly npm seems to default to showing the README of the most recent release even if the `latest` tag is set to something else.

You can get the alpha by running `npm install arangojs@alpha` or view the README for 3.9.1 by looking at https://github.com/arangodb/arangojs/tree/v3.9.1

**Comment by Kurtas** [comment]
I started using alpha version, thanks for info
