### ISSUE TITLE
With aql template strings, I can use Document/EdgeCollections in templates but not Graphs.

### ISSUE THREAD

**Issue by earslap** [arangodb/arangojs#740]
Is this intended? Inside ${} within an aql template, I can refer to document collection objects directly and the templating system does its interpolation job, but if I use a Graph object inside ${} the queries fail. I have to explicitly use ${myGraph.name} and refer to it by name for the query to work. Is this intended behavior?

**Comment by alexgorbatchev** [comment]
Can also confirm this. Same question. Feels unintentionally broken.

**Comment by awlayton** [comment]
This issue seems to be back?

If I do `${myGraph}` it gets a key like `@value0` but the query fails unless I change it to `value0` manually, or use `${myGraph.name}`.
