### ISSUE TITLE
documentCollection.save return doc without JSON document what was saved.

### ISSUE THREAD

**Issue by Kurtas** [arangodb/arangojs#75]
Hi, 

I installed arangojs@4.0.0-alpha7 today and I have probably problem with documentCollection.save method. This method returns doc without JSON document what was saved.

Help isn't clear in this case (https://github.com/arangodb/arangojs#documentcollectionsave) so I want to ask you, if it's expected behavior or it's bug?

See example:
```javascript
const c = self.arDb.collection('vertex');
c.save({name: l2.name}).then((doc) => {
   console.log(doc);
}

{ error: false,
    _id: 'vertex/82518834183',
    _rev: '82518834183',
    _key: '82518834183' } ]
}
```
Thanks

**Comment by pluma** [comment]
Yes, the documentation is wrong in that case. Thanks for catching that.

**Comment by Kurtas** [comment]
Thanks for answer. I think that returning the entire document would be more useful ;)

**Comment by pluma** [comment]
This driver aims to be as low level as possible while still being useful. In most cases the result values are just the raw server response.

Returning the entire document in this case would mean removing the `error` field from the server response and merging it with the original document from the request. Doing this would present some problems (e.g. if the object passed in as request document is modified after it has been sent to the server, it would no longer reflect the document that was actually saved, so the only way to avoid this would be to deep-clone the entire document before sending it but that adds unnecessary overhead in many scenarios where the response is not actually used).

**Comment by dmk255** [comment]
Sorry for rezing such an old thread.

I am also experiencing this issue where the vertex returned by the save action does not include the document properties submitted to it. This results in code that looks like the following:
```
const savedItem = Object.assign({}, stagedItem, (await collection.save(stagedItem)).vertex));
```

**Comment by pluma** [comment]
@dmk255 Have you seen the `returnNew` option for the save methods?

**Comment by dmk255** [comment]
@pluma I was using returnNew when I had initially implemented this in Foxx. It doesn't look like it's available for the graph collection functions: [graphVertexCollection.save](https://github.com/arangodb/arangojs#graphvertexcollectionsave)

**Comment by pluma** [comment]
Hm, looks like you're right. The graph HTTP API doesn't seem to implement this option. This seems like something you might want to report on the ArangoDB issue tracker as a feature request: https://github.com/arangodb/arangodb/issues/new
