### ISSUE TITLE
Connection Error: error in store

### ISSUE THREAD

**Issue by cjarv** [arangodb/arangojs#758]
Failed to connect to database.
...\node_modules\connect-arango\lib\connect-arango.js:110:22
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

...\node_modules\\connect-arango\\lib\\connect-arango.js","function":null,"line":110,"method":null,"native":false},{"column":5,"file":"node:internal/process/t
ask_queues","function":"processTicksAndRejections","line":93,"method":null,"native":false}]}

This is failing because of the store for some reason. I have checked my db object coming from connect-arango and it looks fine. This package worked a few months ago. Let me know if you need any additional information. Thanks for your help.

Cheers,
cjarv

**Comment by pluma** [comment]
I'm closing this as it sounds like this is a problem with `connect-arango` and not `arangojs` and you already have opened an issue there: https://github.com/AlexanderArvidsson/connect-arango/issues/8
