### ISSUE TITLE
docs: built in functions usage example

### ISSUE THREAD

**Issue by vitoladev** [arangodb/arangojs#761]
It would be great to have a usage example for the built in functions of the driver inside the **README.md** such as `collection.document()`,  `collection.documents()`, `collection.save()`, `collection.exists()` etc.

I can send a PR with this usage example to help people that use this library.

**Comment by pluma** [comment]
I'm not sure what you mean. Are you aware of the API documentation? https://arangodb.github.io/arangojs/7.7.0/interfaces/collection.documentcollection.html#document

Depending on your editor/IDE you should also see in-line documentation when using those methods.

**Comment by vitoladev** [comment]
yes, that's exactly what i was looking for, usually i could only see the API documentation inside the methods on VS Code, i didn't found it on my own searching on the website. 

It would be good to mention about this documentation on the README.md about this topic, would be helpful for other people in the same situation.

Thanks!
