### ISSUE TITLE
Can somebody help me with the question that about  connect by node.js module

### ISSUE THREAD

**Issue by realdog** [arangodb/arangojs#78]
Can somebody help me with following issue:
When i use the module, i start my db server with server.disable-authentication = false, and i write the code:
```
var db = new Database('http://127.0.0.1:8000');
db.createDatabase('mydb', function(err, newdb) {
  if (err) {
    console.log('Failed to create database: %j',
      err);
  } else {
    console.log('Database created: %j', newdb.name);
  }
});
```
and 

```
var db = new Database('http://username:password@127.0.0.1:8000');
db.createDatabase('mydb', function(err, newdb) {
  if (err) {
    console.log('Failed to create database: %j',
      err);
  } else {
    console.log('Database created: %j', newdb.name);
  }
});
```
Then i found they all  print 
 ```
Database created: "mydb"
```

why?

**Comment by pluma** [comment]
I can't replicate your problem. Are you sure authentication is correctly enabled?

Your code fails with `UnauthorizedError: Unauthorized` for me in the first example when running arangod with `--server.disable-authentication false`.
