### ISSUE TITLE
puzzled about memory use

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangojs#79]
I have a node app that uses arangojs 3.9.1 (using default values for everything except url and databaseName) and, amongst other things, does the following:

```JavaScript
fooCollection
  .update(key, newFooData)
  .then(function() {
    return db.query('FOR bar IN bars FILTER … UPDATE bar WITH {…some AQL function calls…) IN bars', newBarData);
  })
  .catch(function(error) {…};
```

I have a log I can play back so that the code above gets called 30,000 times, which takes almost 6 minutes. In order to speed this up, I figure I combine both roundtrips to ArangoDB into one with the help of a transaction:

```JavaScript
let action = String(
  function(p) {
    var db = require('org/arangodb').db;
    db.foos.update(p.foo.key, p.foo.newFooData);
    db._query('FOR bar IN bars FILTER … UPDATE bar WITH {…some AQL function calls…} IN bars', p.bar.newBarData);
  });
db.transaction({write: ['foos', 'bars']}, action, {…})
  .catch(function(error) {…};
```

Otherwise, the code is identical. While the new version is 15 seconds faster, I was really surprised that it used MUCH less memory. **The first version with two roundtrips consumes 788MB, the second version with the transaction only uses 433MB.**

I ran each version 3 times to make sure my measurements for time and memory are repeatable (they are). I played back the same log file every time, i.e. used the same dataset. And I restored my db in ArangoDB before every run to the same state.

Any idea why there’s such a big difference in memory between these two versions?

**Comment by pluma** [comment]
Are you talking about the memory use of ArangoDB or that of Node running the driver?

I don't see any obvious reason why the driver should use vastly different amounts of memory in the two cases, unless the result of the query in the first example is pretty big (though your query doesn't seem to have a return value at all).

**Comment by pekeler** [comment]
Node

**Comment by pekeler** [comment]
Ah, the return value. That makes sense.

I'm not happy with the way node handles garbage collection. I'm now manually calling global.gc() on a regular basis which brings memory use down to 60MB, i.e. there's no leak and all is good. Thanks!
