### ISSUE TITLE
"npm run coveralls" throw error

### ISSUE THREAD

**Issue by XescuGC** [arangodb/arangojs#80]
I've just pulled the new version of the repo and now the `npm run coveralls` is broken, i think you need to add the correct folder or you have forgotten to push it to git :smile:

![job__257_1_-_arangodb_arangojs_-_travis_ci_-_vimperator](https://cloud.githubusercontent.com/assets/1532900/10674555/da6ba194-78fb-11e5-8787-2ac3b61fb0ff.png)
(This if from [Travis](https://travis-ci.org/arangodb/arangojs/jobs/86844127))

**Comment by pluma** [comment]
Yeah, I'm a dolt. The pre script had the wrong prefix.
